PocketMine-MP: pocketmine\network\mcpe\protocol\BossEventPacket Class Reference
pocketmine\network\mcpe\protocol\BossEventPacket Class Reference
Public Member Functions
__get ($name)
__set ($name, $value)
canBeSentBeforeLogin ()
decode (PacketSerializer $in)
encode (PacketSerializer $out)
getName ()
handle (PacketHandlerInterface $handler)
pid ()
Static Public Member Functions
static healthPercent (int $bossActorUniqueId, float $healthPercent)
static hide (int $bossActorUniqueId)
static properties (int $bossActorUniqueId, bool $darkenScreen, int $color=BossBarColor::PURPLE, int $overlay=0)
static query (int $bossActorUniqueId, int $playerActorUniqueId)
static registerPlayer (int $bossActorUniqueId, int $playerActorUniqueId)
static show (int $bossActorUniqueId, string $title, float $healthPercent, bool $darkenScreen=false, int $color=BossBarColor::PURPLE, int $overlay=0)
static title (int $bossActorUniqueId, string $title)
static unregisterPlayer (int $bossActorUniqueId, int $playerActorUniqueId)
Public Attributes
int $bossActorUniqueId
int $color
bool $darkenScreen
int $eventType
float $healthPercent
int $overlay
int $playerActorUniqueId
int $recipientSubId = 0
int $senderSubId = 0
string $title
const NETWORK_ID = ProtocolInfo::BOSS_EVENT_PACKET
const PID_MASK = 0x3ff
const TYPE_HEALTH_PERCENT = 4
const TYPE_HIDE = 2
const TYPE_PROPERTIES = 6
const TYPE_QUERY = 8
const TYPE_REGISTER_PLAYER = 1
const TYPE_SHOW = 0
const TYPE_TEXTURE = 7
const TYPE_TITLE = 5
const TYPE_UNREGISTER_PLAYER = 3
Protected Member Functions
decodeHeader (PacketSerializer $in)
decodePayload (PacketSerializer $in)
encodeHeader (PacketSerializer $out)
encodePayload (PacketSerializer $out)
Detailed Description
Definition at line 20 of file BossEventPacket.php.
Member Function Documentation
__get()
pocketmine\network\mcpe\protocol\DataPacket::__get ($name) inherited
Parameters
string $name
Returns
mixed
Definition at line 105 of file DataPacket.php.
__set()
pocketmine\network\mcpe\protocol\DataPacket::__set ($name, $value) inherited
Parameters
string $name
mixed $value
Definition at line 113 of file DataPacket.php.
canBeSentBeforeLogin()
pocketmine\network\mcpe\protocol\DataPacket::canBeSentBeforeLogin () inherited
Implements pocketmine\network\mcpe\protocol\Packet.
Definition at line 42 of file DataPacket.php.
decode()
pocketmine\network\mcpe\protocol\DataPacket::decode (PacketSerializer $in) final inherited
Exceptions
PacketDecodeException
Implements pocketmine\network\mcpe\protocol\Packet.
Definition at line 49 of file DataPacket.php.
decodeHeader()
pocketmine\network\mcpe\protocol\DataPacket::decodeHeader (PacketSerializer $in) protected inherited
Exceptions
BinaryDataException
PacketDecodeException
Definition at line 62 of file DataPacket.php.
decodePayload()
pocketmine\network\mcpe\protocol\BossEventPacket::decodePayload (PacketSerializer $in) protected
Decodes the packet body, without the packet ID or other generic header fields.
Exceptions
PacketDecodeException
BinaryDataException
Reimplemented from pocketmine\network\mcpe\protocol\DataPacket.
Definition at line 111 of file BossEventPacket.php.
References pocketmine\network\mcpe\protocol\serializer\PacketSerializer\getActorUniqueId(), pocketmine\utils\BinaryStream\getLFloat(), pocketmine\utils\BinaryStream\getLShort(), pocketmine\network\mcpe\protocol\serializer\PacketSerializer\getString(), and pocketmine\utils\BinaryStream\getUnsignedVarInt().
encode()
pocketmine\network\mcpe\protocol\DataPacket::encode (PacketSerializer $out) final inherited
Implements pocketmine\network\mcpe\protocol\Packet.
Definition at line 82 of file DataPacket.php.
encodeHeader()
pocketmine\network\mcpe\protocol\DataPacket::encodeHeader (PacketSerializer $out) protected inherited
Definition at line 87 of file DataPacket.php.
encodePayload()
pocketmine\network\mcpe\protocol\BossEventPacket::encodePayload (PacketSerializer $out) protected
Encodes the packet body, without the packet ID or other generic header fields.
Reimplemented from pocketmine\network\mcpe\protocol\DataPacket.
Definition at line 146 of file BossEventPacket.php.
References pocketmine\utils\BinaryStream\putUnsignedVarInt().
getName()
pocketmine\network\mcpe\protocol\DataPacket::getName () inherited
Implements pocketmine\network\mcpe\protocol\Packet.
Definition at line 38 of file DataPacket.php.
handle()
pocketmine\network\mcpe\protocol\BossEventPacket::handle (PacketHandlerInterface $handler)
Performs handling for this packet. Usually you'll want an appropriately named method in the session handler for this.
This method returns a bool to indicate whether the packet was handled or not. If the packet was unhandled, a debug message will be logged with a hexdump of the packet.
Typically this method returns the return value of the handler in the supplied PacketHandler. See other packets for examples how to implement this.
Returns
bool true if the packet was handled successfully, false if not.
Exceptions
PacketDecodeException if broken data was found in the packet
Implements pocketmine\network\mcpe\protocol\Packet.
Definition at line 177 of file BossEventPacket.php.
healthPercent()
static pocketmine\network\mcpe\protocol\BossEventPacket::healthPercent (int $bossActorUniqueId, float $healthPercent) static
Definition at line 85 of file BossEventPacket.php.
hide()
static pocketmine\network\mcpe\protocol\BossEventPacket::hide (int $bossActorUniqueId) static
Definition at line 69 of file BossEventPacket.php.
pid()
pocketmine\network\mcpe\protocol\DataPacket::pid () inherited
Implements pocketmine\network\mcpe\protocol\Packet.
Definition at line 34 of file DataPacket.php.
properties()
static pocketmine\network\mcpe\protocol\BossEventPacket::properties (int $bossActorUniqueId, bool $darkenScreen, int $color = BossBarColor::PURPLE, int $overlay = 0) static
Definition at line 97 of file BossEventPacket.php.
query()
static pocketmine\network\mcpe\protocol\BossEventPacket::query (int $bossActorUniqueId, int $playerActorUniqueId) static
Definition at line 105 of file BossEventPacket.php.
registerPlayer()
static pocketmine\network\mcpe\protocol\BossEventPacket::registerPlayer (int $bossActorUniqueId, int $playerActorUniqueId) static
Definition at line 73 of file BossEventPacket.php.
show()
static pocketmine\network\mcpe\protocol\BossEventPacket::show (int $bossActorUniqueId, string $title, float $healthPercent, bool $darkenScreen = false, int $color = BossBarColor::PURPLE, int $overlay = 0) static
Definition at line 59 of file BossEventPacket.php.
title()
static pocketmine\network\mcpe\protocol\BossEventPacket::title (int $bossActorUniqueId, string $title) static
Definition at line 91 of file BossEventPacket.php.
unregisterPlayer()
static pocketmine\network\mcpe\protocol\BossEventPacket::unregisterPlayer (int $bossActorUniqueId, int $playerActorUniqueId) static
Definition at line 79 of file BossEventPacket.php.
Member Data Documentation
$bossActorUniqueId
int pocketmine\network\mcpe\protocol\BossEventPacket::$bossActorUniqueId
Definition at line 42 of file BossEventPacket.php.
$color
int pocketmine\network\mcpe\protocol\BossEventPacket::$color
Definition at line 49 of file BossEventPacket.php.
$darkenScreen
bool pocketmine\network\mcpe\protocol\BossEventPacket::$darkenScreen
Definition at line 48 of file BossEventPacket.php.
$eventType
int pocketmine\network\mcpe\protocol\BossEventPacket::$eventType
Definition at line 43 of file BossEventPacket.php.
$healthPercent
float pocketmine\network\mcpe\protocol\BossEventPacket::$healthPercent
Definition at line 46 of file BossEventPacket.php.
$overlay
int pocketmine\network\mcpe\protocol\BossEventPacket::$overlay
Definition at line 50 of file BossEventPacket.php.
$playerActorUniqueId
int pocketmine\network\mcpe\protocol\BossEventPacket::$playerActorUniqueId
Definition at line 45 of file BossEventPacket.php.
$recipientSubId
int pocketmine\network\mcpe\protocol\DataPacket::$recipientSubId = 0 inherited
Definition at line 32 of file DataPacket.php.
$senderSubId
int pocketmine\network\mcpe\protocol\DataPacket::$senderSubId = 0 inherited
Definition at line 31 of file DataPacket.php.
$title
string pocketmine\network\mcpe\protocol\BossEventPacket::$title
Definition at line 47 of file BossEventPacket.php.
NETWORK_ID
const pocketmine\network\mcpe\protocol\BossEventPacket::NETWORK_ID = ProtocolInfo::BOSS_EVENT_PACKET
Definition at line 21 of file BossEventPacket.php.
PID_MASK
const pocketmine\network\mcpe\protocol\DataPacket::PID_MASK = 0x3ff inherited
Definition at line 25 of file DataPacket.php.
TYPE_HEALTH_PERCENT
const pocketmine\network\mcpe\protocol\BossEventPacket::TYPE_HEALTH_PERCENT = 4
S2C: Sets the bar percentage.
Definition at line 32 of file BossEventPacket.php.
TYPE_HIDE
const pocketmine\network\mcpe\protocol\BossEventPacket::TYPE_HIDE = 2
S2C: Removes the boss-bar from the client.
Definition at line 28 of file BossEventPacket.php.
TYPE_PROPERTIES
const pocketmine\network\mcpe\protocol\BossEventPacket::TYPE_PROPERTIES = 6
S2C: Updates misc properties of the bar and environment.
Definition at line 36 of file BossEventPacket.php.
TYPE_QUERY
const pocketmine\network\mcpe\protocol\BossEventPacket::TYPE_QUERY = 8
C2S: Client asking the server to resend all boss data.
Definition at line 40 of file BossEventPacket.php.
TYPE_REGISTER_PLAYER
const pocketmine\network\mcpe\protocol\BossEventPacket::TYPE_REGISTER_PLAYER = 1
C2S: Registers a player to a boss fight.
Definition at line 26 of file BossEventPacket.php.
TYPE_SHOW
const pocketmine\network\mcpe\protocol\BossEventPacket::TYPE_SHOW = 0
S2C: Shows the boss-bar to the player.
Definition at line 24 of file BossEventPacket.php.
TYPE_TEXTURE
const pocketmine\network\mcpe\protocol\BossEventPacket::TYPE_TEXTURE = 7
S2C: Updates boss-bar colour and overlay texture.
Definition at line 38 of file BossEventPacket.php.
TYPE_TITLE
const pocketmine\network\mcpe\protocol\BossEventPacket::TYPE_TITLE = 5
S2C: Sets title of the bar.
Definition at line 34 of file BossEventPacket.php.
TYPE_UNREGISTER_PLAYER
const pocketmine\network\mcpe\protocol\BossEventPacket::TYPE_UNREGISTER_PLAYER = 3
C2S: Unregisters a player from a boss fight.
Definition at line 30 of file BossEventPacket.php.
The documentation for this class was generated from the following file:
BossEventPacket.php