PocketMine-MP: PrefixedLogger Class Reference
PrefixedLogger Class Reference
Public Member Functions
__construct (\Logger $delegate, string $prefix)
alert ($message)
critical ($message)
debug ($message)
emergency ($message)
error ($message)
getPrefix ()
info ($message)
log ($level, $message)
logException (\Throwable $e, $trace=null)
logException (Throwable $e, $trace=null)
notice ($message)
setPrefix (string $prefix)
warning ($message)
Detailed Description
Definition at line 20 of file PrefixedLogger.php.
Constructor & Destructor Documentation
__construct()
PrefixedLogger::__construct (\Logger $delegate, string $prefix)
Definition at line 25 of file PrefixedLogger.php.
Member Function Documentation
alert()
SimpleLogger::alert ($message) inherited
Action must be taken immediately
Parameters
string $message
Returns
void
Implements Logger.
Definition at line 25 of file SimpleLogger.php.
References SimpleLogger\log().
critical()
SimpleLogger::critical ($message) inherited
Critical conditions
Parameters
string $message
Returns
void
Implements Logger.
Definition at line 29 of file SimpleLogger.php.
References SimpleLogger\log().
Referenced by SimpleLogger\logException().
debug()
SimpleLogger::debug ($message) inherited
Detailed debug information.
Parameters
string $message
Returns
void
Implements Logger.
Definition at line 49 of file SimpleLogger.php.
References SimpleLogger\log().
emergency()
SimpleLogger::emergency ($message) inherited
System is unusable
Parameters
string $message
Returns
void
Implements Logger.
Definition at line 21 of file SimpleLogger.php.
References SimpleLogger\log().
error()
SimpleLogger::error ($message) inherited
Runtime errors that do not require immediate action but should typically be logged and monitored.
Parameters
string $message
Returns
void
Implements Logger.
Definition at line 33 of file SimpleLogger.php.
References SimpleLogger\log().
getPrefix()
PrefixedLogger::getPrefix ()
Returns
string
Definition at line 41 of file PrefixedLogger.php.
info()
SimpleLogger::info ($message) inherited
Interesting events.
Parameters
string $message
Returns
void
Implements Logger.
Definition at line 45 of file SimpleLogger.php.
References SimpleLogger\log().
log()
PrefixedLogger::log ($level, $message)
Logs with an arbitrary level.
Parameters
mixed $level
string $message
Returns
void
Reimplemented from SimpleLogger.
Reimplemented in pocketmine\plugin\PluginLogger.
Definition at line 30 of file PrefixedLogger.php.
logException() [1/2]
SimpleLogger::logException (\Throwable $e, $trace = null) inherited
Logs a Throwable object
Parameters
Throwable $e
array | null $trace @phpstan-param list<array<string, mixed>>|null $trace
Returns
void
Implements Logger.
Definition at line 57 of file SimpleLogger.php.
References SimpleLogger\critical().
logException() [2/2]
PrefixedLogger::logException (Throwable $e, $trace = null)
Definition at line 34 of file PrefixedLogger.php.
notice()
SimpleLogger::notice ($message) inherited
Normal but significant events.
Parameters
string $message
Returns
void
Implements Logger.
Definition at line 41 of file SimpleLogger.php.
References SimpleLogger\log().
setPrefix()
PrefixedLogger::setPrefix (string $prefix)
Parameters
string $prefix
Definition at line 48 of file PrefixedLogger.php.
warning()
SimpleLogger::warning ($message) inherited
Exceptional occurrences that are not errors.
Example: Use of deprecated APIs, poor use of an API, undesirable things that are not necessarily wrong.
Parameters
string $message
Returns
void
Implements Logger.
Definition at line 37 of file SimpleLogger.php.
References SimpleLogger\log().
The documentation for this class was generated from the following file:
PrefixedLogger.php