PocketMine-MP: pocketmine\block\BlockFactory Class Reference
pocketmine\block\BlockFactory Class Reference
Public Member Functions
fromFullBlock (int $fullState)
get (int $id, int $meta)
getAllKnownStates ()
getMappedStateId (int $fullState)
isRegistered (int $id, int $meta=0)
register (Block $block, bool $override=false)
remap (int $id, int $meta, Block $block)
Public Attributes
SplFixedArray $blastResistance
SplFixedArray $blocksDirectSkyLight
SplFixedArray $light
SplFixedArray $lightFilter
Detailed Description
Manages deserializing block types from their legacy blockIDs and metadata. This is primarily needed for loading chunks from disk.
Definition at line 72 of file BlockFactory.php.
Constructor & Destructor Documentation
__construct()
pocketmine\block\BlockFactory::__construct ()
Definition at line 108 of file BlockFactory.php.
Member Function Documentation
fromFullBlock()
pocketmine\block\BlockFactory::fromFullBlock (int $fullState)
Definition at line 1064 of file BlockFactory.php.
get()
pocketmine\block\BlockFactory::get (int $id, int $meta)
Deprecated:
This method should ONLY be used for deserializing data, e.g. from a config or database. For all other purposes, use VanillaBlocks.
See also
VanillaBlocks
Deserializes a block from the provided legacy ID and legacy meta.
Definition at line 1046 of file BlockFactory.php.
getAllKnownStates()
pocketmine\block\BlockFactory::getAllKnownStates ()
Returns
Block[]
Definition at line 1079 of file BlockFactory.php.
getMappedStateId()
pocketmine\block\BlockFactory::getMappedStateId (int $fullState)
Returns the ID of the state mapped to the given state ID. Used to correct invalid blockstates found in loaded chunks.
Definition at line 1087 of file BlockFactory.php.
isRegistered()
pocketmine\block\BlockFactory::isRegistered (int $id, int $meta = 0)
Returns whether a specified block state is already registered in the block factory.
Definition at line 1071 of file BlockFactory.php.
Referenced by pocketmine\block\BlockFactory\register().
register()
pocketmine\block\BlockFactory::register (Block $block, bool $override = false)
Maps a block type to its corresponding ID. This is necessary to ensure that the block is correctly loaded when reading from disk storage.
NOTE: If you are registering a new block type, you will need to add it to the creative inventory yourself - it will not automatically appear there.
Parameters
bool $override Whether to override existing registrations
Exceptions
RuntimeException if something attempted to override an already-registered block without specifying the $override parameter.
Definition at line 976 of file BlockFactory.php.
References pocketmine\block\Block\getIdInfo(), pocketmine\block\Slab\getStateBitmask(), pocketmine\block\BlockFactory\isRegistered(), and pocketmine\block\Slab\readStateFromData().
remap()
pocketmine\block\BlockFactory::remap (int $id, int $meta, Block $block)
Definition at line 1017 of file BlockFactory.php.
Member Data Documentation
$blastResistance
SplFixedArray pocketmine\block\BlockFactory::$blastResistance
Definition at line 106 of file BlockFactory.php.
$blocksDirectSkyLight
SplFixedArray pocketmine\block\BlockFactory::$blocksDirectSkyLight
Definition at line 101 of file BlockFactory.php.
$light
SplFixedArray pocketmine\block\BlockFactory::$light
Definition at line 91 of file BlockFactory.php.
$lightFilter
SplFixedArray pocketmine\block\BlockFactory::$lightFilter
Definition at line 96 of file BlockFactory.php.
The documentation for this class was generated from the following file:
BlockFactory.php