PocketMine-MP: pocketmine\network\mcpe\protocol\serializer\PacketSerializer Class Reference
pocketmine\network\mcpe\protocol\serializer\PacketSerializer Class Reference
Public Member Functions
feof ()
get (int $len)
getActorRuntimeId ()
getActorUniqueId ()
getBlockPosition ()
getBool ()
getBuffer ()
getByte ()
getCommandOriginData ()
getDouble ()
getEntityLink ()
getEntityMetadata ()
getFloat ()
getGameRules ()
getInt ()
getItemStackWithoutStackId ()
getItemStackWrapper ()
getLDouble ()
getLFloat ()
getLInt ()
getLLong ()
getLong ()
getLShort ()
getLTriad ()
getNbtCompoundRoot ()
getNbtRoot ()
getOffset ()
getRecipeIngredient ()
getRemaining ()
getRotationByte ()
getRoundedFloat (int $accuracy)
getRoundedLFloat (int $accuracy)
getShort ()
getSignedBlockPosition ()
getSignedLShort ()
getSignedShort ()
getSkin ()
getString ()
getStructureEditorData ()
getStructureSettings ()
getTriad ()
getUnsignedVarInt ()
getUnsignedVarLong ()
getUUID ()
getVarInt ()
getVarLong ()
getVector2 ()
getVector3 ()
put (string $str)
putActorRuntimeId (int $eid)
putActorUniqueId (int $eid)
putBlockPosition (BlockPosition $blockPosition)
putBool (bool $v)
putByte (int $v)
putCommandOriginData (CommandOriginData $data)
putDouble (float $v)
putEntityLink (EntityLink $link)
putEntityMetadata (array $metadata)
putFloat (float $v)
putGameRules (array $rules)
putInt (int $v)
putItemStackWithoutStackId (ItemStack $itemStack)
putItemStackWrapper (ItemStackWrapper $itemStackWrapper)
putLDouble (float $v)
putLFloat (float $v)
putLInt (int $v)
putLLong (int $v)
putLong (int $v)
putLShort (int $v)
putLTriad (int $v)
putRecipeIngredient (RecipeIngredient $ingredient)
putRotationByte (float $rotation)
putShort (int $v)
putSignedBlockPosition (BlockPosition $blockPosition)
putSkin (SkinData $skin)
putString (string $v)
putStructureEditorData (StructureEditorData $structureEditorData)
putStructureSettings (StructureSettings $structureSettings)
putTriad (int $v)
putUnsignedVarInt (int $v)
putUnsignedVarLong (int $v)
putUUID (UuidInterface $uuid)
putVarInt (int $v)
putVarLong (int $v)
putVector2 (Vector2 $vector2)
putVector3 (Vector3 $vector)
putVector3Nullable (?Vector3 $vector)
readCreativeItemNetId ()
readItemStackNetIdVariant ()
readItemStackRequestId ()
readLegacyItemStackRequestId ()
readOptional (\Closure $reader)
readRecipeNetId ()
readServerItemStackId ()
rewind ()
setOffset (int $offset)
writeCreativeItemNetId (int $id)
writeItemStackNetIdVariant (int $id)
writeItemStackRequestId (int $id)
writeLegacyItemStackRequestId (int $id)
writeOptional (mixed $value, \Closure $writer)
writeRecipeNetId (int $id)
writeServerItemStackId (int $id)
Static Public Member Functions
static decoder (string $buffer, int $offset)
static encoder ()
Protected Member Functions
__construct (string $buffer="", int $offset=0)
Protected Attributes
$buffer
$offset
Detailed Description
Definition at line 66 of file bedrock-protocol/src/serializer/PacketSerializer.php.
Constructor & Destructor Documentation
__construct()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::__construct (string $buffer = "", int $offset = 0) protected
Reimplemented from pocketmine\utils\BinaryStream.
Definition at line 67 of file bedrock-protocol/src/serializer/PacketSerializer.php.
Member Function Documentation
decoder()
static pocketmine\network\mcpe\protocol\serializer\PacketSerializer::decoder (string $buffer, int $offset) static
Definition at line 76 of file bedrock-protocol/src/serializer/PacketSerializer.php.
encoder()
static pocketmine\network\mcpe\protocol\serializer\PacketSerializer::encoder () static
Definition at line 72 of file bedrock-protocol/src/serializer/PacketSerializer.php.
feof()
pocketmine\utils\BinaryStream::feof () inherited
Returns whether the offset has reached the end of the buffer.
Definition at line 372 of file BinaryStream.php.
get()
pocketmine\utils\BinaryStream::get (int $len) inherited
@phpstan-impure
Exceptions
BinaryDataException if there are not enough bytes left in the buffer
Definition at line 67 of file BinaryStream.php.
Referenced by pocketmine\network\mcpe\protocol\serializer\PacketBatch\decodeRaw(), pocketmine\world\format\io\leveldb\LevelDB\deserializeBlockPalette(), and raklib\protocol\OfflineMessage\readMagic().
getActorRuntimeId()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::getActorRuntimeId () final
Exceptions
BinaryDataException
Definition at line 423 of file bedrock-protocol/src/serializer/PacketSerializer.php.
Referenced by pocketmine\network\mcpe\protocol\AnimateEntityPacket\decodePayload().
getActorUniqueId()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::getActorUniqueId () final
Exceptions
BinaryDataException
Definition at line 412 of file bedrock-protocol/src/serializer/PacketSerializer.php.
Referenced by pocketmine\network\mcpe\protocol\BossEventPacket\decodePayload(), pocketmine\network\mcpe\protocol\ClientboundMapItemDataPacket\decodePayload(), pocketmine\network\mcpe\protocol\PlayerListPacket\decodePayload(), pocketmine\network\mcpe\protocol\SetScoreboardIdentityPacket\decodePayload(), and pocketmine\network\mcpe\protocol\SetScorePacket\decodePayload().
getBlockPosition()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::getBlockPosition ()
Reads a block position with unsigned Y coordinate.
Exceptions
BinaryDataException
Definition at line 436 of file bedrock-protocol/src/serializer/PacketSerializer.php.
Referenced by pocketmine\network\mcpe\protocol\CommandBlockUpdatePacket\decodePayload().
getBool()
pocketmine\utils\BinaryStream::getBool () inherited
@phpstan-impure
Exceptions
BinaryDataException
Definition at line 105 of file BinaryStream.php.
Referenced by pocketmine\network\mcpe\protocol\CommandBlockUpdatePacket\decodePayload(), and pocketmine\network\mcpe\protocol\PlayerListPacket\decodePayload().
getBuffer()
pocketmine\utils\BinaryStream::getBuffer () inherited
Definition at line 59 of file BinaryStream.php.
getByte()
pocketmine\utils\BinaryStream::getByte () inherited
@phpstan-impure
Exceptions
BinaryDataException
Definition at line 117 of file BinaryStream.php.
Referenced by pocketmine\network\mcpe\protocol\BookEditPacket\decodePayload(), pocketmine\network\mcpe\protocol\SetHudPacket\decodePayload(), pocketmine\network\mcpe\protocol\SetScorePacket\decodePayload(), raklib\protocol\AcknowledgePacket\decodePayload(), and pocketmine\network\mcpe\protocol\AvailableCommandsPacket\getEnumValueIndex().
getCommandOriginData()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::getCommandOriginData ()
Exceptions
BinaryDataException
Definition at line 614 of file bedrock-protocol/src/serializer/PacketSerializer.php.
getDouble()
pocketmine\utils\BinaryStream::getDouble () inherited
@phpstan-impure
Exceptions
BinaryDataException
Definition at line 257 of file BinaryStream.php.
getEntityLink()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::getEntityLink ()
Exceptions
BinaryDataException
Definition at line 592 of file bedrock-protocol/src/serializer/PacketSerializer.php.
getEntityMetadata()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::getEntityMetadata ()
Decodes entity metadata from the stream.
Returns
MetadataProperty[] @phpstan-return array<int, MetadataProperty>
Exceptions
PacketDecodeException
BinaryDataException
Definition at line 365 of file bedrock-protocol/src/serializer/PacketSerializer.php.
getFloat()
pocketmine\utils\BinaryStream::getFloat () inherited
@phpstan-impure
Exceptions
BinaryDataException
Definition at line 217 of file BinaryStream.php.
Referenced by pocketmine\network\mcpe\protocol\CorrectPlayerMovePredictionPacket\decodePayload().
getGameRules()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::getGameRules ()
Reads gamerules
Returns
GameRule[] game rule name => value @phpstan-return array<string, GameRule>
Exceptions
PacketDecodeException
BinaryDataException
Definition at line 560 of file bedrock-protocol/src/serializer/PacketSerializer.php.
getInt()
pocketmine\utils\BinaryStream::getInt () inherited
@phpstan-impure
Exceptions
BinaryDataException
Definition at line 193 of file BinaryStream.php.
getItemStackWithoutStackId()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::getItemStackWithoutStackId ()
Exceptions
PacketDecodeException
BinaryDataException
Definition at line 292 of file bedrock-protocol/src/serializer/PacketSerializer.php.
getItemStackWrapper()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::getItemStackWrapper ()
Definition at line 305 of file bedrock-protocol/src/serializer/PacketSerializer.php.
getLDouble()
pocketmine\utils\BinaryStream::getLDouble () inherited
@phpstan-impure
Exceptions
BinaryDataException
Definition at line 269 of file BinaryStream.php.
getLFloat()
pocketmine\utils\BinaryStream::getLFloat () inherited
@phpstan-impure
Exceptions
BinaryDataException
Definition at line 237 of file BinaryStream.php.
Referenced by pocketmine\network\mcpe\protocol\AddActorPacket\decodePayload(), pocketmine\network\mcpe\protocol\AnimatePacket\decodePayload(), pocketmine\network\mcpe\protocol\BossEventPacket\decodePayload(), pocketmine\network\mcpe\protocol\ClientboundDebugRendererPacket\decodePayload(), and pocketmine\network\mcpe\protocol\InteractPacket\decodePayload().
getLInt()
pocketmine\utils\BinaryStream::getLInt () inherited
@phpstan-impure
Exceptions
BinaryDataException
Definition at line 205 of file BinaryStream.php.
Referenced by pocketmine\network\mcpe\protocol\MovePlayerPacket\decodePayload(), pocketmine\network\mcpe\protocol\PlayerListPacket\decodePayload(), and pocketmine\network\mcpe\protocol\SetScorePacket\decodePayload().
getLLong()
pocketmine\utils\BinaryStream::getLLong () inherited
@phpstan-impure
Exceptions
BinaryDataException
Definition at line 293 of file BinaryStream.php.
Referenced by pocketmine\network\mcpe\protocol\ClientboundDebugRendererPacket\decodePayload(), pocketmine\network\mcpe\protocol\ClientCacheBlobStatusPacket\decodePayload(), and pocketmine\network\mcpe\protocol\ClientCacheMissResponsePacket\decodePayload().
getLong()
pocketmine\utils\BinaryStream::getLong () inherited
@phpstan-impure
Exceptions
BinaryDataException
Definition at line 281 of file BinaryStream.php.
getLShort()
pocketmine\utils\BinaryStream::getLShort () inherited
@phpstan-impure
Exceptions
BinaryDataException
Definition at line 149 of file BinaryStream.php.
Referenced by pocketmine\network\mcpe\protocol\BossEventPacket\decodePayload(), and pocketmine\network\mcpe\protocol\AvailableCommandsPacket\getCommandData().
getLTriad()
pocketmine\utils\BinaryStream::getLTriad () inherited
@phpstan-impure
Exceptions
BinaryDataException
Definition at line 181 of file BinaryStream.php.
Referenced by raklib\protocol\AcknowledgePacket\decodePayload().
getNbtCompoundRoot()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::getNbtCompoundRoot ()
Definition at line 721 of file bedrock-protocol/src/serializer/PacketSerializer.php.
getNbtRoot()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::getNbtRoot ()
Definition at line 710 of file bedrock-protocol/src/serializer/PacketSerializer.php.
getOffset()
pocketmine\utils\BinaryStream::getOffset () inherited
Definition at line 55 of file BinaryStream.php.
getRecipeIngredient()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::getRecipeIngredient ()
Definition at line 332 of file bedrock-protocol/src/serializer/PacketSerializer.php.
getRemaining()
pocketmine\utils\BinaryStream::getRemaining () inherited
@phpstan-impure
Exceptions
BinaryDataException
Definition at line 87 of file BinaryStream.php.
getRotationByte()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::getRotationByte ()
Exceptions
BinaryDataException
Definition at line 534 of file bedrock-protocol/src/serializer/PacketSerializer.php.
getRoundedFloat()
pocketmine\utils\BinaryStream::getRoundedFloat (int $accuracy) inherited
@phpstan-impure
Exceptions
BinaryDataException
Definition at line 225 of file BinaryStream.php.
getRoundedLFloat()
pocketmine\utils\BinaryStream::getRoundedLFloat (int $accuracy) inherited
@phpstan-impure
Exceptions
BinaryDataException
Definition at line 245 of file BinaryStream.php.
getShort()
pocketmine\utils\BinaryStream::getShort () inherited
@phpstan-impure
Exceptions
BinaryDataException
Definition at line 129 of file BinaryStream.php.
getSignedBlockPosition()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::getSignedBlockPosition ()
Reads a block position with a signed Y coordinate.
Exceptions
BinaryDataException
Definition at line 457 of file bedrock-protocol/src/serializer/PacketSerializer.php.
getSignedLShort()
pocketmine\utils\BinaryStream::getSignedLShort () inherited
@phpstan-impure
Exceptions
BinaryDataException
Definition at line 157 of file BinaryStream.php.
getSignedShort()
pocketmine\utils\BinaryStream::getSignedShort () inherited
@phpstan-impure
Exceptions
BinaryDataException
Definition at line 137 of file BinaryStream.php.
getSkin()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::getSkin ()
Definition at line 108 of file bedrock-protocol/src/serializer/PacketSerializer.php.
getString()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::getString ()
Exceptions
BinaryDataException
Definition at line 83 of file bedrock-protocol/src/serializer/PacketSerializer.php.
Referenced by pocketmine\network\mcpe\protocol\AddActorPacket\decodePayload(), pocketmine\network\mcpe\protocol\AvailableCommandsPacket\decodePayload(), pocketmine\network\mcpe\protocol\BookEditPacket\decodePayload(), pocketmine\network\mcpe\protocol\BossEventPacket\decodePayload(), pocketmine\network\mcpe\protocol\ClientboundDebugRendererPacket\decodePayload(), pocketmine\network\mcpe\protocol\ClientCacheMissResponsePacket\decodePayload(), pocketmine\network\mcpe\protocol\DeathInfoPacket\decodePayload(), pocketmine\network\mcpe\protocol\DimensionDataPacket\decodePayload(), pocketmine\network\mcpe\protocol\ItemComponentPacket\decodePayload(), pocketmine\network\mcpe\protocol\PlayerFogPacket\decodePayload(), pocketmine\network\mcpe\protocol\PlayerListPacket\decodePayload(), pocketmine\network\mcpe\protocol\PurchaseReceiptPacket\decodePayload(), pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket\decodePayload(), pocketmine\network\mcpe\protocol\SetScorePacket\decodePayload(), pocketmine\network\mcpe\protocol\TextPacket\decodePayload(), pocketmine\network\mcpe\protocol\UnlockedRecipesPacket\decodePayload(), pocketmine\network\mcpe\protocol\UpdateSoftEnumPacket\decodePayload(), pocketmine\network\mcpe\protocol\CommandOutputPacket\getCommandMessage(), and pocketmine\network\mcpe\protocol\AvailableCommandsPacket\getSoftEnum().
getStructureEditorData()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::getStructureEditorData ()
Definition at line 682 of file bedrock-protocol/src/serializer/PacketSerializer.php.
getStructureSettings()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::getStructureSettings ()
Definition at line 638 of file bedrock-protocol/src/serializer/PacketSerializer.php.
getTriad()
pocketmine\utils\BinaryStream::getTriad () inherited
@phpstan-impure
Exceptions
BinaryDataException
Definition at line 169 of file BinaryStream.php.
getUnsignedVarInt()
pocketmine\utils\BinaryStream::getUnsignedVarInt () inherited
Reads a 32-bit variable-length unsigned integer from the buffer and returns it.
@phpstan-impure
Exceptions
BinaryDataException
Definition at line 307 of file BinaryStream.php.
Referenced by pocketmine\network\mcpe\protocol\BossEventPacket\decodePayload(), pocketmine\network\mcpe\protocol\ClientboundMapItemDataPacket\decodePayload(), pocketmine\network\mcpe\protocol\CommandBlockUpdatePacket\decodePayload(), pocketmine\network\mcpe\protocol\InventoryTransactionPacket\decodePayload(), pocketmine\network\mcpe\protocol\TextPacket\decodePayload(), pocketmine\network\mcpe\protocol\serializer\PacketBatch\decodeRaw(), and pocketmine\network\mcpe\protocol\types\inventory\NetworkInventoryAction\read().
getUnsignedVarLong()
pocketmine\utils\BinaryStream::getUnsignedVarLong () inherited
Reads a 64-bit variable-length integer from the buffer and returns it.
@phpstan-impure
Exceptions
BinaryDataException
Definition at line 341 of file BinaryStream.php.
getUUID()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::getUUID ()
Exceptions
BinaryDataException
Definition at line 95 of file bedrock-protocol/src/serializer/PacketSerializer.php.
Referenced by pocketmine\network\mcpe\protocol\EmoteListPacket\decodePayload(), and pocketmine\network\mcpe\protocol\PlayerListPacket\decodePayload().
getVarInt()
pocketmine\utils\BinaryStream::getVarInt () inherited
Reads a 32-bit zigzag-encoded variable-length integer from the buffer and returns it.
@phpstan-impure
Exceptions
BinaryDataException
Definition at line 324 of file BinaryStream.php.
Referenced by pocketmine\network\mcpe\protocol\CraftingDataPacket\decodePayload(), and pocketmine\network\mcpe\protocol\types\inventory\NetworkInventoryAction\read().
getVarLong()
pocketmine\utils\BinaryStream::getVarLong () inherited
Reads a 64-bit zigzag-encoded variable-length integer from the buffer and returns it.
@phpstan-impure
Exceptions
BinaryDataException
Definition at line 358 of file BinaryStream.php.
Referenced by pocketmine\network\mcpe\protocol\SetScoreboardIdentityPacket\decodePayload(), and pocketmine\network\mcpe\protocol\SetScorePacket\decodePayload().
getVector2()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::getVector2 ()
Reads a floating-point Vector2 object with coordinates rounded to 4 decimal places.
Exceptions
BinaryDataException
Definition at line 490 of file bedrock-protocol/src/serializer/PacketSerializer.php.
getVector3()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::getVector3 ()
Reads a floating-point Vector3 object with coordinates rounded to 4 decimal places.
Exceptions
BinaryDataException
Definition at line 478 of file bedrock-protocol/src/serializer/PacketSerializer.php.
Referenced by pocketmine\network\mcpe\protocol\ClientboundDebugRendererPacket\decodePayload(), and pocketmine\network\mcpe\protocol\PlayerAuthInputPacket\decodePayload().
put()
pocketmine\utils\BinaryStream::put (string $str) inherited
Definition at line 97 of file BinaryStream.php.
putActorRuntimeId()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::putActorRuntimeId (int $eid)
Definition at line 427 of file bedrock-protocol/src/serializer/PacketSerializer.php.
putActorUniqueId()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::putActorUniqueId (int $eid)
Definition at line 416 of file bedrock-protocol/src/serializer/PacketSerializer.php.
putBlockPosition()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::putBlockPosition (BlockPosition $blockPosition)
Writes a block position with unsigned Y coordinate.
Definition at line 446 of file bedrock-protocol/src/serializer/PacketSerializer.php.
Referenced by pocketmine\network\mcpe\protocol\CommandBlockUpdatePacket\encodePayload().
putBool()
pocketmine\utils\BinaryStream::putBool (bool $v) inherited
Definition at line 109 of file BinaryStream.php.
putByte()
pocketmine\utils\BinaryStream::putByte (int $v) inherited
Definition at line 121 of file BinaryStream.php.
putCommandOriginData()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::putCommandOriginData (CommandOriginData $data)
Definition at line 628 of file bedrock-protocol/src/serializer/PacketSerializer.php.
putDouble()
pocketmine\utils\BinaryStream::putDouble (float $v) inherited
Definition at line 261 of file BinaryStream.php.
putEntityLink()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::putEntityLink (EntityLink $link)
Definition at line 602 of file bedrock-protocol/src/serializer/PacketSerializer.php.
putEntityMetadata()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::putEntityMetadata (array $metadata)
Writes entity metadata to the packet buffer.
Parameters
MetadataProperty[] $metadata
@phpstan-param array<int, MetadataProperty> $metadata
Definition at line 400 of file bedrock-protocol/src/serializer/PacketSerializer.php.
putFloat()
pocketmine\utils\BinaryStream::putFloat (float $v) inherited
Definition at line 229 of file BinaryStream.php.
putGameRules()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::putGameRules (array $rules)
Writes a gamerule array
Parameters
GameRule[] $rules @phpstan-param array<string, GameRule> $rules
Definition at line 579 of file bedrock-protocol/src/serializer/PacketSerializer.php.
putInt()
pocketmine\utils\BinaryStream::putInt (int $v) inherited
Definition at line 197 of file BinaryStream.php.
putItemStackWithoutStackId()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::putItemStackWithoutStackId (ItemStack $itemStack)
Definition at line 299 of file bedrock-protocol/src/serializer/PacketSerializer.php.
putItemStackWrapper()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::putItemStackWrapper (ItemStackWrapper $itemStackWrapper)
Definition at line 319 of file bedrock-protocol/src/serializer/PacketSerializer.php.
putLDouble()
pocketmine\utils\BinaryStream::putLDouble (float $v) inherited
Definition at line 273 of file BinaryStream.php.
putLFloat()
pocketmine\utils\BinaryStream::putLFloat (float $v) inherited
Definition at line 249 of file BinaryStream.php.
putLInt()
pocketmine\utils\BinaryStream::putLInt (int $v) inherited
Definition at line 209 of file BinaryStream.php.
putLLong()
pocketmine\utils\BinaryStream::putLLong (int $v) inherited
Definition at line 297 of file BinaryStream.php.
putLong()
pocketmine\utils\BinaryStream::putLong (int $v) inherited
Definition at line 285 of file BinaryStream.php.
putLShort()
pocketmine\utils\BinaryStream::putLShort (int $v) inherited
Definition at line 161 of file BinaryStream.php.
putLTriad()
pocketmine\utils\BinaryStream::putLTriad (int $v) inherited
Definition at line 185 of file BinaryStream.php.
putRecipeIngredient()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::putRecipeIngredient (RecipeIngredient $ingredient)
Definition at line 347 of file bedrock-protocol/src/serializer/PacketSerializer.php.
putRotationByte()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::putRotationByte (float $rotation)
Definition at line 538 of file bedrock-protocol/src/serializer/PacketSerializer.php.
putShort()
pocketmine\utils\BinaryStream::putShort (int $v) inherited
Definition at line 141 of file BinaryStream.php.
putSignedBlockPosition()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::putSignedBlockPosition (BlockPosition $blockPosition)
Writes a block position with a signed Y coordinate.
Definition at line 467 of file bedrock-protocol/src/serializer/PacketSerializer.php.
putSkin()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::putSkin (SkinData $skin)
Definition at line 186 of file bedrock-protocol/src/serializer/PacketSerializer.php.
putString()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::putString (string $v)
Definition at line 87 of file bedrock-protocol/src/serializer/PacketSerializer.php.
putStructureEditorData()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::putStructureEditorData (StructureEditorData $structureEditorData)
Definition at line 698 of file bedrock-protocol/src/serializer/PacketSerializer.php.
putStructureSettings()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::putStructureSettings (StructureSettings $structureSettings)
Definition at line 662 of file bedrock-protocol/src/serializer/PacketSerializer.php.
putTriad()
pocketmine\utils\BinaryStream::putTriad (int $v) inherited
Definition at line 173 of file BinaryStream.php.
putUnsignedVarInt()
pocketmine\utils\BinaryStream::putUnsignedVarInt (int $v) inherited
Writes a 32-bit variable-length unsigned integer to the end of the buffer.
Definition at line 314 of file BinaryStream.php.
Referenced by pocketmine\network\mcpe\protocol\serializer\PacketBatch\encodePackets(), pocketmine\network\mcpe\protocol\BossEventPacket\encodePayload(), pocketmine\network\mcpe\protocol\CommandBlockUpdatePacket\encodePayload(), pocketmine\network\mcpe\protocol\InventoryTransactionPacket\encodePayload(), pocketmine\network\mcpe\protocol\LevelChunkPacket\encodePayload(), pocketmine\network\mcpe\protocol\TextPacket\encodePayload(), pocketmine\network\mcpe\protocol\serializer\PacketBatch\encodeRaw(), and pocketmine\network\mcpe\protocol\types\inventory\NetworkInventoryAction\write().
putUnsignedVarLong()
pocketmine\utils\BinaryStream::putUnsignedVarLong (int $v) inherited
Writes a 64-bit variable-length integer to the end of the buffer.
Definition at line 348 of file BinaryStream.php.
putUUID()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::putUUID (UuidInterface $uuid)
Definition at line 102 of file bedrock-protocol/src/serializer/PacketSerializer.php.
putVarInt()
pocketmine\utils\BinaryStream::putVarInt (int $v) inherited
Writes a 32-bit zigzag-encoded variable-length integer to the end of the buffer.
Definition at line 331 of file BinaryStream.php.
Referenced by pocketmine\network\mcpe\protocol\CraftingDataPacket\encodePayload(), and pocketmine\network\mcpe\protocol\types\inventory\NetworkInventoryAction\write().
putVarLong()
pocketmine\utils\BinaryStream::putVarLong (int $v) inherited
Writes a 64-bit zigzag-encoded variable-length integer to the end of the buffer.
Definition at line 365 of file BinaryStream.php.
Referenced by pocketmine\network\mcpe\protocol\SetScoreboardIdentityPacket\encodePayload(), and pocketmine\network\mcpe\protocol\SetScorePacket\encodePayload().
putVector2()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::putVector2 (Vector2 $vector2)
Writes a floating-point Vector2 object
Definition at line 526 of file bedrock-protocol/src/serializer/PacketSerializer.php.
putVector3()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::putVector3 (Vector3 $vector)
Writes a floating-point Vector3 object
Definition at line 517 of file bedrock-protocol/src/serializer/PacketSerializer.php.
Referenced by pocketmine\network\mcpe\protocol\ClientboundDebugRendererPacket\encodePayload(), and pocketmine\network\mcpe\protocol\PlayerAuthInputPacket\encodePayload().
putVector3Nullable()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::putVector3Nullable (?Vector3 $vector)
Writes a floating-point Vector3 object, or 3x zero if null is given.
Note: ONLY use this where it is reasonable to allow not specifying the vector. For all other purposes, use the non-nullable version.
See also
PacketSerializer::putVector3()
Definition at line 504 of file bedrock-protocol/src/serializer/PacketSerializer.php.
readCreativeItemNetId()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::readCreativeItemNetId ()
Definition at line 737 of file bedrock-protocol/src/serializer/PacketSerializer.php.
readItemStackNetIdVariant()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::readItemStackNetIdVariant ()
This is a union of ItemStackRequestId, LegacyItemStackRequestId, and ServerItemStackId, used in serverbound packets to allow the client to refer to server known items, or items which may have been modified by a previous as-yet unacknowledged request from the client.
Server itemstack ID is positive
InventoryTransaction "legacy" request ID is negative and even
ItemStackRequest request ID is negative and odd
0 refers to an empty itemstack (air)
Definition at line 755 of file bedrock-protocol/src/serializer/PacketSerializer.php.
readItemStackRequestId()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::readItemStackRequestId ()
Definition at line 768 of file bedrock-protocol/src/serializer/PacketSerializer.php.
readLegacyItemStackRequestId()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::readLegacyItemStackRequestId ()
Definition at line 776 of file bedrock-protocol/src/serializer/PacketSerializer.php.
readOptional()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::readOptional (\Closure $reader)
@phpstan-template T @phpstan-param \Closure() : T $reader @phpstan-return T|null
Definition at line 797 of file bedrock-protocol/src/serializer/PacketSerializer.php.
Referenced by pocketmine\network\mcpe\protocol\CorrectPlayerMovePredictionPacket\decodePayload().
readRecipeNetId()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::readRecipeNetId ()
Definition at line 729 of file bedrock-protocol/src/serializer/PacketSerializer.php.
readServerItemStackId()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::readServerItemStackId ()
Definition at line 784 of file bedrock-protocol/src/serializer/PacketSerializer.php.
rewind()
pocketmine\utils\BinaryStream::rewind () inherited
Rewinds the stream pointer to the start.
Definition at line 47 of file BinaryStream.php.
setOffset()
pocketmine\utils\BinaryStream::setOffset (int $offset) inherited
Definition at line 51 of file BinaryStream.php.
writeCreativeItemNetId()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::writeCreativeItemNetId (int $id)
Definition at line 741 of file bedrock-protocol/src/serializer/PacketSerializer.php.
writeItemStackNetIdVariant()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::writeItemStackNetIdVariant (int $id)
This is a union of ItemStackRequestId, LegacyItemStackRequestId, and ServerItemStackId, used in serverbound packets to allow the client to refer to server known items, or items which may have been modified by a previous as-yet unacknowledged request from the client.
Definition at line 764 of file bedrock-protocol/src/serializer/PacketSerializer.php.
writeItemStackRequestId()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::writeItemStackRequestId (int $id)
Definition at line 772 of file bedrock-protocol/src/serializer/PacketSerializer.php.
writeLegacyItemStackRequestId()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::writeLegacyItemStackRequestId (int $id)
Definition at line 780 of file bedrock-protocol/src/serializer/PacketSerializer.php.
writeOptional()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::writeOptional (mixed $value, \Closure $writer)
@phpstan-template T @phpstan-param T|null $value @phpstan-param \Closure(T) : void $writer
Definition at line 809 of file bedrock-protocol/src/serializer/PacketSerializer.php.
Referenced by pocketmine\network\mcpe\protocol\CorrectPlayerMovePredictionPacket\encodePayload().
writeRecipeNetId()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::writeRecipeNetId (int $id)
Definition at line 733 of file bedrock-protocol/src/serializer/PacketSerializer.php.
writeServerItemStackId()
pocketmine\network\mcpe\protocol\serializer\PacketSerializer::writeServerItemStackId (int $id)
Definition at line 788 of file bedrock-protocol/src/serializer/PacketSerializer.php.
Member Data Documentation
$buffer
pocketmine\utils\BinaryStream::$buffer protected inherited
Definition at line 37 of file BinaryStream.php.
$offset
pocketmine\utils\BinaryStream::$offset protected inherited
Definition at line 35 of file BinaryStream.php.
The documentation for this class was generated from the following file:
bedrock-protocol/src/serializer/PacketSerializer.php