PocketMine-MP: pocketmine\world\generator\noise\Noise Class Reference
pocketmine\world\generator\noise\Noise Class Reference
Public Member Functions
__construct (protected int $octaves, protected float $persistence, protected float $expansion)
getFastNoise1D (int $xSize, int $samplingRate, int $x, int $y, int $z)
getFastNoise2D (int $xSize, int $zSize, int $samplingRate, int $x, int $y, int $z)
getFastNoise3D (int $xSize, int $ySize, int $zSize, int $xSamplingRate, int $ySamplingRate, int $zSamplingRate, int $x, int $y, int $z)
getNoise2D ($x, $z)
getNoise3D ($x, $y, $z)
noise2D ($x, $z, $normalized=false)
noise3D ($x, $y, $z, $normalized=false)
Static Public Member Functions
static bilinearLerp ($x, $y, $q00, $q01, $q10, $q11, $x1, $x2, $y1, $y2)
static linearLerp ($x, $x1, $x2, $q0, $q1)
static trilinearLerp ($x, $y, $z, $q000, $q001, $q010, $q011, $q100, $q101, $q110, $q111, $x1, $x2, $y1, $y2, $z1, $z2)
Detailed Description
Definition at line 32 of file Noise.php.
Constructor & Destructor Documentation
__construct()
pocketmine\world\generator\noise\Noise::__construct (protected int $octaves, protected float $persistence, protected float $expansion)
Definition at line 114 of file Noise.php.
Member Function Documentation
bilinearLerp()
static pocketmine\world\generator\noise\Noise::bilinearLerp ($x, $y, $q00, $q01, $q10, $q11, $x1, $x2, $y1, $y2) static
Parameters
float $x
float $y
float $q00
float $q01
float $q10
float $q11
float $x1
float $x2
float $y1
float $y2
Returns
float
Definition at line 61 of file Noise.php.
getFastNoise1D()
pocketmine\world\generator\noise\Noise::getFastNoise1D (int $xSize, int $samplingRate, int $x, int $y, int $z)
Returns
\SplFixedArray|float[] @phpstan-return \SplFixedArray<float>
Definition at line 203 of file Noise.php.
getFastNoise2D()
pocketmine\world\generator\noise\Noise::getFastNoise2D (int $xSize, int $zSize, int $samplingRate, int $x, int $y, int $z)
Returns
\SplFixedArray|float[][] @phpstan-return \SplFixedArray<\SplFixedArray<float>>
Definition at line 238 of file Noise.php.
getFastNoise3D()
pocketmine\world\generator\noise\Noise::getFastNoise3D (int $xSize, int $ySize, int $zSize, int $xSamplingRate, int $ySamplingRate, int $zSamplingRate, int $x, int $y, int $z)
Returns
float[][][]
Definition at line 285 of file Noise.php.
getNoise2D()
pocketmine\world\generator\noise\Noise::getNoise2D ($x, $z) abstract
Parameters
float $x
float $z
Returns
float
Reimplemented in pocketmine\world\generator\noise\Simplex.
Referenced by pocketmine\world\generator\noise\Noise\noise2D().
getNoise3D()
pocketmine\world\generator\noise\Noise::getNoise3D ($x, $y, $z) abstract
Parameters
float $x
float $y
float $z
Returns
float
Reimplemented in pocketmine\world\generator\noise\Simplex.
Referenced by pocketmine\world\generator\noise\Noise\noise3D().
linearLerp()
static pocketmine\world\generator\noise\Noise::linearLerp ($x, $x1, $x2, $q0, $q1) static
Parameters
float $x
float $x1
float $x2
float $q0
float $q1
Returns
float
Definition at line 43 of file Noise.php.
noise2D()
pocketmine\world\generator\noise\Noise::noise2D ($x, $z, $normalized = false)
Parameters
float $x
float $z
bool $normalized
Returns
float
Definition at line 144 of file Noise.php.
References pocketmine\world\generator\noise\Noise\getNoise2D().
noise3D()
pocketmine\world\generator\noise\Noise::noise3D ($x, $y, $z, $normalized = false)
Parameters
float $x
float $y
float $z
bool $normalized
Returns
float
Definition at line 175 of file Noise.php.
References pocketmine\world\generator\noise\Noise\getNoise3D().
trilinearLerp()
static pocketmine\world\generator\noise\Noise::trilinearLerp ($x, $y, $z, $q000, $q001, $q010, $q011, $q100, $q101, $q110, $q111, $x1, $x2, $y1, $y2, $z1, $z2) static
Parameters
float $x
float $y
float $z
float $q000
float $q001
float $q010
float $q011
float $q100
float $q101
float $q110
float $q111
float $x1
float $x2
float $y1
float $y2
float $z1
float $z2
Returns
float
Definition at line 93 of file Noise.php.
The documentation for this class was generated from the following file:
Noise.php