PocketMine-MP: pocketmine\data\bedrock\block\convert\BlockStateReader Class Reference
pocketmine\data\bedrock\block\convert\BlockStateReader Class Reference
Public Member Functions
__construct (private BlockStateData $data)
badValueException (string $name, string $stringifiedValue, ?string $reason=null)
checkUnreadProperties ()
ignored (string $name)
missingOrWrongTypeException (string $name, ?Tag $tag)
read5MinusHorizontalFacing ()
readBellAttachmentType ()
readBlockFace ()
readBool (string $name)
readBoundedInt (string $name, int $min, int $max)
readCardinalHorizontalFacing ()
readCoralFacing ()
readEndRodFacingDirection ()
readFacingDirection ()
readFacingFlags ()
readFacingWithoutDown ()
readFacingWithoutUp ()
readHorizontalFacing ()
readInt (string $name)
readLegacyHorizontalFacing ()
readPillarAxis ()
readSlabPosition ()
readString (string $name)
readTorchFacing ()
readWallConnectionType (string $name)
readWeirdoHorizontalFacing ()
todo (string $name)
Detailed Description
Definition at line 45 of file BlockStateReader.php.
Constructor & Destructor Documentation
__construct()
pocketmine\data\bedrock\block\convert\BlockStateReader::__construct (private BlockStateData $data)
Definition at line 53 of file BlockStateReader.php.
Member Function Documentation
badValueException()
pocketmine\data\bedrock\block\convert\BlockStateReader::badValueException (string $name, string $stringifiedValue, ?string $reason = null)
Definition at line 63 of file BlockStateReader.php.
checkUnreadProperties()
pocketmine\data\bedrock\block\convert\BlockStateReader::checkUnreadProperties ()
Exceptions
BlockStateDeserializeException
Definition at line 356 of file BlockStateReader.php.
ignored()
pocketmine\data\bedrock\block\convert\BlockStateReader::ignored (string $name)
Explicitly mark a property as unused, so it doesn't get flagged as an error when debug mode is enabled
Definition at line 338 of file BlockStateReader.php.
missingOrWrongTypeException()
pocketmine\data\bedrock\block\convert\BlockStateReader::missingOrWrongTypeException (string $name, ?Tag $tag)
Definition at line 59 of file BlockStateReader.php.
read5MinusHorizontalFacing()
pocketmine\data\bedrock\block\convert\BlockStateReader::read5MinusHorizontalFacing ()
This is for trapdoors, because Mojang botched the conversion in 1.13
Exceptions
BlockStateDeserializeException
Definition at line 218 of file BlockStateReader.php.
readBellAttachmentType()
pocketmine\data\bedrock\block\convert\BlockStateReader::readBellAttachmentType ()
Exceptions
BlockStateDeserializeException
Definition at line 312 of file BlockStateReader.php.
readBlockFace()
pocketmine\data\bedrock\block\convert\BlockStateReader::readBlockFace ()
Exceptions
BlockStateDeserializeException
Definition at line 141 of file BlockStateReader.php.
readBool()
pocketmine\data\bedrock\block\convert\BlockStateReader::readBool (string $name)
Exceptions
BlockStateDeserializeException
Definition at line 71 of file BlockStateReader.php.
References pocketmine\nbt\tag\Tag\getValue().
readBoundedInt()
pocketmine\data\bedrock\block\convert\BlockStateReader::readBoundedInt (string $name, int $min, int $max)
Exceptions
BlockStateDeserializeException
Definition at line 95 of file BlockStateReader.php.
readCardinalHorizontalFacing()
pocketmine\data\bedrock\block\convert\BlockStateReader::readCardinalHorizontalFacing ()
Used by pumpkins as of 1.20.0.23 beta
Exceptions
BlockStateDeserializeException
Definition at line 231 of file BlockStateReader.php.
readCoralFacing()
pocketmine\data\bedrock\block\convert\BlockStateReader::readCoralFacing ()
Exceptions
BlockStateDeserializeException
Definition at line 242 of file BlockStateReader.php.
readEndRodFacingDirection()
pocketmine\data\bedrock\block\convert\BlockStateReader::readEndRodFacingDirection ()
Exceptions
BlockStateDeserializeException
Definition at line 177 of file BlockStateReader.php.
readFacingDirection()
pocketmine\data\bedrock\block\convert\BlockStateReader::readFacingDirection ()
Exceptions
BlockStateDeserializeException
Definition at line 129 of file BlockStateReader.php.
readFacingFlags()
pocketmine\data\bedrock\block\convert\BlockStateReader::readFacingFlags ()
Returns
int[] @phpstan-return array<int, int>
Definition at line 157 of file BlockStateReader.php.
readFacingWithoutDown()
pocketmine\data\bedrock\block\convert\BlockStateReader::readFacingWithoutDown ()
Exceptions
BlockStateDeserializeException
Definition at line 252 of file BlockStateReader.php.
readFacingWithoutUp()
pocketmine\data\bedrock\block\convert\BlockStateReader::readFacingWithoutUp ()
Definition at line 260 of file BlockStateReader.php.
readHorizontalFacing()
pocketmine\data\bedrock\block\convert\BlockStateReader::readHorizontalFacing ()
Exceptions
BlockStateDeserializeException
Definition at line 183 of file BlockStateReader.php.
readInt()
pocketmine\data\bedrock\block\convert\BlockStateReader::readInt (string $name)
Exceptions
BlockStateDeserializeException
Definition at line 85 of file BlockStateReader.php.
References pocketmine\nbt\tag\Tag\getValue().
readLegacyHorizontalFacing()
pocketmine\data\bedrock\block\convert\BlockStateReader::readLegacyHorizontalFacing ()
Exceptions
BlockStateDeserializeException
Definition at line 205 of file BlockStateReader.php.
readPillarAxis()
pocketmine\data\bedrock\block\convert\BlockStateReader::readPillarAxis ()
@phpstan-return Axis::*
Exceptions
BlockStateDeserializeException
Definition at line 272 of file BlockStateReader.php.
readSlabPosition()
pocketmine\data\bedrock\block\convert\BlockStateReader::readSlabPosition ()
Exceptions
BlockStateDeserializeException
Definition at line 286 of file BlockStateReader.php.
readString()
pocketmine\data\bedrock\block\convert\BlockStateReader::readString (string $name)
Exceptions
BlockStateDeserializeException
Definition at line 104 of file BlockStateReader.php.
References pocketmine\nbt\tag\Tag\getValue().
readTorchFacing()
pocketmine\data\bedrock\block\convert\BlockStateReader::readTorchFacing ()
@phpstan-return Facing::UP|Facing::NORTH|Facing::SOUTH|Facing::WEST|Facing::EAST
Exceptions
BlockStateDeserializeException
Definition at line 298 of file BlockStateReader.php.
readWallConnectionType()
pocketmine\data\bedrock\block\convert\BlockStateReader::readWallConnectionType (string $name)
Exceptions
BlockStateDeserializeException
Definition at line 323 of file BlockStateReader.php.
readWeirdoHorizontalFacing()
pocketmine\data\bedrock\block\convert\BlockStateReader::readWeirdoHorizontalFacing ()
Exceptions
BlockStateDeserializeException
Definition at line 195 of file BlockStateReader.php.
todo()
pocketmine\data\bedrock\block\convert\BlockStateReader::todo (string $name)
Used to mark unused properties that haven't been implemented yet
Definition at line 349 of file BlockStateReader.php.
The documentation for this class was generated from the following file:
BlockStateReader.php