PocketMine-MP: pocketmine\entity\projectile\Arrow Class Reference
pocketmine\entity\projectile\Arrow Class Reference
Public Member Functions
__construct (Location $location, ?Entity $shootingEntity, bool $critical, ?CompoundTag $nbt=null)
__toString ()
addMotion (float $x, float $y, float $z)
attack (EntityDamageEvent $source)
broadcastAnimation (Animation $animation, ?array $targets=null)
broadcastSound (Sound $sound, ?array $targets=null)
canBeCollidedWith ()
canBeMovedByCurrents ()
canClimb ()
canClimbWalls ()
canCollideWith (Entity $entity)
canSaveWithChunk ()
close ()
despawnFrom (Player $player, bool $send=true)
despawnFromAll ()
extinguish ()
flagForDespawn ()
getAttributeMap ()
getBaseDamage ()
getBoundingBox ()
getDirectionPlane ()
getDirectionVector ()
getEyeHeight ()
getEyePos ()
getFallDistance ()
getFireTicks ()
getHealth ()
getHorizontalFacing ()
getId ()
getLastDamageCause ()
getLocation ()
getMaxHealth ()
getMotion ()
getNameTag ()
getNetworkProperties ()
getOffsetPosition (Vector3 $vector3)
getOwningEntity ()
getOwningEntityId ()
getPickupMode ()
getPosition ()
getPunchKnockback ()
getResultDamage ()
getScale ()
getScoreTag ()
getSize ()
getTargetEntity ()
getTargetEntityId ()
getViewers ()
getWorld ()
hasGravity ()
hasMovementUpdate ()
heal (EntityRegainHealthEvent $source)
isAlive ()
isClosed ()
isCritical ()
isFireProof ()
isFlaggedForDespawn ()
isImmobile ()
isInsideOfSolid ()
isInvisible ()
isNameTagAlwaysVisible ()
isNameTagVisible ()
isOnFire ()
isOnGround ()
isSilent ()
isUnderwater ()
kill ()
onCollideWithPlayer (Player $player)
onInteract (Player $player, Vector3 $clickPos)
onNearbyBlockChange ()
onRandomUpdate ()
onUpdate (int $currentTick)
resetFallDistance ()
respawnToAll ()
saveNBT ()
scheduleUpdate ()
sendData (?array $targets, ?array $data=null)
setBaseDamage (float $damage)
setCanClimb (bool $value=true)
setCanClimbWalls (bool $value=true)
setCanSaveWithChunk (bool $value)
setCritical (bool $value=true)
setFallDistance (float $fallDistance)
setFireTicks (int $fireTicks)
setForceMovementUpdate (bool $value=true)
setHasGravity (bool $v=true)
setHealth (float $amount)
setImmobile (bool $value=true)
setInvisible (bool $value=true)
setLastDamageCause (EntityDamageEvent $type)
setMaxHealth (int $amount)
setMotion (Vector3 $motion)
setNameTag (string $name)
setNameTagAlwaysVisible (bool $value=true)
setNameTagVisible (bool $value=true)
setOnFire (int $seconds)
setOwningEntity (?Entity $owner)
setPickupMode (int $pickupMode)
setPunchKnockback (float $punchKnockback)
setRotation (float $yaw, float $pitch)
setScale (float $value)
setScoreTag (string $score)
setSilent (bool $value=true)
setTargetEntity (?Entity $target)
spawnTo (Player $player)
spawnToAll ()
teleport (Vector3 $pos, ?float $yaw=null, ?float $pitch=null)
Static Public Member Functions
static getNetworkTypeId ()
static nextRuntimeId ()
Public Attributes
$boundingBox
$canCollide = true
$fallDistance = 0.0
$isCollided = false
$isCollidedHorizontally = false
$isCollidedVertically = false
$keepMovement = false
$lastUpdate
$noDamageTicks = 0
$onGround = false
$size
$ticksLived = 0
const MOTION_THRESHOLD = 0.00001
const PICKUP_ANY = 1
const PICKUP_CREATIVE = 2
const PICKUP_NONE = 0
const TAG_CRIT = "crit"
Protected Member Functions
addAttributes ()
applyDragBeforeGravity ()
broadcastMotion ()
broadcastMovement (bool $teleport=false)
calculateInterceptWithBlock (Block $block, Vector3 $start, Vector3 $end)
checkBlockIntersections ()
checkGroundState (float $wantedX, float $wantedY, float $wantedZ, float $dx, float $dy, float $dz)
checkObstruction (float $x, float $y, float $z)
dealFireDamage ()
destroyCycles ()
doOnFireTick (int $tickDiff=1)
entityBaseTick (int $tickDiff=1)
getAllNetworkData ()
getBlocksAroundWithEntityInsideActions ()
getBlocksIntersected (float $inset)
getDirtyNetworkData ()
getInitialSizeInfo ()
initEntity (CompoundTag $nbt)
move (float $dx, float $dy, float $dz)
onDeath ()
onDeathUpdate (int $tickDiff)
onDispose ()
onHit (ProjectileHitEvent $event)
onHitBlock (Block $blockHit, RayTraceResult $hitResult)
onHitEntity (Entity $entityHit, RayTraceResult $hitResult)
onHitGround ()
recalculateBoundingBox ()
resetLastMovements ()
sendSpawnPacket (Player $player)
setPosition (Vector3 $pos)
setPositionAndRotation (Vector3 $pos, float $yaw, float $pitch)
setSize (EntitySizeInfo $size)
syncNetworkData (EntityMetadataCollection $properties)
tryChangeMovement ()
updateFallState (float $distanceThisTick, bool $onGround)
updateMovement (bool $teleport=false)
Protected Attributes
$alwaysShowNameTag = false
$attributeMap
$blockHit
$blocksAround
$canClimb = false
$canClimbWalls = false
$closed = false
$collideTicks = 0
$critical = false
$damage = 2.0
$drag = 0.01
$fireTicks = 0
$forceMovementUpdate = false
$gravity = 0.05
$gravityEnabled = true
$hasSpawned = []
$id
$immobile = false
$invisible = false
$isStatic = false
$justCreated = true
$lastDamageCause = null
$lastLocation
$lastMotion
$location
$motion
$nameTag = ""
$nameTagVisible = true
bool $networkPropertiesDirty = false
$ownerId = null
$pickupMode = self::PICKUP_ANY
$punchKnockback = 0.0
$scale = 1.0
$scoreTag = ""
$server
$silent = false
$stepHeight = 0.0
$targetId = null
$timings
$ySize = 0.0
const STEP_CLIP_MULTIPLIER = 0.4
Detailed Description
Definition at line 44 of file entity/projectile/Arrow.php.
Constructor & Destructor Documentation
__construct()
pocketmine\entity\projectile\Arrow::__construct (Location $location, ?Entity $shootingEntity, bool $critical, ?CompoundTag $nbt = null)
Definition at line 73 of file entity/projectile/Arrow.php.
Member Function Documentation
__toString()
pocketmine\entity\Entity::__toString () inherited
Definition at line 1673 of file Entity.php.
addAttributes()
pocketmine\entity\Entity::addAttributes () protected inherited
Definition at line 525 of file Entity.php.
addMotion()
pocketmine\entity\Entity::addMotion (float $x, float $y, float $z) inherited
Adds the given values to the entity's motion vector.
Definition at line 1393 of file Entity.php.
Referenced by pocketmine\entity\effect\LevitationEffect\applyEffect().
applyDragBeforeGravity()
pocketmine\entity\projectile\Projectile::applyDragBeforeGravity () protected inherited
Reimplemented from pocketmine\entity\Entity.
Definition at line 153 of file Projectile.php.
attack()
pocketmine\entity\projectile\Projectile::attack (EntityDamageEvent $source) inherited
Reimplemented from pocketmine\entity\Entity.
Definition at line 67 of file Projectile.php.
broadcastAnimation()
pocketmine\entity\Entity::broadcastAnimation (Animation $animation, ?array $targets = null) inherited
Parameters
Player[] | null $targets
Reimplemented in pocketmine\player\Player.
Definition at line 1655 of file Entity.php.
References pocketmine\server().
broadcastMotion()
pocketmine\entity\Entity::broadcastMotion () protected inherited
Definition at line 796 of file Entity.php.
broadcastMovement()
pocketmine\entity\Entity::broadcastMovement (bool $teleport = false) protected inherited
Definition at line 770 of file Entity.php.
broadcastSound()
pocketmine\entity\Entity::broadcastSound (Sound $sound, ?array $targets = null) inherited
Broadcasts a sound caused by the entity. If the entity is considered "silent", the sound will be dropped.
Parameters
Player[] | null $targets
Reimplemented in pocketmine\player\Player.
Definition at line 1663 of file Entity.php.
References pocketmine\world\sound\Sound\encode(), and pocketmine\server().
calculateInterceptWithBlock()
pocketmine\entity\projectile\Projectile::calculateInterceptWithBlock (Block $block, Vector3 $start, Vector3 $end) protected inherited
Called by move() when raytracing blocks to discover whether the block should be considered as a point of impact. This can be overridden by other projectiles to allow altering the blocks which are collided with (for example some projectiles collide with any non-air block).
Returns
RayTraceResult|null the result of the ray trace if successful, or null if no interception is found.
Definition at line 275 of file Projectile.php.
canBeCollidedWith()
pocketmine\entity\projectile\Projectile::canBeCollidedWith () inherited
Reimplemented from pocketmine\entity\Entity.
Definition at line 108 of file Projectile.php.
canBeMovedByCurrents()
pocketmine\entity\Entity::canBeMovedByCurrents () inherited
Returns whether this entity can be moved by currents in liquids.
Reimplemented in pocketmine\entity\object\FallingBlock, and pocketmine\player\Player.
Definition at line 1277 of file Entity.php.
canClimb()
pocketmine\entity\Entity::canClimb () inherited
Returns whether the entity is able to climb blocks such as ladders or vines.
Definition at line 370 of file Entity.php.
canClimbWalls()
pocketmine\entity\Entity::canClimbWalls () inherited
Returns whether this entity is climbing a block. By default this is only true if the entity is climbing a ladder or vine or similar block.
Definition at line 385 of file Entity.php.
canCollideWith()
pocketmine\entity\projectile\Projectile::canCollideWith (Entity $entity) inherited
Reimplemented from pocketmine\entity\Entity.
Definition at line 104 of file Projectile.php.
canSaveWithChunk()
pocketmine\entity\Entity::canSaveWithChunk () inherited
Returns whether this entity will be saved when its chunk is unloaded.
Reimplemented in pocketmine\player\Player.
Definition at line 461 of file Entity.php.
checkBlockIntersections()
pocketmine\entity\Entity::checkBlockIntersections () protected inherited
Definition at line 1281 of file Entity.php.
checkGroundState()
pocketmine\entity\Entity::checkGroundState (float $wantedX, float $wantedY, float $wantedZ, float $dx, float $dy, float $dz) protected inherited
Definition at line 1225 of file Entity.php.
checkObstruction()
pocketmine\entity\Entity::checkObstruction (float $x, float $y, float $z) protected inherited
Definition at line 836 of file Entity.php.
close()
pocketmine\entity\Entity::close () final inherited
Closes the entity and frees attached references.
WARNING: Entities are unusable after this has been executed!
Definition at line 1553 of file Entity.php.
dealFireDamage()
pocketmine\entity\Entity::dealFireDamage () protected inherited
Called to deal damage to entities when they are on fire.
Definition at line 727 of file Entity.php.
despawnFrom()
pocketmine\entity\Entity::despawnFrom (Player $player, bool $send = true) inherited
Deprecated:
WARNING: This function DOES NOT permanently hide the entity from the player. As soon as the entity or player moves, the player will once again be able to see the entity.
Definition at line 1509 of file Entity.php.
despawnFromAll()
pocketmine\entity\Entity::despawnFromAll () inherited
Deprecated:
WARNING: This function DOES NOT permanently hide the entity from viewers. As soon as the entity or player moves, viewers will once again be able to see the entity.
Definition at line 1523 of file Entity.php.
destroyCycles()
pocketmine\entity\Entity::destroyCycles () protected inherited
Called when the entity is disposed, after all events have been fired. This should be used to perform destructive circular object references and things which could impact memory usage.
It is expected that the object is unusable after this is called.
Reimplemented in pocketmine\entity\Human, pocketmine\entity\Living, and pocketmine\player\Player.
Definition at line 1586 of file Entity.php.
doOnFireTick()
pocketmine\entity\Entity::doOnFireTick (int $tickDiff = 1) protected inherited
Definition at line 704 of file Entity.php.
entityBaseTick()
pocketmine\entity\projectile\Arrow::entityBaseTick (int $tickDiff = 1) protected
Reimplemented from pocketmine\entity\Entity.
Definition at line 122 of file entity/projectile/Arrow.php.
extinguish()
pocketmine\entity\Entity::extinguish () inherited
Definition at line 695 of file Entity.php.
flagForDespawn()
pocketmine\entity\Entity::flagForDespawn () inherited
Flags the entity to be removed from the world on the next tick.
Definition at line 1532 of file Entity.php.
getAllNetworkData()
pocketmine\entity\Entity::getAllNetworkData () final protected inherited
Returns
MetadataProperty[] @phpstan-return array<int, MetadataProperty>
Definition at line 1621 of file Entity.php.
getAttributeMap()
pocketmine\entity\Entity::getAttributeMap () inherited
Definition at line 618 of file Entity.php.
getBaseDamage()
pocketmine\entity\projectile\Projectile::getBaseDamage () inherited
Returns the base damage applied on collision. This is multiplied by the projectile's speed to give a result damage.
Definition at line 116 of file Projectile.php.
getBlocksAroundWithEntityInsideActions()
pocketmine\entity\Entity::getBlocksAroundWithEntityInsideActions () protected inherited
Returns
Block[]
Definition at line 1259 of file Entity.php.
getBlocksIntersected()
pocketmine\entity\Entity::getBlocksIntersected (float $inset) protected inherited
Yields all the blocks whose full-cube areas are intersected by the entity's AABB.
@phpstan-return \Generator<int, Block, void, void>
Definition at line 1237 of file Entity.php.
getBoundingBox()
pocketmine\entity\Entity::getBoundingBox () inherited
Definition at line 313 of file Entity.php.
getDirectionPlane()
pocketmine\entity\Entity::getDirectionPlane () inherited
Definition at line 938 of file Entity.php.
getDirectionVector()
pocketmine\entity\Entity::getDirectionVector () inherited
Definition at line 929 of file Entity.php.
getDirtyNetworkData()
pocketmine\entity\Entity::getDirtyNetworkData () final protected inherited
Returns
MetadataProperty[] @phpstan-return array<int, MetadataProperty>
Definition at line 1609 of file Entity.php.
getEyeHeight()
pocketmine\entity\Entity::getEyeHeight () inherited
Definition at line 1075 of file Entity.php.
getEyePos()
pocketmine\entity\Entity::getEyePos () inherited
Definition at line 1079 of file Entity.php.
getFallDistance()
pocketmine\entity\Entity::getFallDistance () inherited
Definition at line 1040 of file Entity.php.
getFireTicks()
pocketmine\entity\Entity::getFireTicks () inherited
Definition at line 680 of file Entity.php.
getHealth()
pocketmine\entity\Entity::getHealth () inherited
Definition at line 575 of file Entity.php.
getHorizontalFacing()
pocketmine\entity\Entity::getHorizontalFacing () inherited
Definition at line 910 of file Entity.php.
getId()
pocketmine\entity\Entity::getId () inherited
Definition at line 1443 of file Entity.php.
getInitialSizeInfo()
pocketmine\entity\projectile\Arrow::getInitialSizeInfo () protected
Reimplemented from pocketmine\entity\Entity.
Definition at line 78 of file entity/projectile/Arrow.php.
getLastDamageCause()
pocketmine\entity\Entity::getLastDamageCause () inherited
Definition at line 614 of file Entity.php.
getLocation()
pocketmine\entity\Entity::getLocation () inherited
Definition at line 1304 of file Entity.php.
getMaxHealth()
pocketmine\entity\Entity::getMaxHealth () inherited
Definition at line 602 of file Entity.php.
getMotion()
pocketmine\entity\Entity::getMotion () inherited
Definition at line 1367 of file Entity.php.
getNameTag()
pocketmine\entity\Entity::getNameTag () inherited
Definition at line 266 of file Entity.php.
getNetworkProperties()
pocketmine\entity\Entity::getNetworkProperties () inherited
Definition at line 622 of file Entity.php.
getNetworkTypeId()
static pocketmine\entity\projectile\Arrow::getNetworkTypeId () static
Reimplemented from pocketmine\entity\Entity.
Definition at line 46 of file entity/projectile/Arrow.php.
getOffsetPosition()
pocketmine\entity\Entity::getOffsetPosition (Vector3 $vector3) inherited
Definition at line 766 of file Entity.php.
getOwningEntity()
pocketmine\entity\Entity::getOwningEntity () inherited
Returns the owning entity, or null if the entity was not found.
Definition at line 407 of file Entity.php.
References pocketmine\server().
getOwningEntityId()
pocketmine\entity\Entity::getOwningEntityId () inherited
Returns the entity ID of the owning entity, or null if the entity doesn't have an owner.
Definition at line 400 of file Entity.php.
getPickupMode()
pocketmine\entity\projectile\Arrow::getPickupMode ()
Definition at line 163 of file entity/projectile/Arrow.php.
getPosition()
pocketmine\entity\Entity::getPosition () inherited
Definition at line 1300 of file Entity.php.
getPunchKnockback()
pocketmine\entity\projectile\Arrow::getPunchKnockback ()
Definition at line 114 of file entity/projectile/Arrow.php.
getResultDamage()
pocketmine\entity\projectile\Arrow::getResultDamage ()
Returns the amount of damage this projectile will deal to the entity it hits.
Reimplemented from pocketmine\entity\projectile\Projectile.
Definition at line 105 of file entity/projectile/Arrow.php.
getScale()
pocketmine\entity\Entity::getScale () inherited
Definition at line 301 of file Entity.php.
getScoreTag()
pocketmine\entity\Entity::getScoreTag () inherited
Definition at line 292 of file Entity.php.
getSize()
pocketmine\entity\Entity::getSize () inherited
Definition at line 330 of file Entity.php.
getTargetEntity()
pocketmine\entity\Entity::getTargetEntity () inherited
Returns the entity's target entity, or null if not found. This is used for things like hostile mobs attacking entities, and for fishing rods reeling hit entities in.
Definition at line 438 of file Entity.php.
References pocketmine\server().
getTargetEntityId()
pocketmine\entity\Entity::getTargetEntityId () inherited
Returns the entity ID of the entity's target, or null if it doesn't have a target.
Definition at line 430 of file Entity.php.
getViewers()
pocketmine\entity\Entity::getViewers () inherited
Returns
Player[]
Definition at line 1450 of file Entity.php.
getWorld()
pocketmine\entity\Entity::getWorld () inherited
Definition at line 1308 of file Entity.php.
hasGravity()
pocketmine\entity\Entity::hasGravity () inherited
Definition at line 800 of file Entity.php.
hasMovementUpdate()
pocketmine\entity\projectile\Projectile::hasMovementUpdate () inherited
Returns whether the entity needs a movement update on the next tick.
Reimplemented from pocketmine\entity\Entity.
Definition at line 165 of file Projectile.php.
heal()
pocketmine\entity\Entity::heal (EntityRegainHealthEvent $source) inherited
Definition at line 540 of file Entity.php.
initEntity()
pocketmine\entity\projectile\Arrow::initEntity (CompoundTag $nbt) protected
Reimplemented from pocketmine\entity\projectile\Projectile.
Definition at line 80 of file entity/projectile/Arrow.php.
isAlive()
pocketmine\entity\Entity::isAlive () inherited
Definition at line 571 of file Entity.php.
isClosed()
pocketmine\entity\Entity::isClosed () inherited
Returns whether the entity has been "closed".
Definition at line 1544 of file Entity.php.
isCritical()
pocketmine\entity\projectile\Arrow::isCritical ()
Definition at line 96 of file entity/projectile/Arrow.php.
isFireProof()
pocketmine\entity\Entity::isFireProof () inherited
Definition at line 700 of file Entity.php.
isFlaggedForDespawn()
pocketmine\entity\Entity::isFlaggedForDespawn () inherited
Definition at line 1537 of file Entity.php.
isImmobile()
pocketmine\entity\Entity::isImmobile () inherited
Definition at line 340 of file Entity.php.
isInsideOfSolid()
pocketmine\entity\Entity::isInsideOfSolid () inherited
Definition at line 1105 of file Entity.php.
isInvisible()
pocketmine\entity\Entity::isInvisible () inherited
Definition at line 349 of file Entity.php.
isNameTagAlwaysVisible()
pocketmine\entity\Entity::isNameTagAlwaysVisible () inherited
Definition at line 274 of file Entity.php.
isNameTagVisible()
pocketmine\entity\Entity::isNameTagVisible () inherited
Definition at line 270 of file Entity.php.
isOnFire()
pocketmine\entity\Entity::isOnFire () inherited
Definition at line 668 of file Entity.php.
isOnGround()
pocketmine\entity\Entity::isOnGround () inherited
Definition at line 1400 of file Entity.php.
isSilent()
pocketmine\entity\Entity::isSilent () inherited
Definition at line 358 of file Entity.php.
isUnderwater()
pocketmine\entity\Entity::isUnderwater () inherited
Definition at line 1094 of file Entity.php.
kill()
pocketmine\entity\Entity::kill () inherited
Definition at line 549 of file Entity.php.
move()
pocketmine\entity\projectile\Projectile::move (float $dx, float $dy, float $dz) protected inherited
Reimplemented from pocketmine\entity\Entity.
Definition at line 169 of file Projectile.php.
nextRuntimeId()
static pocketmine\entity\Entity::nextRuntimeId () static inherited
Returns a new runtime entity ID for a new entity.
Definition at line 89 of file Entity.php.
Referenced by pocketmine\world\particle\FloatingTextParticle\encode().
onCollideWithPlayer()
pocketmine\entity\projectile\Arrow::onCollideWithPlayer (Player $player)
Reimplemented from pocketmine\entity\Entity.
Definition at line 171 of file entity/projectile/Arrow.php.
onDeath()
pocketmine\entity\Entity::onDeath () protected inherited
Override this to do actions on death.
Reimplemented in pocketmine\entity\Living, pocketmine\entity\object\Painting, and pocketmine\player\Player.
Definition at line 560 of file Entity.php.
onDeathUpdate()
pocketmine\entity\Entity::onDeathUpdate (int $tickDiff) protected inherited
Called to tick entities while dead. Returns whether the entity should be flagged for despawn yet.
Reimplemented in pocketmine\entity\Living, and pocketmine\player\Player.
Definition at line 567 of file Entity.php.
onDispose()
pocketmine\entity\Entity::onDispose () protected inherited
Called when the entity is disposed to clean up things like viewers. This SHOULD NOT destroy internal state, because it may be needed by descendent classes.
Reimplemented in pocketmine\entity\Human, pocketmine\entity\Living, and pocketmine\player\Player.
Definition at line 1573 of file Entity.php.
onHit()
pocketmine\entity\projectile\Arrow::onHit (ProjectileHitEvent $event) protected
Called when the projectile hits something. Override this to perform non-target-specific effects when the projectile hits something.
Reimplemented from pocketmine\entity\projectile\Projectile.
Definition at line 142 of file entity/projectile/Arrow.php.
onHitBlock()
pocketmine\entity\projectile\Arrow::onHitBlock (Block $blockHit, RayTraceResult $hitResult) protected
Called when the projectile collides with a Block.
Reimplemented from pocketmine\entity\projectile\Projectile.
Definition at line 147 of file entity/projectile/Arrow.php.
onHitEntity()
pocketmine\entity\projectile\Arrow::onHitEntity (Entity $entityHit, RayTraceResult $hitResult) protected
Called when the projectile collides with an Entity.
Reimplemented from pocketmine\entity\projectile\Projectile.
Definition at line 152 of file entity/projectile/Arrow.php.
onHitGround()
pocketmine\entity\Entity::onHitGround () protected inherited
Called when a falling entity hits the ground.
Reimplemented in pocketmine\entity\Living.
Definition at line 1071 of file Entity.php.
onInteract()
pocketmine\entity\Entity::onInteract (Player $player, Vector3 $clickPos) inherited
Called when interacted or tapped by a Player. Returns whether something happened as a result of the interaction.
Definition at line 1090 of file Entity.php.
onNearbyBlockChange()
pocketmine\entity\projectile\Projectile::onNearbyBlockChange () inherited
Reimplemented from pocketmine\entity\Entity.
Definition at line 157 of file Projectile.php.
onRandomUpdate()
pocketmine\entity\Entity::onRandomUpdate () inherited
Called when a random update is performed on the chunk the entity is in. This happens when the chunk is within the ticking chunk range of a player (or chunk loader).
Reimplemented in pocketmine\entity\object\Painting.
Definition at line 1013 of file Entity.php.
onUpdate()
pocketmine\entity\Entity::onUpdate (int $currentTick) inherited
Definition at line 942 of file Entity.php.
recalculateBoundingBox()
pocketmine\entity\Entity::recalculateBoundingBox () protected inherited
Definition at line 317 of file Entity.php.
resetFallDistance()
pocketmine\entity\Entity::resetFallDistance () inherited
Definition at line 1046 of file Entity.php.
resetLastMovements()
pocketmine\entity\Entity::resetLastMovements () protected inherited
Definition at line 1362 of file Entity.php.
respawnToAll()
pocketmine\entity\Entity::respawnToAll () inherited
Definition at line 1498 of file Entity.php.
saveNBT()
pocketmine\entity\projectile\Arrow::saveNBT ()
Reimplemented from pocketmine\entity\projectile\Projectile.
Definition at line 88 of file entity/projectile/Arrow.php.
scheduleUpdate()
pocketmine\entity\Entity::scheduleUpdate () final inherited
Definition at line 997 of file Entity.php.
sendData()
pocketmine\entity\Entity::sendData (?array $targets, ?array $data = null) inherited
Parameters
Player[] | null $targets
MetadataProperty[] $data Properly formatted entity data, defaults to everything
@phpstan-param array<int, MetadataProperty> $data
Reimplemented in pocketmine\player\Player.
Definition at line 1596 of file Entity.php.
sendSpawnPacket()
pocketmine\entity\Entity::sendSpawnPacket (Player $player) protected inherited
Called by spawnTo() to send whatever packets needed to spawn the entity to the client.
Reimplemented in pocketmine\entity\Human, pocketmine\entity\Living, pocketmine\entity\object\ItemEntity, and pocketmine\entity\object\Painting.
Definition at line 1459 of file Entity.php.
setBaseDamage()
pocketmine\entity\projectile\Projectile::setBaseDamage (float $damage) inherited
Sets the base amount of damage applied by the projectile.
Definition at line 123 of file Projectile.php.
setCanClimb()
pocketmine\entity\Entity::setCanClimb (bool $value = true) inherited
Sets whether the entity is able to climb climbable blocks.
Definition at line 377 of file Entity.php.
setCanClimbWalls()
pocketmine\entity\Entity::setCanClimbWalls (bool $value = true) inherited
Sets whether the entity is climbing a block. If true, the entity can climb anything.
Definition at line 392 of file Entity.php.
setCanSaveWithChunk()
pocketmine\entity\Entity::setCanSaveWithChunk (bool $value) inherited
Sets whether this entity will be saved when its chunk is unloaded. This can be used to prevent the entity being saved to disk.
Reimplemented in pocketmine\player\Player.
Definition at line 469 of file Entity.php.
setCritical()
pocketmine\entity\projectile\Arrow::setCritical (bool $value = true)
Definition at line 100 of file entity/projectile/Arrow.php.
setFallDistance()
pocketmine\entity\Entity::setFallDistance (float $fallDistance) inherited
Definition at line 1042 of file Entity.php.
setFireTicks()
pocketmine\entity\Entity::setFireTicks (int $fireTicks) inherited
Exceptions
InvalidArgumentException
Definition at line 687 of file Entity.php.
setForceMovementUpdate()
pocketmine\entity\Entity::setForceMovementUpdate (bool $value = true) final inherited
Flags the entity as needing a movement update on the next tick. Setting this forces a movement update even if the entity's motion is zero. Used to trigger movement updates when blocks change near entities.
Definition at line 1021 of file Entity.php.
setHasGravity()
pocketmine\entity\Entity::setHasGravity (bool $v = true) inherited
Definition at line 804 of file Entity.php.
setHealth()
pocketmine\entity\Entity::setHealth (float $amount) inherited
Sets the health of the Entity. This won't send any update to the players
Reimplemented in pocketmine\entity\Living.
Definition at line 582 of file Entity.php.
setImmobile()
pocketmine\entity\Entity::setImmobile (bool $value = true) inherited
Definition at line 344 of file Entity.php.
setInvisible()
pocketmine\entity\Entity::setInvisible (bool $value = true) inherited
Definition at line 353 of file Entity.php.
setLastDamageCause()
pocketmine\entity\Entity::setLastDamageCause (EntityDamageEvent $type) inherited
Definition at line 610 of file Entity.php.
setMaxHealth()
pocketmine\entity\Entity::setMaxHealth (int $amount) inherited
Definition at line 606 of file Entity.php.
setMotion()
pocketmine\entity\Entity::setMotion (Vector3 $motion) inherited
Definition at line 1371 of file Entity.php.
setNameTag()
pocketmine\entity\Entity::setNameTag (string $name) inherited
Definition at line 278 of file Entity.php.
setNameTagAlwaysVisible()
pocketmine\entity\Entity::setNameTagAlwaysVisible (bool $value = true) inherited
Definition at line 287 of file Entity.php.
setNameTagVisible()
pocketmine\entity\Entity::setNameTagVisible (bool $value = true) inherited
Definition at line 283 of file Entity.php.
setOnFire()
pocketmine\entity\Entity::setOnFire (int $seconds) inherited
Definition at line 672 of file Entity.php.
setOwningEntity()
pocketmine\entity\Entity::setOwningEntity (?Entity $owner) inherited
Sets the owner of the entity. Passing null will remove the current owner.
Exceptions
InvalidArgumentException if the supplied entity is not valid
Definition at line 416 of file Entity.php.
setPickupMode()
pocketmine\entity\projectile\Arrow::setPickupMode (int $pickupMode)
Definition at line 167 of file entity/projectile/Arrow.php.
setPosition()
pocketmine\entity\Entity::setPosition (Vector3 $pos) protected inherited
Definition at line 1312 of file Entity.php.
setPositionAndRotation()
pocketmine\entity\Entity::setPositionAndRotation (Vector3 $pos, float $yaw, float $pitch) protected inherited
Definition at line 1352 of file Entity.php.
setPunchKnockback()
pocketmine\entity\projectile\Arrow::setPunchKnockback (float $punchKnockback)
Definition at line 118 of file entity/projectile/Arrow.php.
setRotation()
pocketmine\entity\Entity::setRotation (float $yaw, float $pitch) inherited
Definition at line 1344 of file Entity.php.
setScale()
pocketmine\entity\Entity::setScale (float $value) inherited
Definition at line 305 of file Entity.php.
setScoreTag()
pocketmine\entity\Entity::setScoreTag (string $score) inherited
Definition at line 296 of file Entity.php.
setSilent()
pocketmine\entity\Entity::setSilent (bool $value = true) inherited
Definition at line 362 of file Entity.php.
setSize()
pocketmine\entity\Entity::setSize (EntitySizeInfo $size) protected inherited
Definition at line 334 of file Entity.php.
setTargetEntity()
pocketmine\entity\Entity::setTargetEntity (?Entity $target) inherited
Sets the entity's target entity. Passing null will remove the current target.
Exceptions
InvalidArgumentException if the target entity is not valid
Definition at line 447 of file Entity.php.
spawnTo()
pocketmine\entity\Entity::spawnTo (Player $player) inherited
Definition at line 1477 of file Entity.php.
spawnToAll()
pocketmine\entity\Entity::spawnToAll () inherited
Definition at line 1489 of file Entity.php.
syncNetworkData()
pocketmine\entity\projectile\Arrow::syncNetworkData (EntityMetadataCollection $properties) protected
Reimplemented from pocketmine\entity\Entity.
Definition at line 205 of file entity/projectile/Arrow.php.
teleport()
pocketmine\entity\Entity::teleport (Vector3 $pos, ?float $yaw = null, ?float $pitch = null) inherited
Parameters
Vector3 | Position | Location $pos
Reimplemented in pocketmine\player\Player.
Definition at line 1407 of file Entity.php.
Referenced by pocketmine\item\ChorusFruit\onConsume().
tryChangeMovement()
pocketmine\entity\Entity::tryChangeMovement () protected inherited
Definition at line 812 of file Entity.php.
updateFallState()
pocketmine\entity\Entity::updateFallState (float $distanceThisTick, bool $onGround) protected inherited
Definition at line 1050 of file Entity.php.
updateMovement()
pocketmine\entity\Entity::updateMovement (bool $teleport = false) protected inherited
Definition at line 740 of file Entity.php.
Member Data Documentation
$alwaysShowNameTag
pocketmine\entity\Entity::$alwaysShowNameTag = false protected inherited
Definition at line 197 of file Entity.php.
$attributeMap
pocketmine\entity\Entity::$attributeMap protected inherited
Definition at line 169 of file Entity.php.
$blockHit
pocketmine\entity\projectile\Projectile::$blockHit protected inherited
Definition at line 58 of file Projectile.php.
$blocksAround
pocketmine\entity\Entity::$blocksAround protected inherited
Definition at line 106 of file Entity.php.
$boundingBox
pocketmine\entity\Entity::$boundingBox inherited
Definition at line 120 of file Entity.php.
$canClimb
pocketmine\entity\Entity::$canClimb = false protected inherited
Definition at line 204 of file Entity.php.
$canClimbWalls
pocketmine\entity\Entity::$canClimbWalls = false protected inherited
Definition at line 206 of file Entity.php.
$canCollide
pocketmine\entity\Entity::$canCollide = true inherited
Definition at line 148 of file Entity.php.
$closed
pocketmine\entity\Entity::$closed = false protected inherited
Definition at line 182 of file Entity.php.
$collideTicks
pocketmine\entity\projectile\Arrow::$collideTicks = 0 protected
Definition at line 68 of file entity/projectile/Arrow.php.
$critical
pocketmine\entity\projectile\Arrow::$critical = false protected
Definition at line 71 of file entity/projectile/Arrow.php.
$damage
pocketmine\entity\projectile\Arrow::$damage = 2.0 protected
Definition at line 59 of file entity/projectile/Arrow.php.
$drag
pocketmine\entity\projectile\Arrow::$drag = 0.01 protected
Definition at line 56 of file entity/projectile/Arrow.php.
$fallDistance
pocketmine\entity\Entity::$fallDistance = 0.0 inherited
Definition at line 140 of file Entity.php.
$fireTicks
pocketmine\entity\Entity::$fireTicks = 0 protected inherited
Definition at line 146 of file Entity.php.
$forceMovementUpdate
pocketmine\entity\Entity::$forceMovementUpdate = false protected inherited
Definition at line 117 of file Entity.php.
$gravity
pocketmine\entity\projectile\Arrow::$gravity = 0.05 protected
Definition at line 55 of file entity/projectile/Arrow.php.
$gravityEnabled
pocketmine\entity\Entity::$gravityEnabled = true protected inherited
Definition at line 176 of file Entity.php.
$hasSpawned
pocketmine\entity\Entity::$hasSpawned = [] protected inherited
Definition at line 94 of file Entity.php.
$id
pocketmine\entity\Entity::$id protected inherited
Definition at line 97 of file Entity.php.
$immobile
pocketmine\entity\Entity::$immobile = false protected inherited
Definition at line 208 of file Entity.php.
$invisible
pocketmine\entity\Entity::$invisible = false protected inherited
Definition at line 210 of file Entity.php.
$isCollided
pocketmine\entity\Entity::$isCollided = false inherited
Definition at line 157 of file Entity.php.
$isCollidedHorizontally
pocketmine\entity\Entity::$isCollidedHorizontally = false inherited
Definition at line 159 of file Entity.php.
$isCollidedVertically
pocketmine\entity\Entity::$isCollidedVertically = false inherited
Definition at line 161 of file Entity.php.
$isStatic
pocketmine\entity\Entity::$isStatic = false protected inherited
Definition at line 151 of file Entity.php.
$justCreated
pocketmine\entity\Entity::$justCreated = true protected inherited
Definition at line 166 of file Entity.php.
$keepMovement
pocketmine\entity\Entity::$keepMovement = false inherited
Definition at line 137 of file Entity.php.
$lastDamageCause
pocketmine\entity\Entity::$lastDamageCause = null protected inherited
Definition at line 103 of file Entity.php.
$lastLocation
pocketmine\entity\Entity::$lastLocation protected inherited
Definition at line 111 of file Entity.php.
$lastMotion
pocketmine\entity\Entity::$lastMotion protected inherited
Definition at line 115 of file Entity.php.
$lastUpdate
pocketmine\entity\Entity::$lastUpdate inherited
Definition at line 144 of file Entity.php.
$location
pocketmine\entity\Entity::$location protected inherited
Definition at line 109 of file Entity.php.
$motion
pocketmine\entity\Entity::$motion protected inherited
Definition at line 113 of file Entity.php.
$nameTag
pocketmine\entity\Entity::$nameTag = "" protected inherited
Definition at line 193 of file Entity.php.
$nameTagVisible
pocketmine\entity\Entity::$nameTagVisible = true protected inherited
Definition at line 195 of file Entity.php.
$networkPropertiesDirty
bool pocketmine\entity\Entity::$networkPropertiesDirty = false protected inherited
Definition at line 190 of file Entity.php.
$noDamageTicks
pocketmine\entity\Entity::$noDamageTicks = 0 inherited
Definition at line 164 of file Entity.php.
$onGround
pocketmine\entity\Entity::$onGround = false inherited
Definition at line 122 of file Entity.php.
$ownerId
pocketmine\entity\Entity::$ownerId = null protected inherited
Definition at line 215 of file Entity.php.
$pickupMode
pocketmine\entity\projectile\Arrow::$pickupMode = self::PICKUP_ANY protected
Definition at line 62 of file entity/projectile/Arrow.php.
$punchKnockback
pocketmine\entity\projectile\Arrow::$punchKnockback = 0.0 protected
Definition at line 65 of file entity/projectile/Arrow.php.
$scale
pocketmine\entity\Entity::$scale = 1.0 protected inherited
Definition at line 201 of file Entity.php.
$scoreTag
pocketmine\entity\Entity::$scoreTag = "" protected inherited
Definition at line 199 of file Entity.php.
$server
pocketmine\entity\Entity::$server protected inherited
Definition at line 179 of file Entity.php.
$silent
pocketmine\entity\Entity::$silent = false protected inherited
Definition at line 212 of file Entity.php.
$size
pocketmine\entity\Entity::$size inherited
Definition at line 125 of file Entity.php.
$stepHeight
pocketmine\entity\Entity::$stepHeight = 0.0 protected inherited
Definition at line 135 of file Entity.php.
$targetId
pocketmine\entity\Entity::$targetId = null protected inherited
Definition at line 217 of file Entity.php.
$ticksLived
pocketmine\entity\Entity::$ticksLived = 0 inherited
Definition at line 142 of file Entity.php.
$timings
pocketmine\entity\Entity::$timings protected inherited
Definition at line 188 of file Entity.php.
$ySize
pocketmine\entity\Entity::$ySize = 0.0 protected inherited
Definition at line 133 of file Entity.php.
MOTION_THRESHOLD
const pocketmine\entity\Entity::MOTION_THRESHOLD = 0.00001 inherited
Definition at line 80 of file Entity.php.
PICKUP_ANY
const pocketmine\entity\projectile\Arrow::PICKUP_ANY = 1
Definition at line 49 of file entity/projectile/Arrow.php.
PICKUP_CREATIVE
const pocketmine\entity\projectile\Arrow::PICKUP_CREATIVE = 2
Definition at line 50 of file entity/projectile/Arrow.php.
PICKUP_NONE
const pocketmine\entity\projectile\Arrow::PICKUP_NONE = 0
Definition at line 48 of file entity/projectile/Arrow.php.
STEP_CLIP_MULTIPLIER
const pocketmine\entity\Entity::STEP_CLIP_MULTIPLIER = 0.4 protected inherited
Definition at line 81 of file Entity.php.
TAG_CRIT
const pocketmine\entity\projectile\Arrow::TAG_CRIT = "crit"
Definition at line 53 of file entity/projectile/Arrow.php.
The documentation for this class was generated from the following file:
entity/projectile/Arrow.php