PocketMine-MP: DaveRandom\CallbackValidator\CallbackType Class Reference
DaveRandom\CallbackValidator\CallbackType Class Reference
Public Member Functions
__construct (ReturnType $returnType, ParameterType ... $parameters)
__toString ()
isSatisfiedBy ($callable)
Static Public Member Functions
static createFromCallable ($callable, $flags=ParameterType::CONTRAVARIANT|ReturnType::COVARIANT)
Detailed Description
Definition at line 5 of file CallbackType.php.
Constructor & Destructor Documentation
__construct()
DaveRandom\CallbackValidator\CallbackType::__construct (ReturnType $returnType, ParameterType ... $parameters)
Definition at line 75 of file CallbackType.php.
Member Function Documentation
__toString()
DaveRandom\CallbackValidator\CallbackType::__toString ()
Returns
string
Definition at line 152 of file CallbackType.php.
createFromCallable()
static DaveRandom\CallbackValidator\CallbackType::createFromCallable ($callable, $flags = ParameterType::CONTRAVARIANT | ReturnType::COVARIANT) static
Parameters
callable $callable
int $flags
Returns
CallbackType
Exceptions
InvalidCallbackException
Definition at line 56 of file CallbackType.php.
References DaveRandom\CallbackValidator\ReturnType\createFromReflectionFunctionAbstract(), and DaveRandom\CallbackValidator\ParameterType\createFromReflectionParameter().
isSatisfiedBy()
DaveRandom\CallbackValidator\CallbackType::isSatisfiedBy ($callable)
Parameters
callable $callable
Returns
bool
Definition at line 85 of file CallbackType.php.
References DaveRandom\CallbackValidator\CallbackType\isSatisfiedBy().
Referenced by DaveRandom\CallbackValidator\CallbackType\isSatisfiedBy().
The documentation for this class was generated from the following file:
CallbackType.php