PocketMine-MP: pocketmine\utils\Process Class Reference
pocketmine\utils\Process Class Reference
Static Public Member Functions
static execute (string $command, string &$stdout=null, string &$stderr=null)
static getAdvancedMemoryUsage ()
static getMemoryUsage ()
static getRealMemoryUsage ()
static getThreadCount ()
static kill (int $pid, bool $subprocesses)
static pid ()
static uid ()
Detailed Description
Definition at line 45 of file Process.php.
Member Function Documentation
execute()
static pocketmine\utils\Process::execute (string $command, string & $stdout = null, string & $stderr = null) static
Parameters
string $command Command to execute
string | null $stdout Reference parameter to write stdout to
string | null $stderr Reference parameter to write stderr to
Returns
int process exit code
Definition at line 158 of file Process.php.
Referenced by pocketmine\utils\Git\getRepositoryState().
getAdvancedMemoryUsage()
static pocketmine\utils\Process::getAdvancedMemoryUsage () static
Returns
int[] @phpstan-return array{int,int,int}
Definition at line 55 of file Process.php.
References pocketmine\utils\Utils\getOS().
Referenced by pocketmine\stats\SendUsageTask\__construct(), and pocketmine\command\defaults\StatusCommand\execute().
getMemoryUsage()
static pocketmine\utils\Process::getMemoryUsage () static
Definition at line 86 of file Process.php.
getRealMemoryUsage()
static pocketmine\utils\Process::getRealMemoryUsage () static
Returns
int[]
Definition at line 93 of file Process.php.
getThreadCount()
static pocketmine\utils\Process::getThreadCount () static
Definition at line 114 of file Process.php.
kill()
static pocketmine\utils\Process::kill (int $pid, bool $subprocesses) static
Definition at line 128 of file Process.php.
pid()
static pocketmine\utils\Process::pid () static
Definition at line 182 of file Process.php.
uid()
static pocketmine\utils\Process::uid () static
Definition at line 190 of file Process.php.
The documentation for this class was generated from the following file:
Process.php