PocketMine-MP: pocketmine\block\tile\Chest Class Reference
pocketmine\block\tile\Chest Class Reference
Public Member Functions
__construct (World $world, Vector3 $pos)
canOpenWith (string $key)
clearSpawnCompoundCache ()
close ()
copyDataFromItem (Item $item)
getBlock ()
getCleanedNBT ()
getDefaultName ()
getInventory ()
getName ()
getPair ()
getPosition ()
getRealInventory ()
getSerializedSpawnCompound ()
getSpawnCompound ()
hasName ()
isClosed ()
isDirty ()
isPaired ()
onBlockDestroyed ()
pairWith (Chest $tile)
readSaveData (CompoundTag $nbt)
saveNBT ()
setDirty (bool $dirty=true)
setName (string $str)
unpair ()
Public Attributes
$closed = false
const TAG_CUSTOM_NAME = "CustomName"
const TAG_ID = "id"
const TAG_ITEMS = "Items"
const TAG_LOCK = "Lock"
const TAG_PAIR_LEAD = "pairlead"
const TAG_PAIRX = "pairx"
const TAG_PAIRZ = "pairz"
const TAG_X = "x"
const TAG_Y = "y"
const TAG_Z = "z"
Protected Member Functions
addAdditionalSpawnData (CompoundTag $nbt)
checkPairing ()
onBlockDestroyedHook ()
writeSaveData (CompoundTag $nbt)
Protected Attributes
$doubleInventory = null
$inventory
$position
$timings
Detailed Description
Definition at line 35 of file tile/Chest.php.
Constructor & Destructor Documentation
__construct()
pocketmine\block\tile\Chest::__construct (World $world, Vector3 $pos)
Reimplemented from pocketmine\block\tile\Tile.
Definition at line 55 of file tile/Chest.php.
Member Function Documentation
addAdditionalSpawnData()
pocketmine\block\tile\Chest::addAdditionalSpawnData (CompoundTag $nbt) protected
An extension to getSpawnCompound() for further modifying the generic tile NBT.
Reimplemented from pocketmine\block\tile\Spawnable.
Definition at line 224 of file tile/Chest.php.
References pocketmine\nbt\tag\CompoundTag\setInt().
canOpenWith()
pocketmine\block\tile\Container::canOpenWith (string $key) inherited
Returns whether this container can be opened by an item with the given custom name.
checkPairing()
pocketmine\block\tile\Chest::checkPairing () protected
Definition at line 136 of file tile/Chest.php.
clearSpawnCompoundCache()
pocketmine\block\tile\Spawnable::clearSpawnCompoundCache () inherited
Definition at line 48 of file Spawnable.php.
close()
pocketmine\block\tile\Chest::close ()
Reimplemented from pocketmine\block\tile\Tile.
Definition at line 96 of file tile/Chest.php.
copyDataFromItem()
pocketmine\block\tile\Tile::copyDataFromItem (Item $item) inherited
Definition at line 93 of file Tile.php.
getBlock()
pocketmine\block\tile\Tile::getBlock () inherited
Definition at line 99 of file Tile.php.
getCleanedNBT()
pocketmine\block\tile\Chest::getCleanedNBT ()
Reimplemented from pocketmine\block\tile\Tile.
Definition at line 87 of file tile/Chest.php.
getDefaultName()
pocketmine\block\tile\Chest::getDefaultName ()
Implements pocketmine\block\tile\Nameable.
Definition at line 163 of file tile/Chest.php.
getInventory()
pocketmine\block\tile\Chest::getInventory ()
Returns
ChestInventory|DoubleChestInventory
Implements pocketmine\inventory\InventoryHolder.
Definition at line 122 of file tile/Chest.php.
getPair()
pocketmine\block\tile\Chest::getPair ()
Definition at line 171 of file tile/Chest.php.
getPosition()
pocketmine\block\tile\Tile::getPosition () inherited
Definition at line 103 of file Tile.php.
getRealInventory()
pocketmine\block\tile\Chest::getRealInventory ()
Returns
ChestInventory
Implements pocketmine\block\tile\Container.
Definition at line 132 of file tile/Chest.php.
getSerializedSpawnCompound()
pocketmine\block\tile\Spawnable::getSerializedSpawnCompound () final inherited
Returns encoded NBT (varint, little-endian) used to spawn this tile to clients. Uses cache where possible, populates cache if it is null.
@phpstan-return CacheableNbt<\pocketmine\nbt\tag\CompoundTag>
Definition at line 58 of file Spawnable.php.
getSpawnCompound()
pocketmine\block\tile\Spawnable::getSpawnCompound () final inherited
Definition at line 66 of file Spawnable.php.
isClosed()
pocketmine\block\tile\Tile::isClosed () inherited
Definition at line 107 of file Tile.php.
isDirty()
pocketmine\block\tile\Spawnable::isDirty () inherited
Deprecated:
Definition at line 37 of file Spawnable.php.
isPaired()
pocketmine\block\tile\Chest::isPaired ()
Definition at line 167 of file tile/Chest.php.
onBlockDestroyed()
pocketmine\block\tile\Tile::onBlockDestroyed () final inherited
Called when the tile's block is destroyed.
Definition at line 118 of file Tile.php.
References pocketmine\block\tile\onBlockDestroyedHook().
onBlockDestroyedHook()
pocketmine\block\tile\Chest::onBlockDestroyedHook () protected
Override this method to do actions you need to do when this tile is destroyed due to block being broken.
Reimplemented from pocketmine\block\tile\Tile.
Definition at line 114 of file tile/Chest.php.
pairWith()
pocketmine\block\tile\Chest::pairWith (Chest $tile)
Definition at line 182 of file tile/Chest.php.
readSaveData()
pocketmine\block\tile\Chest::readSaveData (CompoundTag $nbt)
Reimplemented from pocketmine\block\tile\Tile.
Definition at line 60 of file tile/Chest.php.
saveNBT()
pocketmine\block\tile\Tile::saveNBT () inherited
Definition at line 72 of file Tile.php.
setDirty()
pocketmine\block\tile\Spawnable::setDirty (bool $dirty = true) inherited
Deprecated:
Definition at line 44 of file Spawnable.php.
unpair()
pocketmine\block\tile\Chest::unpair ()
Definition at line 204 of file tile/Chest.php.
writeSaveData()
pocketmine\block\tile\Chest::writeSaveData (CompoundTag $nbt) protected
Writes additional save data to a CompoundTag, not including generic things like ID and coordinates.
Reimplemented from pocketmine\block\tile\Tile.
Definition at line 78 of file tile/Chest.php.
References pocketmine\nbt\tag\CompoundTag\setInt().
Member Data Documentation
$closed
pocketmine\block\tile\Tile::$closed = false inherited
Definition at line 51 of file Tile.php.
$doubleInventory
pocketmine\block\tile\Chest::$doubleInventory = null protected
Definition at line 50 of file tile/Chest.php.
$inventory
pocketmine\block\tile\Chest::$inventory protected
Definition at line 48 of file tile/Chest.php.
$position
pocketmine\block\tile\Tile::$position protected inherited
Definition at line 49 of file Tile.php.
$timings
pocketmine\block\tile\Tile::$timings protected inherited
Definition at line 53 of file Tile.php.
TAG_CUSTOM_NAME
const pocketmine\block\tile\Nameable::TAG_CUSTOM_NAME = "CustomName" inherited
Definition at line 27 of file Nameable.php.
TAG_ID
const pocketmine\block\tile\Tile::TAG_ID = "id" inherited
Definition at line 43 of file Tile.php.
TAG_ITEMS
const pocketmine\block\tile\Container::TAG_ITEMS = "Items" inherited
Definition at line 30 of file Container.php.
TAG_LOCK
const pocketmine\block\tile\Container::TAG_LOCK = "Lock" inherited
Definition at line 31 of file Container.php.
TAG_PAIR_LEAD
const pocketmine\block\tile\Chest::TAG_PAIR_LEAD = "pairlead"
Definition at line 45 of file tile/Chest.php.
TAG_PAIRX
const pocketmine\block\tile\Chest::TAG_PAIRX = "pairx"
Definition at line 43 of file tile/Chest.php.
TAG_PAIRZ
const pocketmine\block\tile\Chest::TAG_PAIRZ = "pairz"
Definition at line 44 of file tile/Chest.php.
TAG_X
const pocketmine\block\tile\Tile::TAG_X = "x" inherited
Definition at line 44 of file Tile.php.
TAG_Y
const pocketmine\block\tile\Tile::TAG_Y = "y" inherited
Definition at line 45 of file Tile.php.
TAG_Z
const pocketmine\block\tile\Tile::TAG_Z = "z" inherited
Definition at line 46 of file Tile.php.
The documentation for this class was generated from the following file:
tile/Chest.php