PocketMine-MP: pocketmine\network\upnp\UPnPNetworkInterface Class Reference
pocketmine\network\upnp\UPnPNetworkInterface Class Reference
Public Member Functions
__construct (private \Logger $logger, private string $ip, private int $port)
setName (string $name)
shutdown ()
start ()
tick ()
Detailed Description
Definition at line 30 of file UPnPNetworkInterface.php.
Constructor & Destructor Documentation
__construct()
pocketmine\network\upnp\UPnPNetworkInterface::__construct (private \Logger $logger, private string $ip, private int $port)
Definition at line 33 of file UPnPNetworkInterface.php.
Member Function Documentation
setName()
pocketmine\network\upnp\UPnPNetworkInterface::setName (string $name)
Implements pocketmine\network\NetworkInterface.
Definition at line 57 of file UPnPNetworkInterface.php.
shutdown()
pocketmine\network\upnp\UPnPNetworkInterface::shutdown ()
Gracefully shuts down the network interface.
Implements pocketmine\network\NetworkInterface.
Definition at line 65 of file UPnPNetworkInterface.php.
start()
pocketmine\network\upnp\UPnPNetworkInterface::start ()
Performs actions needed to start the interface after it is registered.
Exceptions
NetworkInterfaceStartException
Implements pocketmine\network\NetworkInterface.
Definition at line 45 of file UPnPNetworkInterface.php.
References pocketmine\utils\Internet\getInternalIP(), pocketmine\network\upnp\UPnP\getServiceUrl(), and pocketmine\network\upnp\UPnP\portForward().
tick()
pocketmine\network\upnp\UPnPNetworkInterface::tick ()
Called every tick to process events on the interface.
Implements pocketmine\network\NetworkInterface.
Definition at line 61 of file UPnPNetworkInterface.php.
The documentation for this class was generated from the following file:
UPnPNetworkInterface.php