PocketMine-MP: pocketmine\network\mcpe\protocol\AvailableCommandsPacket Class Reference
pocketmine\network\mcpe\protocol\AvailableCommandsPacket Class Reference
Public Member Functions
__get ($name)
__set ($name, $value)
canBeSentBeforeLogin ()
decode (PacketSerializer $in)
encode (PacketSerializer $out)
getName ()
handle (PacketHandlerInterface $handler)
pid ()
Static Public Member Functions
static create (array $commandData, array $hardcodedEnums, array $softEnums, array $enumConstraints)
Public Attributes
array $commandData = []
array $enumConstraints = []
array $hardcodedEnums = []
int $recipientSubId = 0
int $senderSubId = 0
array $softEnums = []
const ARG_FLAG_ENUM = 0x200000
const ARG_FLAG_POSTFIX = 0x1000000
const ARG_FLAG_VALID = 0x100000
const ARG_TYPE_BLOCK_STATES = 0x43
const ARG_TYPE_COMMAND = 0x46
const ARG_TYPE_COMPARE_OPERATOR = 0x07
const ARG_TYPE_EQUIPMENT_SLOT = 0x26
const ARG_TYPE_FILEPATH = 0x11
const ARG_TYPE_FLOAT = 0x03
const ARG_TYPE_FULL_INTEGER_RANGE = 0x17
const ARG_TYPE_INT = 0x01
const ARG_TYPE_INT_POSITION = 0x2f
const ARG_TYPE_JSON = 0x39
const ARG_TYPE_MESSAGE = 0x33
const ARG_TYPE_OPERATOR = 0x06
const ARG_TYPE_POSITION = 0x30
const ARG_TYPE_RAWTEXT = 0x35
const ARG_TYPE_STRING = 0x27
const ARG_TYPE_TARGET = 0x08
const ARG_TYPE_VALUE = 0x04
const ARG_TYPE_WILDCARD_INT = 0x05
const ARG_TYPE_WILDCARD_TARGET = 0x0a
const HARDCODED_ENUM_NAMES
const NETWORK_ID = ProtocolInfo::AVAILABLE_COMMANDS_PACKET
const PID_MASK = 0x3ff
Protected Member Functions
decodeHeader (PacketSerializer $in)
decodePayload (PacketSerializer $in)
encodeHeader (PacketSerializer $out)
encodePayload (PacketSerializer $out)
getCommandData (array $enums, array $postfixes, PacketSerializer $in)
getEnum (array $enumValueList, PacketSerializer $in)
getEnumConstraint (array $enums, array $enumValues, PacketSerializer $in)
getEnumValueIndex (int $valueCount, PacketSerializer $in)
getSoftEnum (PacketSerializer $in)
putCommandData (CommandData $data, array $enumIndexes, array $postfixIndexes, PacketSerializer $out)
putEnum (CommandEnum $enum, array $enumValueMap, PacketSerializer $out)
putEnumConstraint (CommandEnumConstraint $constraint, array $enumIndexes, array $enumValueIndexes, PacketSerializer $out)
putEnumValueIndex (int $index, int $valueCount, PacketSerializer $out)
putSoftEnum (CommandEnum $enum, PacketSerializer $out)
Detailed Description
Definition at line 27 of file AvailableCommandsPacket.php.
Member Function Documentation
__get()
pocketmine\network\mcpe\protocol\DataPacket::__get ($name) inherited
Parameters
string $name
Returns
mixed
Definition at line 105 of file DataPacket.php.
__set()
pocketmine\network\mcpe\protocol\DataPacket::__set ($name, $value) inherited
Parameters
string $name
mixed $value
Definition at line 113 of file DataPacket.php.
canBeSentBeforeLogin()
pocketmine\network\mcpe\protocol\DataPacket::canBeSentBeforeLogin () inherited
Implements pocketmine\network\mcpe\protocol\Packet.
Definition at line 42 of file DataPacket.php.
create()
static pocketmine\network\mcpe\protocol\AvailableCommandsPacket::create (array $commandData, array $hardcodedEnums, array $softEnums, array $enumConstraints) static
@generate-create-func
Parameters
CommandData[] $commandData
CommandEnum[] $hardcodedEnums
CommandEnum[] $softEnums
CommandEnumConstraint[] $enumConstraints
Definition at line 116 of file AvailableCommandsPacket.php.
decode()
pocketmine\network\mcpe\protocol\DataPacket::decode (PacketSerializer $in) final inherited
Exceptions
PacketDecodeException
Implements pocketmine\network\mcpe\protocol\Packet.
Definition at line 49 of file DataPacket.php.
decodeHeader()
pocketmine\network\mcpe\protocol\DataPacket::decodeHeader (PacketSerializer $in) protected inherited
Exceptions
BinaryDataException
PacketDecodeException
Definition at line 62 of file DataPacket.php.
decodePayload()
pocketmine\network\mcpe\protocol\AvailableCommandsPacket::decodePayload (PacketSerializer $in) protected
Decodes the packet body, without the packet ID or other generic header fields.
Exceptions
PacketDecodeException
BinaryDataException
Reimplemented from pocketmine\network\mcpe\protocol\DataPacket.
Definition at line 125 of file AvailableCommandsPacket.php.
References pocketmine\network\mcpe\protocol\serializer\PacketSerializer\getString().
encode()
pocketmine\network\mcpe\protocol\DataPacket::encode (PacketSerializer $out) final inherited
Implements pocketmine\network\mcpe\protocol\Packet.
Definition at line 82 of file DataPacket.php.
encodeHeader()
pocketmine\network\mcpe\protocol\DataPacket::encodeHeader (PacketSerializer $out) protected inherited
Definition at line 87 of file DataPacket.php.
encodePayload()
pocketmine\network\mcpe\protocol\AvailableCommandsPacket::encodePayload (PacketSerializer $out) protected
Encodes the packet body, without the packet ID or other generic header fields.
Reimplemented from pocketmine\network\mcpe\protocol\DataPacket.
Definition at line 381 of file AvailableCommandsPacket.php.
getCommandData()
pocketmine\network\mcpe\protocol\AvailableCommandsPacket::getCommandData (array $enums, array $postfixes, PacketSerializer $in) protected
Parameters
CommandEnum[] $enums
string[] $postfixes
Exceptions
PacketDecodeException
BinaryDataException
Definition at line 300 of file AvailableCommandsPacket.php.
References pocketmine\utils\BinaryStream\getBool(), pocketmine\utils\BinaryStream\getByte(), pocketmine\utils\BinaryStream\getLInt(), pocketmine\network\mcpe\protocol\serializer\PacketSerializer\getString(), and pocketmine\utils\BinaryStream\getUnsignedVarInt().
getEnum()
pocketmine\network\mcpe\protocol\AvailableCommandsPacket::getEnum (array $enumValueList, PacketSerializer $in) protected
Parameters
string[] $enumValueList
Exceptions
PacketDecodeException
BinaryDataException
Definition at line 166 of file AvailableCommandsPacket.php.
getEnumConstraint()
pocketmine\network\mcpe\protocol\AvailableCommandsPacket::getEnumConstraint (array $enums, array $enumValues, PacketSerializer $in) protected
Parameters
CommandEnum[] $enums
string[] $enumValues
Exceptions
PacketDecodeException
BinaryDataException
Definition at line 256 of file AvailableCommandsPacket.php.
getEnumValueIndex()
pocketmine\network\mcpe\protocol\AvailableCommandsPacket::getEnumValueIndex (int $valueCount, PacketSerializer $in) protected
Exceptions
BinaryDataException
Definition at line 229 of file AvailableCommandsPacket.php.
References pocketmine\utils\BinaryStream\getByte().
getName()
pocketmine\network\mcpe\protocol\DataPacket::getName () inherited
Implements pocketmine\network\mcpe\protocol\Packet.
Definition at line 38 of file DataPacket.php.
getSoftEnum()
pocketmine\network\mcpe\protocol\AvailableCommandsPacket::getSoftEnum (PacketSerializer $in) protected
Exceptions
BinaryDataException
Definition at line 187 of file AvailableCommandsPacket.php.
References pocketmine\network\mcpe\protocol\serializer\PacketSerializer\getString().
handle()
pocketmine\network\mcpe\protocol\AvailableCommandsPacket::handle (PacketHandlerInterface $handler)
Performs handling for this packet. Usually you'll want an appropriately named method in the session handler for this.
This method returns a bool to indicate whether the packet was handled or not. If the packet was unhandled, a debug message will be logged with a hexdump of the packet.
Typically this method returns the return value of the handler in the supplied PacketHandler. See other packets for examples how to implement this.
Returns
bool true if the packet was handled successfully, false if not.
Exceptions
PacketDecodeException if broken data was found in the packet
Implements pocketmine\network\mcpe\protocol\Packet.
Definition at line 452 of file AvailableCommandsPacket.php.
pid()
pocketmine\network\mcpe\protocol\DataPacket::pid () inherited
Implements pocketmine\network\mcpe\protocol\Packet.
Definition at line 34 of file DataPacket.php.
putCommandData()
pocketmine\network\mcpe\protocol\AvailableCommandsPacket::putCommandData (CommandData $data, array $enumIndexes, array $postfixIndexes, PacketSerializer $out) protected
Parameters
int[] $enumIndexes string enum name -> int index
int[] $postfixIndexes
Definition at line 344 of file AvailableCommandsPacket.php.
putEnum()
pocketmine\network\mcpe\protocol\AvailableCommandsPacket::putEnum (CommandEnum $enum, array $enumValueMap, PacketSerializer $out) protected
Parameters
int[] $enumValueMap
Definition at line 202 of file AvailableCommandsPacket.php.
putEnumConstraint()
pocketmine\network\mcpe\protocol\AvailableCommandsPacket::putEnumConstraint (CommandEnumConstraint $constraint, array $enumIndexes, array $enumValueIndexes, PacketSerializer $out) protected
Parameters
int[] $enumIndexes string enum name -> int index
int[] $enumValueIndexes string value -> int index
Definition at line 284 of file AvailableCommandsPacket.php.
putEnumValueIndex()
pocketmine\network\mcpe\protocol\AvailableCommandsPacket::putEnumValueIndex (int $index, int $valueCount, PacketSerializer $out) protected
Definition at line 239 of file AvailableCommandsPacket.php.
putSoftEnum()
pocketmine\network\mcpe\protocol\AvailableCommandsPacket::putSoftEnum (CommandEnum $enum, PacketSerializer $out) protected
Definition at line 216 of file AvailableCommandsPacket.php.
Member Data Documentation
$commandData
array pocketmine\network\mcpe\protocol\AvailableCommandsPacket::$commandData = []
Definition at line 87 of file AvailableCommandsPacket.php.
$enumConstraints
array pocketmine\network\mcpe\protocol\AvailableCommandsPacket::$enumConstraints = []
Definition at line 107 of file AvailableCommandsPacket.php.
$hardcodedEnums
array pocketmine\network\mcpe\protocol\AvailableCommandsPacket::$hardcodedEnums = []
Definition at line 94 of file AvailableCommandsPacket.php.
$recipientSubId
int pocketmine\network\mcpe\protocol\DataPacket::$recipientSubId = 0 inherited
Definition at line 32 of file DataPacket.php.
$senderSubId
int pocketmine\network\mcpe\protocol\DataPacket::$senderSubId = 0 inherited
Definition at line 31 of file DataPacket.php.
$softEnums
array pocketmine\network\mcpe\protocol\AvailableCommandsPacket::$softEnums = []
Definition at line 101 of file AvailableCommandsPacket.php.
ARG_FLAG_ENUM
const pocketmine\network\mcpe\protocol\AvailableCommandsPacket::ARG_FLAG_ENUM = 0x200000
Enums are a little different: they are composed as follows: ARG_FLAG_ENUM | ARG_FLAG_VALID | (enum index)
Definition at line 74 of file AvailableCommandsPacket.php.
ARG_FLAG_POSTFIX
const pocketmine\network\mcpe\protocol\AvailableCommandsPacket::ARG_FLAG_POSTFIX = 0x1000000
This is used for /xp <level: int>L. It can only be applied to integer parameters.
Definition at line 77 of file AvailableCommandsPacket.php.
ARG_FLAG_VALID
const pocketmine\network\mcpe\protocol\AvailableCommandsPacket::ARG_FLAG_VALID = 0x100000
This flag is set on all types EXCEPT the POSTFIX type. Not completely sure what this is for, but it is required for the argtype to work correctly. VALID seems as good a name as any.
Definition at line 34 of file AvailableCommandsPacket.php.
ARG_TYPE_BLOCK_STATES
const pocketmine\network\mcpe\protocol\AvailableCommandsPacket::ARG_TYPE_BLOCK_STATES = 0x43
Definition at line 66 of file AvailableCommandsPacket.php.
ARG_TYPE_COMMAND
const pocketmine\network\mcpe\protocol\AvailableCommandsPacket::ARG_TYPE_COMMAND = 0x46
Definition at line 68 of file AvailableCommandsPacket.php.
ARG_TYPE_COMPARE_OPERATOR
const pocketmine\network\mcpe\protocol\AvailableCommandsPacket::ARG_TYPE_COMPARE_OPERATOR = 0x07
Definition at line 45 of file AvailableCommandsPacket.php.
ARG_TYPE_EQUIPMENT_SLOT
const pocketmine\network\mcpe\protocol\AvailableCommandsPacket::ARG_TYPE_EQUIPMENT_SLOT = 0x26
Definition at line 54 of file AvailableCommandsPacket.php.
ARG_TYPE_FILEPATH
const pocketmine\network\mcpe\protocol\AvailableCommandsPacket::ARG_TYPE_FILEPATH = 0x11
Definition at line 50 of file AvailableCommandsPacket.php.
ARG_TYPE_FLOAT
const pocketmine\network\mcpe\protocol\AvailableCommandsPacket::ARG_TYPE_FLOAT = 0x03
Definition at line 41 of file AvailableCommandsPacket.php.
ARG_TYPE_FULL_INTEGER_RANGE
const pocketmine\network\mcpe\protocol\AvailableCommandsPacket::ARG_TYPE_FULL_INTEGER_RANGE = 0x17
Definition at line 52 of file AvailableCommandsPacket.php.
ARG_TYPE_INT
const pocketmine\network\mcpe\protocol\AvailableCommandsPacket::ARG_TYPE_INT = 0x01
Basic parameter types. These must be combined with the ARG_FLAG_VALID constant. ARG_FLAG_VALID | (type const)
Definition at line 40 of file AvailableCommandsPacket.php.
ARG_TYPE_INT_POSITION
const pocketmine\network\mcpe\protocol\AvailableCommandsPacket::ARG_TYPE_INT_POSITION = 0x2f
Definition at line 57 of file AvailableCommandsPacket.php.
ARG_TYPE_JSON
const pocketmine\network\mcpe\protocol\AvailableCommandsPacket::ARG_TYPE_JSON = 0x39
Definition at line 64 of file AvailableCommandsPacket.php.
ARG_TYPE_MESSAGE
const pocketmine\network\mcpe\protocol\AvailableCommandsPacket::ARG_TYPE_MESSAGE = 0x33
Definition at line 60 of file AvailableCommandsPacket.php.
ARG_TYPE_OPERATOR
const pocketmine\network\mcpe\protocol\AvailableCommandsPacket::ARG_TYPE_OPERATOR = 0x06
Definition at line 44 of file AvailableCommandsPacket.php.
ARG_TYPE_POSITION
const pocketmine\network\mcpe\protocol\AvailableCommandsPacket::ARG_TYPE_POSITION = 0x30
Definition at line 58 of file AvailableCommandsPacket.php.
ARG_TYPE_RAWTEXT
const pocketmine\network\mcpe\protocol\AvailableCommandsPacket::ARG_TYPE_RAWTEXT = 0x35
Definition at line 62 of file AvailableCommandsPacket.php.
ARG_TYPE_STRING
const pocketmine\network\mcpe\protocol\AvailableCommandsPacket::ARG_TYPE_STRING = 0x27
Definition at line 55 of file AvailableCommandsPacket.php.
ARG_TYPE_TARGET
const pocketmine\network\mcpe\protocol\AvailableCommandsPacket::ARG_TYPE_TARGET = 0x08
Definition at line 46 of file AvailableCommandsPacket.php.
ARG_TYPE_VALUE
const pocketmine\network\mcpe\protocol\AvailableCommandsPacket::ARG_TYPE_VALUE = 0x04
Definition at line 42 of file AvailableCommandsPacket.php.
ARG_TYPE_WILDCARD_INT
const pocketmine\network\mcpe\protocol\AvailableCommandsPacket::ARG_TYPE_WILDCARD_INT = 0x05
Definition at line 43 of file AvailableCommandsPacket.php.
ARG_TYPE_WILDCARD_TARGET
const pocketmine\network\mcpe\protocol\AvailableCommandsPacket::ARG_TYPE_WILDCARD_TARGET = 0x0a
Definition at line 48 of file AvailableCommandsPacket.php.
HARDCODED_ENUM_NAMES
const pocketmine\network\mcpe\protocol\AvailableCommandsPacket::HARDCODED_ENUM_NAMES
Initial value:
= [
        "CommandName" => true
    ]
Definition at line 79 of file AvailableCommandsPacket.php.
NETWORK_ID
const pocketmine\network\mcpe\protocol\AvailableCommandsPacket::NETWORK_ID = ProtocolInfo::AVAILABLE_COMMANDS_PACKET
Definition at line 28 of file AvailableCommandsPacket.php.
PID_MASK
const pocketmine\network\mcpe\protocol\DataPacket::PID_MASK = 0x3ff inherited
Definition at line 25 of file DataPacket.php.
The documentation for this class was generated from the following file:
AvailableCommandsPacket.php