PocketMine-MP: pocketmine\entity\object\Painting Class Reference
pocketmine\entity\object\Painting Class Reference
Public Member Functions
__construct (Location $location, Vector3 $blockIn, int $facing, PaintingMotive $motive, ?CompoundTag $nbt=null)
__toString ()
addMotion (float $x, float $y, float $z)
attack (EntityDamageEvent $source)
broadcastAnimation (Animation $animation, ?array $targets=null)
broadcastSound (Sound $sound, ?array $targets=null)
canBeCollidedWith ()
canBeMovedByCurrents ()
canBeRenamed ()
canClimb ()
canClimbWalls ()
canCollideWith (Entity $entity)
canSaveWithChunk ()
close ()
despawnFrom (Player $player, bool $send=true)
despawnFromAll ()
extinguish (int $cause=EntityExtinguishEvent::CAUSE_CUSTOM)
flagForDespawn ()
getAttributeMap ()
getBoundingBox ()
getDirectionPlane ()
getDirectionVector ()
getEyeHeight ()
getEyePos ()
getFacing ()
getFallDistance ()
getFireTicks ()
getGravity ()
getHealth ()
getHorizontalFacing ()
getId ()
getLastDamageCause ()
getLocation ()
getMaxHealth ()
getMotion ()
getMotive ()
getNameTag ()
getNetworkProperties ()
getOffsetPosition (Vector3 $vector3)
getOwningEntity ()
getOwningEntityId ()
getPickedItem ()
getPosition ()
getScale ()
getScoreTag ()
getSize ()
getStepHeight ()
getTargetEntity ()
getTargetEntityId ()
getViewers ()
getWorld ()
hasGravity ()
hasMovementUpdate ()
hasNoClientPredictions ()
heal (EntityRegainHealthEvent $source)
isAlive ()
isClosed ()
isFireProof ()
isFlaggedForDespawn ()
isInsideOfSolid ()
isInvisible ()
isNameTagAlwaysVisible ()
isNameTagVisible ()
isOnFire ()
isOnGround ()
isSilent ()
isUnderwater ()
kill ()
onCollideWithPlayer (Player $player)
onInteract (Player $player, Vector3 $clickPos)
onNearbyBlockChange ()
onRandomUpdate ()
onUpdate (int $currentTick)
resetFallDistance ()
respawnToAll ()
saveNBT ()
scheduleUpdate ()
sendData (?array $targets, ?array $data=null)
setCanClimb (bool $value=true)
setCanClimbWalls (bool $value=true)
setCanSaveWithChunk (bool $value)
setFallDistance (float $fallDistance)
setFireTicks (int $fireTicks)
setForceMovementUpdate (bool $value=true)
setGravity (float $gravity)
setHasGravity (bool $v=true)
setHealth (float $amount)
setInvisible (bool $value=true)
setLastDamageCause (EntityDamageEvent $type)
setMaxHealth (int $amount)
setMotion (Vector3 $motion)
setNameTag (string $name)
setNameTagAlwaysVisible (bool $value=true)
setNameTagVisible (bool $value=true)
setNoClientPredictions (bool $value=true)
setOnFire (int $seconds)
setOwningEntity (?Entity $owner)
setRotation (float $yaw, float $pitch)
setScale (float $value)
setScoreTag (string $score)
setSilent (bool $value=true)
setStepHeight (float $stepHeight)
setTargetEntity (?Entity $target)
spawnTo (Player $player)
spawnToAll ()
teleport (Vector3 $pos, ?float $yaw=null, ?float $pitch=null)
Static Public Member Functions
static canFit (World $world, Vector3 $blockIn, int $facing, bool $checkOverlap, PaintingMotive $motive)
static getNetworkTypeId ()
static nextRuntimeId ()
Public Attributes
AxisAlignedBB $boundingBox
float $fallDistance = 0.0
bool $isCollided = false
bool $isCollidedHorizontally = false
bool $isCollidedVertically = false
bool $keepMovement = false
int $lastUpdate
int $noDamageTicks = 0
bool $onGround = false
EntitySizeInfo $size
int $ticksLived = 0
const DATA_TO_FACING
const MOTION_THRESHOLD = 0.00001
const TAG_DIRECTION_BE = "Direction"
const TAG_FACING_JE = "Facing"
const TAG_MOTION = "Motion"
const TAG_MOTIVE = "Motive"
const TAG_POS = "Pos"
const TAG_ROTATION = "Rotation"
const TAG_TILE_X = "TileX"
const TAG_TILE_Y = "TileY"
const TAG_TILE_Z = "TileZ"
Protected Member Functions
addAttributes ()
applyDragBeforeGravity ()
broadcastMotion ()
broadcastMovement (bool $teleport=false)
checkBlockIntersections ()
checkGroundState (float $wantedX, float $wantedY, float $wantedZ, float $dx, float $dy, float $dz)
checkObstruction (float $x, float $y, float $z)
dealFireDamage ()
destroyCycles ()
doOnFireTick (int $tickDiff=1)
entityBaseTick (int $tickDiff=1)
getAllNetworkData ()
getBlocksAroundWithEntityInsideActions ()
getBlocksIntersected (float $inset)
getDirtyNetworkData ()
getInitialDragMultiplier ()
getInitialGravity ()
getInitialSizeInfo ()
initEntity (CompoundTag $nbt)
move (float $dx, float $dy, float $dz)
onDeath ()
onDeathUpdate (int $tickDiff)
onDispose ()
onFirstUpdate (int $currentTick)
onHitGround ()
recalculateBoundingBox ()
resetLastMovements ()
sendSpawnPacket (Player $player)
setPosition (Vector3 $pos)
setPositionAndRotation (Vector3 $pos, float $yaw, float $pitch)
setSize (EntitySizeInfo $size)
syncNetworkData (EntityMetadataCollection $properties)
tryChangeMovement ()
updateFallState (float $distanceThisTick, bool $onGround)
updateMovement (bool $teleport=false)
Protected Attributes
bool $alwaysShowNameTag = false
AttributeMap $attributeMap
Vector3 $blockIn
array $blocksAround = null
bool $canClimb = false
bool $canClimbWalls = false
bool $closed = false
float $drag
int $facing
int $fireTicks = 0
bool $forceMovementUpdate = false
float $gravity
bool $gravityEnabled = true
array $hasSpawned = []
int $id
bool $invisible = false
bool $justCreated = true
EntityDamageEvent $lastDamageCause = null
Location $lastLocation
Vector3 $lastMotion
Location $location
Vector3 $motion
PaintingMotive $motive
string $nameTag = ""
bool $nameTagVisible = true
bool $networkPropertiesDirty = false
bool $noClientPredictions = false
int $ownerId = null
float $scale = 1.0
string $scoreTag = ""
Server $server
bool $silent = false
float $stepHeight = 0.0
int $targetId = null
TimingsHandler $timings
float $ySize = 0.0
const STEP_CLIP_MULTIPLIER = 0.4
Detailed Description
Definition at line 44 of file Painting.php.
Constructor & Destructor Documentation
__construct()
pocketmine\entity\object\Painting::__construct (Location $location, Vector3 $blockIn, int $facing, PaintingMotive $motive, ?CompoundTag $nbt = null)
Definition at line 71 of file Painting.php.
Member Function Documentation
__toString()
pocketmine\entity\Entity::__toString () inherited
Definition at line 1739 of file Entity.php.
addAttributes()
pocketmine\entity\Entity::addAttributes () protected inherited
Definition at line 532 of file Entity.php.
addMotion()
pocketmine\entity\Entity::addMotion (float $x, float $y, float $z) inherited
Adds the given values to the entity's motion vector.
Definition at line 1450 of file Entity.php.
Referenced by pocketmine\entity\effect\LevitationEffect\applyEffect().
applyDragBeforeGravity()
pocketmine\entity\Entity::applyDragBeforeGravity () protected inherited
Definition at line 840 of file Entity.php.
attack()
pocketmine\entity\Entity::attack (EntityDamageEvent $source) inherited
Definition at line 536 of file Entity.php.
broadcastAnimation()
pocketmine\entity\Entity::broadcastAnimation (Animation $animation, ?array $targets = null) inherited
Parameters
Player[] | null $targets
Reimplemented in pocketmine\player\Player.
Definition at line 1721 of file Entity.php.
broadcastMotion()
pocketmine\entity\Entity::broadcastMotion () protected inherited
Definition at line 819 of file Entity.php.
broadcastMovement()
pocketmine\entity\Entity::broadcastMovement (bool $teleport = false) protected inherited
Definition at line 801 of file Entity.php.
broadcastSound()
pocketmine\entity\Entity::broadcastSound (Sound $sound, ?array $targets = null) inherited
Broadcasts a sound caused by the entity. If the entity is considered "silent", the sound will be dropped.
Parameters
Player[] | null $targets
Reimplemented in pocketmine\player\Player.
Definition at line 1729 of file Entity.php.
canBeCollidedWith()
pocketmine\entity\object\Painting::canBeCollidedWith ()
Reimplemented from pocketmine\entity\Entity.
Definition at line 151 of file Painting.php.
canBeMovedByCurrents()
pocketmine\entity\Entity::canBeMovedByCurrents () inherited
Returns whether this entity can be moved by currents in liquids.
Reimplemented in pocketmine\entity\object\FallingBlock, and pocketmine\player\Player.
Definition at line 1331 of file Entity.php.
canBeRenamed()
pocketmine\entity\Entity::canBeRenamed () inherited
Returns whether players can rename this entity using a name tag. Note that plugins can still name entities using setNameTag().
Reimplemented in pocketmine\entity\Living, and pocketmine\player\Player.
Definition at line 266 of file Entity.php.
canClimb()
pocketmine\entity\Entity::canClimb () inherited
Returns whether the entity is able to climb blocks such as ladders or vines.
Definition at line 375 of file Entity.php.
canClimbWalls()
pocketmine\entity\Entity::canClimbWalls () inherited
Returns whether this entity is climbing a block. By default this is only true if the entity is climbing a ladder or vine or similar block.
Definition at line 390 of file Entity.php.
canCollideWith()
pocketmine\entity\Entity::canCollideWith (Entity $entity) inherited
Definition at line 763 of file Entity.php.
canFit()
static pocketmine\entity\object\Painting::canFit (World $world, Vector3 $blockIn, int $facing, bool $checkOverlap, PaintingMotive $motive) static
Returns whether a painting with the specified motive can be placed at the given position.
Definition at line 205 of file Painting.php.
canSaveWithChunk()
pocketmine\entity\Entity::canSaveWithChunk () inherited
Returns whether this entity will be saved when its chunk is unloaded.
Reimplemented in pocketmine\entity\object\ItemEntity, and pocketmine\player\Player.
Definition at line 466 of file Entity.php.
checkBlockIntersections()
pocketmine\entity\Entity::checkBlockIntersections () protected inherited
Definition at line 1335 of file Entity.php.
checkGroundState()
pocketmine\entity\Entity::checkGroundState (float $wantedX, float $wantedY, float $wantedZ, float $dx, float $dy, float $dz) protected inherited
Definition at line 1279 of file Entity.php.
checkObstruction()
pocketmine\entity\Entity::checkObstruction (float $x, float $y, float $z) protected inherited
Definition at line 868 of file Entity.php.
close()
pocketmine\entity\Entity::close () final inherited
Closes the entity and frees attached references.
WARNING: Entities are unusable after this has been executed!
Definition at line 1621 of file Entity.php.
dealFireDamage()
pocketmine\entity\Entity::dealFireDamage () protected inherited
Called to deal damage to entities when they are on fire.
Definition at line 758 of file Entity.php.
despawnFrom()
pocketmine\entity\Entity::despawnFrom (Player $player, bool $send = true) inherited
Deprecated
WARNING: This function DOES NOT permanently hide the entity from the player. As soon as the entity or player moves, the player will once again be able to see the entity.
Definition at line 1568 of file Entity.php.
despawnFromAll()
pocketmine\entity\Entity::despawnFromAll () inherited
Deprecated
WARNING: This function DOES NOT permanently hide the entity from viewers. As soon as the entity or player moves, viewers will once again be able to see the entity.
Definition at line 1582 of file Entity.php.
destroyCycles()
pocketmine\entity\Entity::destroyCycles () protected inherited
Called when the entity is disposed, after all events have been fired. This should be used to perform destructive circular object references and things which could impact memory usage.
It is expected that the object is unusable after this is called.
Reimplemented in pocketmine\entity\Human, pocketmine\entity\Living, and pocketmine\player\Player.
Definition at line 1654 of file Entity.php.
doOnFireTick()
pocketmine\entity\Entity::doOnFireTick (int $tickDiff = 1) protected inherited
Definition at line 734 of file Entity.php.
entityBaseTick()
pocketmine\entity\Entity::entityBaseTick (int $tickDiff = 1) protected inherited
Definition at line 641 of file Entity.php.
extinguish()
pocketmine\entity\Entity::extinguish (int $cause = EntityExtinguishEvent::CAUSE_CUSTOM) inherited
Definition at line 722 of file Entity.php.
flagForDespawn()
pocketmine\entity\Entity::flagForDespawn () inherited
Flags the entity to be removed from the world on the next tick.
Definition at line 1600 of file Entity.php.
getAllNetworkData()
pocketmine\entity\Entity::getAllNetworkData () final protected inherited
Returns
MetadataProperty[] @phpstan-return array<int, MetadataProperty>
Definition at line 1687 of file Entity.php.
getAttributeMap()
pocketmine\entity\Entity::getAttributeMap () inherited
Definition at line 633 of file Entity.php.
getBlocksAroundWithEntityInsideActions()
pocketmine\entity\Entity::getBlocksAroundWithEntityInsideActions () protected inherited
Returns
Block[]
Definition at line 1313 of file Entity.php.
getBlocksIntersected()
pocketmine\entity\Entity::getBlocksIntersected (float $inset) protected inherited
Yields all the blocks whose full-cube areas are intersected by the entity's AABB.
@phpstan-return \Generator<int, Block, void, void>
Definition at line 1291 of file Entity.php.
getBoundingBox()
pocketmine\entity\Entity::getBoundingBox () inherited
Definition at line 306 of file Entity.php.
getDirectionPlane()
pocketmine\entity\Entity::getDirectionPlane () inherited
Definition at line 970 of file Entity.php.
getDirectionVector()
pocketmine\entity\Entity::getDirectionVector () inherited
Definition at line 961 of file Entity.php.
getDirtyNetworkData()
pocketmine\entity\Entity::getDirtyNetworkData () final protected inherited
Returns
MetadataProperty[] @phpstan-return array<int, MetadataProperty>
Definition at line 1675 of file Entity.php.
getEyeHeight()
pocketmine\entity\Entity::getEyeHeight () inherited
Definition at line 1117 of file Entity.php.
getEyePos()
pocketmine\entity\Entity::getEyePos () inherited
Definition at line 1121 of file Entity.php.
getFacing()
pocketmine\entity\object\Painting::getFacing ()
Definition at line 180 of file Painting.php.
getFallDistance()
pocketmine\entity\Entity::getFallDistance () inherited
Definition at line 1082 of file Entity.php.
getFireTicks()
pocketmine\entity\Entity::getFireTicks () inherited
Definition at line 698 of file Entity.php.
getGravity()
pocketmine\entity\Entity::getGravity () inherited
Definition at line 823 of file Entity.php.
getHealth()
pocketmine\entity\Entity::getHealth () inherited
Definition at line 590 of file Entity.php.
getHorizontalFacing()
pocketmine\entity\Entity::getHorizontalFacing () inherited
Definition at line 942 of file Entity.php.
getId()
pocketmine\entity\Entity::getId () inherited
Definition at line 1500 of file Entity.php.
getInitialDragMultiplier()
pocketmine\entity\object\Painting::getInitialDragMultiplier () protected
Returns the percentage by which the entity's velocity is reduced per tick when moving through air. The entity's velocity is multiplied by 1 minus this value.
Returns
float 0-1
Reimplemented from pocketmine\entity\Entity.
Definition at line 83 of file Painting.php.
getInitialGravity()
pocketmine\entity\object\Painting::getInitialGravity () protected
Returns the downwards acceleration of the entity when falling, in blocks/tick.
Returns
float minimum 0
Reimplemented from pocketmine\entity\Entity.
Definition at line 85 of file Painting.php.
getInitialSizeInfo()
pocketmine\entity\object\Painting::getInitialSizeInfo () protected
Reimplemented from pocketmine\entity\Entity.
Definition at line 78 of file Painting.php.
getLastDamageCause()
pocketmine\entity\Entity::getLastDamageCause () inherited
Definition at line 629 of file Entity.php.
getLocation()
pocketmine\entity\Entity::getLocation () inherited
Definition at line 1361 of file Entity.php.
getMaxHealth()
pocketmine\entity\Entity::getMaxHealth () inherited
Definition at line 617 of file Entity.php.
getMotion()
pocketmine\entity\Entity::getMotion () inherited
Definition at line 1424 of file Entity.php.
getMotive()
pocketmine\entity\object\Painting::getMotive ()
Returns the painting motive (which image is displayed on the painting)
Definition at line 176 of file Painting.php.
getNameTag()
pocketmine\entity\Entity::getNameTag () inherited
Definition at line 250 of file Entity.php.
getNetworkProperties()
pocketmine\entity\Entity::getNetworkProperties () inherited
Definition at line 637 of file Entity.php.
getNetworkTypeId()
static pocketmine\entity\object\Painting::getNetworkTypeId () static
Reimplemented from pocketmine\entity\Entity.
Definition at line 52 of file Painting.php.
getOffsetPosition()
pocketmine\entity\Entity::getOffsetPosition (Vector3 $vector3) inherited
Definition at line 797 of file Entity.php.
getOwningEntity()
pocketmine\entity\Entity::getOwningEntity () inherited
Returns the owning entity, or null if the entity was not found.
Definition at line 412 of file Entity.php.
References pocketmine\server().
getOwningEntityId()
pocketmine\entity\Entity::getOwningEntityId () inherited
Returns the entity ID of the owning entity, or null if the entity doesn't have an owner.
Definition at line 405 of file Entity.php.
getPickedItem()
pocketmine\entity\object\Painting::getPickedItem ()
Returns the item that players will equip when middle-clicking on this entity.
Reimplemented from pocketmine\entity\Entity.
Definition at line 169 of file Painting.php.
getPosition()
pocketmine\entity\Entity::getPosition () inherited
Definition at line 1357 of file Entity.php.
getScale()
pocketmine\entity\Entity::getScale () inherited
Definition at line 294 of file Entity.php.
getScoreTag()
pocketmine\entity\Entity::getScoreTag () inherited
Definition at line 285 of file Entity.php.
getSize()
pocketmine\entity\Entity::getSize () inherited
Definition at line 323 of file Entity.php.
getStepHeight()
pocketmine\entity\Entity::getStepHeight () inherited
Definition at line 1275 of file Entity.php.
getTargetEntity()
pocketmine\entity\Entity::getTargetEntity () inherited
Returns the entity's target entity, or null if not found. This is used for things like hostile mobs attacking entities, and for fishing rods reeling hit entities in.
Definition at line 443 of file Entity.php.
References pocketmine\server().
getTargetEntityId()
pocketmine\entity\Entity::getTargetEntityId () inherited
Returns the entity ID of the entity's target, or null if it doesn't have a target.
Definition at line 435 of file Entity.php.
getViewers()
pocketmine\entity\Entity::getViewers () inherited
Returns
Player[]
Definition at line 1507 of file Entity.php.
getWorld()
pocketmine\entity\Entity::getWorld () inherited
Definition at line 1365 of file Entity.php.
hasGravity()
pocketmine\entity\Entity::hasGravity () inherited
Definition at line 832 of file Entity.php.
hasMovementUpdate()
pocketmine\entity\object\Painting::hasMovementUpdate ()
Returns whether the entity needs a movement update on the next tick.
Reimplemented from pocketmine\entity\Entity.
Definition at line 143 of file Painting.php.
hasNoClientPredictions()
pocketmine\entity\Entity::hasNoClientPredictions () inherited
Returns whether clients may predict this entity's behaviour and movement. Used for things like water movement, burning, and movement smoothing (interpolation).
Definition at line 337 of file Entity.php.
heal()
pocketmine\entity\Entity::heal (EntityRegainHealthEvent $source) inherited
Definition at line 555 of file Entity.php.
initEntity()
pocketmine\entity\object\Painting::initEntity (CompoundTag $nbt) protected
Reimplemented from pocketmine\entity\Entity.
Definition at line 87 of file Painting.php.
isAlive()
pocketmine\entity\Entity::isAlive () inherited
Definition at line 586 of file Entity.php.
isClosed()
pocketmine\entity\Entity::isClosed () inherited
Returns whether the entity has been "closed".
Definition at line 1612 of file Entity.php.
isFireProof()
pocketmine\entity\Entity::isFireProof () inherited
Definition at line 730 of file Entity.php.
isFlaggedForDespawn()
pocketmine\entity\Entity::isFlaggedForDespawn () inherited
Definition at line 1605 of file Entity.php.
isInsideOfSolid()
pocketmine\entity\Entity::isInsideOfSolid () inherited
Definition at line 1147 of file Entity.php.
isInvisible()
pocketmine\entity\Entity::isInvisible () inherited
Definition at line 354 of file Entity.php.
isNameTagAlwaysVisible()
pocketmine\entity\Entity::isNameTagAlwaysVisible () inherited
Definition at line 258 of file Entity.php.
isNameTagVisible()
pocketmine\entity\Entity::isNameTagVisible () inherited
Definition at line 254 of file Entity.php.
isOnFire()
pocketmine\entity\Entity::isOnFire () inherited
Definition at line 686 of file Entity.php.
isOnGround()
pocketmine\entity\Entity::isOnGround () inherited
Definition at line 1457 of file Entity.php.
isSilent()
pocketmine\entity\Entity::isSilent () inherited
Definition at line 363 of file Entity.php.
isUnderwater()
pocketmine\entity\Entity::isUnderwater () inherited
Definition at line 1136 of file Entity.php.
kill()
pocketmine\entity\Entity::kill () inherited
Definition at line 564 of file Entity.php.
move()
pocketmine\entity\Entity::move (float $dx, float $dy, float $dz) protected inherited
Definition at line 1153 of file Entity.php.
nextRuntimeId()
static pocketmine\entity\Entity::nextRuntimeId () static inherited
Returns a new runtime entity ID for a new entity.
Definition at line 105 of file Entity.php.
onCollideWithPlayer()
pocketmine\entity\Entity::onCollideWithPlayer (Player $player) inherited
Definition at line 1125 of file Entity.php.
onDeath()
pocketmine\entity\object\Painting::onDeath () protected
Override this to do actions on death.
Reimplemented from pocketmine\entity\Entity.
Definition at line 107 of file Painting.php.
References pocketmine\player\Player\hasFiniteResources().
onDeathUpdate()
pocketmine\entity\Entity::onDeathUpdate (int $tickDiff) protected inherited
Called to tick entities while dead. Returns whether the entity should be flagged for despawn yet.
Reimplemented in pocketmine\entity\Living, pocketmine\entity\object\EndCrystal, and pocketmine\player\Player.
Definition at line 582 of file Entity.php.
onDispose()
pocketmine\entity\Entity::onDispose () protected inherited
Called when the entity is disposed to clean up things like viewers. This SHOULD NOT destroy internal state, because it may be needed by descendent classes.
Reimplemented in pocketmine\entity\Human, pocketmine\entity\Living, and pocketmine\player\Player.
Definition at line 1641 of file Entity.php.
onFirstUpdate()
pocketmine\entity\Entity::onFirstUpdate (int $currentTick) protected inherited
Called from onUpdate() on the first tick of a new entity. This is called before any movement processing or main ticking logic. Use this to fire any events related to spawning the entity.
Reimplemented in pocketmine\entity\object\FireworkRocket, pocketmine\entity\object\ItemEntity, and pocketmine\entity\projectile\Trident.
Definition at line 978 of file Entity.php.
onHitGround()
pocketmine\entity\Entity::onHitGround () protected inherited
Called when a falling entity hits the ground.
Reimplemented in pocketmine\entity\Living, and pocketmine\entity\object\FallingBlock.
Definition at line 1113 of file Entity.php.
onInteract()
pocketmine\entity\Entity::onInteract (Player $player, Vector3 $clickPos) inherited
Called when interacted or tapped by a Player. Returns whether something happened as a result of the interaction.
Definition at line 1132 of file Entity.php.
onNearbyBlockChange()
pocketmine\entity\object\Painting::onNearbyBlockChange ()
Reimplemented from pocketmine\entity\Entity.
Definition at line 131 of file Painting.php.
onRandomUpdate()
pocketmine\entity\object\Painting::onRandomUpdate ()
Called when a random update is performed on the chunk the entity is in. This happens when the chunk is within the ticking chunk range of a player (or chunk loader).
Reimplemented from pocketmine\entity\Entity.
Definition at line 139 of file Painting.php.
onUpdate()
pocketmine\entity\Entity::onUpdate (int $currentTick) inherited
Definition at line 982 of file Entity.php.
recalculateBoundingBox()
pocketmine\entity\object\Painting::recalculateBoundingBox () protected
Reimplemented from pocketmine\entity\Entity.
Definition at line 126 of file Painting.php.
resetFallDistance()
pocketmine\entity\Entity::resetFallDistance () inherited
Definition at line 1088 of file Entity.php.
resetLastMovements()
pocketmine\entity\Entity::resetLastMovements () protected inherited
Definition at line 1419 of file Entity.php.
respawnToAll()
pocketmine\entity\Entity::respawnToAll () inherited
Definition at line 1557 of file Entity.php.
saveNBT()
pocketmine\entity\object\Painting::saveNBT ()
Reimplemented from pocketmine\entity\Entity.
Definition at line 93 of file Painting.php.
scheduleUpdate()
pocketmine\entity\Entity::scheduleUpdate () final inherited
Definition at line 1039 of file Entity.php.
sendData()
pocketmine\entity\Entity::sendData (?array $targets, ?array $data = null) inherited
Parameters
Player[] | null $targets
MetadataProperty[] $data Properly formatted entity data, defaults to everything
@phpstan-param array<int, MetadataProperty> $data
Reimplemented in pocketmine\player\Player.
Definition at line 1664 of file Entity.php.
sendSpawnPacket()
pocketmine\entity\object\Painting::sendSpawnPacket (Player $player) protected
Called by spawnTo() to send whatever packets needed to spawn the entity to the client.
Reimplemented from pocketmine\entity\Entity.
Definition at line 155 of file Painting.php.
setCanClimb()
pocketmine\entity\Entity::setCanClimb (bool $value = true) inherited
Sets whether the entity is able to climb climbable blocks.
Definition at line 382 of file Entity.php.
setCanClimbWalls()
pocketmine\entity\Entity::setCanClimbWalls (bool $value = true) inherited
Sets whether the entity is climbing a block. If true, the entity can climb anything.
Definition at line 397 of file Entity.php.
setCanSaveWithChunk()
pocketmine\entity\Entity::setCanSaveWithChunk (bool $value) inherited
Sets whether this entity will be saved when its chunk is unloaded. This can be used to prevent the entity being saved to disk.
Reimplemented in pocketmine\player\Player.
Definition at line 474 of file Entity.php.
setFallDistance()
pocketmine\entity\Entity::setFallDistance (float $fallDistance) inherited
Definition at line 1084 of file Entity.php.
setFireTicks()
pocketmine\entity\Entity::setFireTicks (int $fireTicks) inherited
Exceptions
InvalidArgumentException
Definition at line 705 of file Entity.php.
setForceMovementUpdate()
pocketmine\entity\Entity::setForceMovementUpdate (bool $value = true) final inherited
Flags the entity as needing a movement update on the next tick. Setting this forces a movement update even if the entity's motion is zero. Used to trigger movement updates when blocks change near entities.
Definition at line 1063 of file Entity.php.
setGravity()
pocketmine\entity\Entity::setGravity (float $gravity) inherited
Definition at line 827 of file Entity.php.
setHasGravity()
pocketmine\entity\Entity::setHasGravity (bool $v = true) inherited
Definition at line 836 of file Entity.php.
setHealth()
pocketmine\entity\Entity::setHealth (float $amount) inherited
Sets the health of the Entity. This won't send any update to the players
Reimplemented in pocketmine\entity\Living.
Definition at line 597 of file Entity.php.
setInvisible()
pocketmine\entity\Entity::setInvisible (bool $value = true) inherited
Definition at line 358 of file Entity.php.
setLastDamageCause()
pocketmine\entity\Entity::setLastDamageCause (EntityDamageEvent $type) inherited
Definition at line 625 of file Entity.php.
setMaxHealth()
pocketmine\entity\Entity::setMaxHealth (int $amount) inherited
Definition at line 621 of file Entity.php.
setMotion()
pocketmine\entity\Entity::setMotion (Vector3 $motion) inherited
Definition at line 1428 of file Entity.php.
setNameTag()
pocketmine\entity\Entity::setNameTag (string $name) inherited
Definition at line 270 of file Entity.php.
setNameTagAlwaysVisible()
pocketmine\entity\Entity::setNameTagAlwaysVisible (bool $value = true) inherited
Definition at line 280 of file Entity.php.
setNameTagVisible()
pocketmine\entity\Entity::setNameTagVisible (bool $value = true) inherited
Definition at line 275 of file Entity.php.
setNoClientPredictions()
pocketmine\entity\Entity::setNoClientPredictions (bool $value = true) inherited
Things such as movement in water, burning, etc. may be predicted by the client. This is sometimes not desirable, since server-side logic may differ from client-side prediction. However, things like movement smoothing (interpolation) are also controlled by this, so it should be used with care.
Setting this flag will also disable player movement inputs, but this should not be relied on, as cheat clients will be able to bypass it.
Definition at line 349 of file Entity.php.
setOnFire()
pocketmine\entity\Entity::setOnFire (int $seconds) inherited
Definition at line 690 of file Entity.php.
setOwningEntity()
pocketmine\entity\Entity::setOwningEntity (?Entity $owner) inherited
Sets the owner of the entity. Passing null will remove the current owner.
Exceptions
InvalidArgumentException if the supplied entity is not valid
Definition at line 421 of file Entity.php.
setPosition()
pocketmine\entity\Entity::setPosition (Vector3 $pos) protected inherited
Definition at line 1369 of file Entity.php.
setPositionAndRotation()
pocketmine\entity\Entity::setPositionAndRotation (Vector3 $pos, float $yaw, float $pitch) protected inherited
Definition at line 1409 of file Entity.php.
setRotation()
pocketmine\entity\Entity::setRotation (float $yaw, float $pitch) inherited
Definition at line 1401 of file Entity.php.
setScale()
pocketmine\entity\Entity::setScale (float $value) inherited
Definition at line 298 of file Entity.php.
setScoreTag()
pocketmine\entity\Entity::setScoreTag (string $score) inherited
Definition at line 289 of file Entity.php.
setSilent()
pocketmine\entity\Entity::setSilent (bool $value = true) inherited
Definition at line 367 of file Entity.php.
setSize()
pocketmine\entity\Entity::setSize (EntitySizeInfo $size) protected inherited
Definition at line 327 of file Entity.php.
setStepHeight()
pocketmine\entity\Entity::setStepHeight (float $stepHeight) inherited
Definition at line 1271 of file Entity.php.
setTargetEntity()
pocketmine\entity\Entity::setTargetEntity (?Entity $target) inherited
Sets the entity's target entity. Passing null will remove the current target.
Exceptions
InvalidArgumentException if the target entity is not valid
Definition at line 452 of file Entity.php.
spawnTo()
pocketmine\entity\Entity::spawnTo (Player $player) inherited
Definition at line 1536 of file Entity.php.
spawnToAll()
pocketmine\entity\Entity::spawnToAll () inherited
Definition at line 1548 of file Entity.php.
syncNetworkData()
pocketmine\entity\Entity::syncNetworkData (EntityMetadataCollection $properties) protected inherited
Definition at line 1695 of file Entity.php.
teleport()
pocketmine\entity\Entity::teleport (Vector3 $pos, ?float $yaw = null, ?float $pitch = null) inherited
Parameters
Vector3 | Position | Location $pos
Reimplemented in pocketmine\player\Player.
Definition at line 1464 of file Entity.php.
Referenced by pocketmine\item\ChorusFruit\onConsume().
tryChangeMovement()
pocketmine\entity\Entity::tryChangeMovement () protected inherited
Definition at line 844 of file Entity.php.
updateFallState()
pocketmine\entity\Entity::updateFallState (float $distanceThisTick, bool $onGround) protected inherited
Definition at line 1092 of file Entity.php.
updateMovement()
pocketmine\entity\object\Painting::updateMovement (bool $teleport = false) protected
Reimplemented from pocketmine\entity\Entity.
Definition at line 147 of file Painting.php.
Member Data Documentation
$alwaysShowNameTag
bool pocketmine\entity\Entity::$alwaysShowNameTag = false protected inherited
Definition at line 175 of file Entity.php.
$attributeMap
AttributeMap pocketmine\entity\Entity::$attributeMap protected inherited
Definition at line 157 of file Entity.php.
$blockIn
Vector3 pocketmine\entity\object\Painting::$blockIn protected
Definition at line 67 of file Painting.php.
$blocksAround
array pocketmine\entity\Entity::$blocksAround = null protected inherited
Definition at line 122 of file Entity.php.
$boundingBox
AxisAlignedBB pocketmine\entity\Entity::$boundingBox inherited
Definition at line 131 of file Entity.php.
$canClimb
bool pocketmine\entity\Entity::$canClimb = false protected inherited
Definition at line 179 of file Entity.php.
$canClimbWalls
bool pocketmine\entity\Entity::$canClimbWalls = false protected inherited
Definition at line 180 of file Entity.php.
$closed
bool pocketmine\entity\Entity::$closed = false protected inherited
Definition at line 165 of file Entity.php.
$drag
float pocketmine\entity\Entity::$drag protected inherited
Definition at line 160 of file Entity.php.
$facing
int pocketmine\entity\object\Painting::$facing protected
Definition at line 68 of file Painting.php.
$fallDistance
float pocketmine\entity\Entity::$fallDistance = 0.0 inherited
Definition at line 143 of file Entity.php.
$fireTicks
int pocketmine\entity\Entity::$fireTicks = 0 protected inherited
Definition at line 146 of file Entity.php.
$forceMovementUpdate
bool pocketmine\entity\Entity::$forceMovementUpdate = false protected inherited
Definition at line 128 of file Entity.php.
$gravity
float pocketmine\entity\Entity::$gravity protected inherited
Definition at line 159 of file Entity.php.
$gravityEnabled
bool pocketmine\entity\Entity::$gravityEnabled = true protected inherited
Definition at line 161 of file Entity.php.
$hasSpawned
array pocketmine\entity\Entity::$hasSpawned = [] protected inherited
Definition at line 113 of file Entity.php.
$id
int pocketmine\entity\Entity::$id protected inherited
Definition at line 115 of file Entity.php.
$invisible
bool pocketmine\entity\Entity::$invisible = false protected inherited
Definition at line 182 of file Entity.php.
$isCollided
bool pocketmine\entity\Entity::$isCollided = false inherited
Definition at line 150 of file Entity.php.
$isCollidedHorizontally
bool pocketmine\entity\Entity::$isCollidedHorizontally = false inherited
Definition at line 151 of file Entity.php.
$isCollidedVertically
bool pocketmine\entity\Entity::$isCollidedVertically = false inherited
Definition at line 152 of file Entity.php.
$justCreated
bool pocketmine\entity\Entity::$justCreated = true protected inherited
Definition at line 155 of file Entity.php.
$keepMovement
bool pocketmine\entity\Entity::$keepMovement = false inherited
Definition at line 141 of file Entity.php.
$lastDamageCause
EntityDamageEvent pocketmine\entity\Entity::$lastDamageCause = null protected inherited
Definition at line 119 of file Entity.php.
$lastLocation
Location pocketmine\entity\Entity::$lastLocation protected inherited
Definition at line 125 of file Entity.php.
$lastMotion
Vector3 pocketmine\entity\Entity::$lastMotion protected inherited
Definition at line 127 of file Entity.php.
$lastUpdate
int pocketmine\entity\Entity::$lastUpdate inherited
Definition at line 145 of file Entity.php.
$location
Location pocketmine\entity\Entity::$location protected inherited
Definition at line 124 of file Entity.php.
$motion
Vector3 pocketmine\entity\Entity::$motion protected inherited
Definition at line 126 of file Entity.php.
$motive
PaintingMotive pocketmine\entity\object\Painting::$motive protected
Definition at line 69 of file Painting.php.
$nameTag
string pocketmine\entity\Entity::$nameTag = "" protected inherited
Definition at line 173 of file Entity.php.
$nameTagVisible
bool pocketmine\entity\Entity::$nameTagVisible = true protected inherited
Definition at line 174 of file Entity.php.
$networkPropertiesDirty
bool pocketmine\entity\Entity::$networkPropertiesDirty = false protected inherited
Definition at line 171 of file Entity.php.
$noClientPredictions
bool pocketmine\entity\Entity::$noClientPredictions = false protected inherited
Definition at line 181 of file Entity.php.
$noDamageTicks
int pocketmine\entity\Entity::$noDamageTicks = 0 inherited
Definition at line 154 of file Entity.php.
$onGround
bool pocketmine\entity\Entity::$onGround = false inherited
Definition at line 132 of file Entity.php.
$ownerId
int pocketmine\entity\Entity::$ownerId = null protected inherited
Definition at line 185 of file Entity.php.
$scale
float pocketmine\entity\Entity::$scale = 1.0 protected inherited
Definition at line 177 of file Entity.php.
$scoreTag
string pocketmine\entity\Entity::$scoreTag = "" protected inherited
Definition at line 176 of file Entity.php.
$server
Server pocketmine\entity\Entity::$server protected inherited
Definition at line 163 of file Entity.php.
$silent
bool pocketmine\entity\Entity::$silent = false protected inherited
Definition at line 183 of file Entity.php.
$size
EntitySizeInfo pocketmine\entity\Entity::$size inherited
Definition at line 134 of file Entity.php.
$stepHeight
float pocketmine\entity\Entity::$stepHeight = 0.0 protected inherited
Definition at line 140 of file Entity.php.
$targetId
int pocketmine\entity\Entity::$targetId = null protected inherited
Definition at line 186 of file Entity.php.
$ticksLived
int pocketmine\entity\Entity::$ticksLived = 0 inherited
Definition at line 144 of file Entity.php.
$timings
TimingsHandler pocketmine\entity\Entity::$timings protected inherited
Definition at line 169 of file Entity.php.
$ySize
float pocketmine\entity\Entity::$ySize = 0.0 protected inherited
Definition at line 139 of file Entity.php.
DATA_TO_FACING
const pocketmine\entity\object\Painting::DATA_TO_FACING
Initial value:
= [
        0 => Facing::SOUTH,
        1 => Facing::WEST,
        2 => Facing::NORTH,
        3 => Facing::EAST
    ]
Definition at line 54 of file Painting.php.
MOTION_THRESHOLD
const pocketmine\entity\Entity::MOTION_THRESHOLD = 0.00001 inherited
Definition at line 88 of file Entity.php.
STEP_CLIP_MULTIPLIER
const pocketmine\entity\Entity::STEP_CLIP_MULTIPLIER = 0.4 protected inherited
Definition at line 89 of file Entity.php.
TAG_DIRECTION_BE
const pocketmine\entity\object\Painting::TAG_DIRECTION_BE = "Direction"
Definition at line 49 of file Painting.php.
TAG_FACING_JE
const pocketmine\entity\object\Painting::TAG_FACING_JE = "Facing"
Definition at line 48 of file Painting.php.
TAG_MOTION
const pocketmine\entity\Entity::TAG_MOTION = "Motion" inherited
Definition at line 97 of file Entity.php.
TAG_MOTIVE
const pocketmine\entity\object\Painting::TAG_MOTIVE = "Motive"
Definition at line 50 of file Painting.php.
TAG_POS
const pocketmine\entity\Entity::TAG_POS = "Pos" inherited
Definition at line 96 of file Entity.php.
TAG_ROTATION
const pocketmine\entity\Entity::TAG_ROTATION = "Rotation" inherited
Definition at line 98 of file Entity.php.
TAG_TILE_X
const pocketmine\entity\object\Painting::TAG_TILE_X = "TileX"
Definition at line 45 of file Painting.php.
TAG_TILE_Y
const pocketmine\entity\object\Painting::TAG_TILE_Y = "TileY"
Definition at line 46 of file Painting.php.
TAG_TILE_Z
const pocketmine\entity\object\Painting::TAG_TILE_Z = "TileZ"
Definition at line 47 of file Painting.php.
The documentation for this class was generated from the following file:
Painting.php