PocketMine-MP: pocketmine\network\mcpe\protocol\CommandBlockUpdatePacket Class Reference
pocketmine\network\mcpe\protocol\CommandBlockUpdatePacket Class Reference
Public Member Functions
__get ($name)
__set ($name, $value)
canBeSentBeforeLogin ()
decode (PacketSerializer $in)
encode (PacketSerializer $out)
getName ()
handle (PacketHandlerInterface $handler)
pid ()
Public Attributes
BlockPosition $blockPosition
string $command
int $commandBlockMode
bool $executeOnFirstTick
string $filteredName
bool $isBlock
bool $isConditional
bool $isRedstoneMode
string $lastOutput
int $minecartActorRuntimeId
string $name
int $recipientSubId = 0
int $senderSubId = 0
bool $shouldTrackOutput
int $tickDelay
const NETWORK_ID = ProtocolInfo::COMMAND_BLOCK_UPDATE_PACKET
const PID_MASK = 0x3ff
Protected Member Functions
decodeHeader (PacketSerializer $in)
decodePayload (PacketSerializer $in)
encodeHeader (PacketSerializer $out)
encodePayload (PacketSerializer $out)
Detailed Description
Definition at line 20 of file CommandBlockUpdatePacket.php.
Member Function Documentation
__get()
pocketmine\network\mcpe\protocol\DataPacket::__get ($name) inherited
Parameters
string $name
Returns
mixed
Definition at line 105 of file DataPacket.php.
__set()
pocketmine\network\mcpe\protocol\DataPacket::__set ($name, $value) inherited
Parameters
string $name
mixed $value
Definition at line 113 of file DataPacket.php.
canBeSentBeforeLogin()
pocketmine\network\mcpe\protocol\DataPacket::canBeSentBeforeLogin () inherited
Implements pocketmine\network\mcpe\protocol\Packet.
Definition at line 42 of file DataPacket.php.
decode()
pocketmine\network\mcpe\protocol\DataPacket::decode (PacketSerializer $in) final inherited
Exceptions
PacketDecodeException
Implements pocketmine\network\mcpe\protocol\Packet.
Definition at line 49 of file DataPacket.php.
decodeHeader()
pocketmine\network\mcpe\protocol\DataPacket::decodeHeader (PacketSerializer $in) protected inherited
Exceptions
BinaryDataException
PacketDecodeException
Definition at line 62 of file DataPacket.php.
decodePayload()
pocketmine\network\mcpe\protocol\CommandBlockUpdatePacket::decodePayload (PacketSerializer $in) protected
Decodes the packet body, without the packet ID or other generic header fields.
Exceptions
PacketDecodeException
BinaryDataException
Reimplemented from pocketmine\network\mcpe\protocol\DataPacket.
Definition at line 40 of file CommandBlockUpdatePacket.php.
References pocketmine\network\mcpe\protocol\serializer\PacketSerializer\getBlockPosition(), pocketmine\utils\BinaryStream\getBool(), and pocketmine\utils\BinaryStream\getUnsignedVarInt().
encode()
pocketmine\network\mcpe\protocol\DataPacket::encode (PacketSerializer $out) final inherited
Implements pocketmine\network\mcpe\protocol\Packet.
Definition at line 82 of file DataPacket.php.
encodeHeader()
pocketmine\network\mcpe\protocol\DataPacket::encodeHeader (PacketSerializer $out) protected inherited
Definition at line 87 of file DataPacket.php.
encodePayload()
pocketmine\network\mcpe\protocol\CommandBlockUpdatePacket::encodePayload (PacketSerializer $out) protected
Encodes the packet body, without the packet ID or other generic header fields.
Reimplemented from pocketmine\network\mcpe\protocol\DataPacket.
Definition at line 62 of file CommandBlockUpdatePacket.php.
References pocketmine\network\mcpe\protocol\serializer\PacketSerializer\putBlockPosition(), and pocketmine\utils\BinaryStream\putUnsignedVarInt().
getName()
pocketmine\network\mcpe\protocol\DataPacket::getName () inherited
Implements pocketmine\network\mcpe\protocol\Packet.
Definition at line 38 of file DataPacket.php.
handle()
pocketmine\network\mcpe\protocol\CommandBlockUpdatePacket::handle (PacketHandlerInterface $handler)
Performs handling for this packet. Usually you'll want an appropriately named method in the session handler for this.
This method returns a bool to indicate whether the packet was handled or not. If the packet was unhandled, a debug message will be logged with a hexdump of the packet.
Typically this method returns the return value of the handler in the supplied PacketHandler. See other packets for examples how to implement this.
Returns
bool true if the packet was handled successfully, false if not.
Exceptions
PacketDecodeException if broken data was found in the packet
Implements pocketmine\network\mcpe\protocol\Packet.
Definition at line 83 of file CommandBlockUpdatePacket.php.
pid()
pocketmine\network\mcpe\protocol\DataPacket::pid () inherited
Implements pocketmine\network\mcpe\protocol\Packet.
Definition at line 34 of file DataPacket.php.
Member Data Documentation
$blockPosition
BlockPosition pocketmine\network\mcpe\protocol\CommandBlockUpdatePacket::$blockPosition
Definition at line 25 of file CommandBlockUpdatePacket.php.
$command
string pocketmine\network\mcpe\protocol\CommandBlockUpdatePacket::$command
Definition at line 32 of file CommandBlockUpdatePacket.php.
$commandBlockMode
int pocketmine\network\mcpe\protocol\CommandBlockUpdatePacket::$commandBlockMode
Definition at line 26 of file CommandBlockUpdatePacket.php.
$executeOnFirstTick
bool pocketmine\network\mcpe\protocol\CommandBlockUpdatePacket::$executeOnFirstTick
Definition at line 38 of file CommandBlockUpdatePacket.php.
$filteredName
string pocketmine\network\mcpe\protocol\CommandBlockUpdatePacket::$filteredName
Definition at line 35 of file CommandBlockUpdatePacket.php.
$isBlock
bool pocketmine\network\mcpe\protocol\CommandBlockUpdatePacket::$isBlock
Definition at line 23 of file CommandBlockUpdatePacket.php.
$isConditional
bool pocketmine\network\mcpe\protocol\CommandBlockUpdatePacket::$isConditional
Definition at line 28 of file CommandBlockUpdatePacket.php.
$isRedstoneMode
bool pocketmine\network\mcpe\protocol\CommandBlockUpdatePacket::$isRedstoneMode
Definition at line 27 of file CommandBlockUpdatePacket.php.
$lastOutput
string pocketmine\network\mcpe\protocol\CommandBlockUpdatePacket::$lastOutput
Definition at line 33 of file CommandBlockUpdatePacket.php.
$minecartActorRuntimeId
int pocketmine\network\mcpe\protocol\CommandBlockUpdatePacket::$minecartActorRuntimeId
Definition at line 30 of file CommandBlockUpdatePacket.php.
$name
string pocketmine\network\mcpe\protocol\CommandBlockUpdatePacket::$name
Definition at line 34 of file CommandBlockUpdatePacket.php.
$recipientSubId
int pocketmine\network\mcpe\protocol\DataPacket::$recipientSubId = 0 inherited
Definition at line 32 of file DataPacket.php.
$senderSubId
int pocketmine\network\mcpe\protocol\DataPacket::$senderSubId = 0 inherited
Definition at line 31 of file DataPacket.php.
$shouldTrackOutput
bool pocketmine\network\mcpe\protocol\CommandBlockUpdatePacket::$shouldTrackOutput
Definition at line 36 of file CommandBlockUpdatePacket.php.
$tickDelay
int pocketmine\network\mcpe\protocol\CommandBlockUpdatePacket::$tickDelay
Definition at line 37 of file CommandBlockUpdatePacket.php.
NETWORK_ID
const pocketmine\network\mcpe\protocol\CommandBlockUpdatePacket::NETWORK_ID = ProtocolInfo::COMMAND_BLOCK_UPDATE_PACKET
Definition at line 21 of file CommandBlockUpdatePacket.php.
PID_MASK
const pocketmine\network\mcpe\protocol\DataPacket::PID_MASK = 0x3ff inherited
Definition at line 25 of file DataPacket.php.
The documentation for this class was generated from the following file:
CommandBlockUpdatePacket.php