PocketMine-MP: pocketmine\stats\SendUsageTask Class Reference
pocketmine\stats\SendUsageTask Class Reference
Public Member Functions
__construct (Server $server, int $type, array $playerList=[])
cancelRun ()
checkProgressUpdates ()
getResult ()
hasCancelledRun ()
hasResult ()
isCrashed ()
isFinished ()
isSubmitted ()
onCompletion ()
onError ()
onProgressUpdate ($progress)
onRun ()
publishProgress ($progress)
run ()
setResult ($result)
setSubmitted ()
Public Attributes
$data
$endpoint
$progressUpdates
$worker = null
const TYPE_CLOSE = 3
const TYPE_OPEN = 1
const TYPE_STATUS = 2
Protected Member Functions
fetchLocal (string $key)
reallyDestruct ()
storeLocal (string $key, $complexData)
Detailed Description
Definition at line 46 of file SendUsageTask.php.
Constructor & Destructor Documentation
__construct()
pocketmine\stats\SendUsageTask::__construct (Server $server, int $type, array $playerList = [])
Parameters
string[] $playerList @phpstan-param array<string, string> $playerList
Definition at line 61 of file SendUsageTask.php.
References pocketmine\network\mcpe\protocol\ProtocolInfo\CURRENT_PROTOCOL, pocketmine\utils\Process\getAdvancedMemoryUsage(), pocketmine\utils\Utils\getMachineUniqueId(), pocketmine\Server\getOnlinePlayers(), pocketmine\utils\Utils\getOS(), pocketmine\Server\getTicksPerSecondAverage(), and pocketmine\Server\getTickUsageAverage().
Member Function Documentation
cancelRun()
pocketmine\scheduler\AsyncTask::cancelRun () inherited
Definition at line 135 of file AsyncTask.php.
checkProgressUpdates()
pocketmine\scheduler\AsyncTask::checkProgressUpdates () inherited
Definition at line 177 of file AsyncTask.php.
fetchLocal()
pocketmine\scheduler\AsyncTask::fetchLocal (string $key) protected inherited
Retrieves data stored in thread-local storage.
If you used storeLocal(), you can use this on the same thread to fetch data stored. This should be used during onProgressUpdate() and onCompletion() to fetch thread-local data stored on the parent thread.
Returns
mixed
Exceptions
InvalidArgumentException if no data were stored by this AsyncTask instance.
Definition at line 243 of file AsyncTask.php.
getResult()
pocketmine\scheduler\AsyncTask::getResult () inherited
Returns
mixed
Definition at line 120 of file AsyncTask.php.
hasCancelledRun()
pocketmine\scheduler\AsyncTask::hasCancelledRun () inherited
Definition at line 139 of file AsyncTask.php.
hasResult()
pocketmine\scheduler\AsyncTask::hasResult () inherited
Definition at line 113 of file AsyncTask.php.
isCrashed()
pocketmine\scheduler\AsyncTask::isCrashed () inherited
Definition at line 101 of file AsyncTask.php.
isFinished()
pocketmine\scheduler\AsyncTask::isFinished () inherited
Returns whether this task has finished executing, whether successfully or not. This differs from isRunning() because it is not true prior to task execution.
Definition at line 109 of file AsyncTask.php.
isSubmitted()
pocketmine\scheduler\AsyncTask::isSubmitted () inherited
Definition at line 147 of file AsyncTask.php.
onCompletion()
pocketmine\scheduler\AsyncTask::onCompletion () inherited
Actions to execute when completed (on main thread) Implement this if you want to handle the data in your AsyncTask after it has been processed
Reimplemented in pocketmine\network\mcpe\auth\ProcessLoginTask, pocketmine\network\mcpe\ChunkRequestTask, pocketmine\network\mcpe\compression\CompressBatchTask, pocketmine\network\mcpe\encryption\PrepareEncryptionTask, pocketmine\scheduler\BulkCurlTask, pocketmine\updater\UpdateCheckTask, pocketmine\world\generator\PopulationTask, and pocketmine\world\light\LightPopulationTask.
Definition at line 160 of file AsyncTask.php.
onError()
pocketmine\scheduler\AsyncTask::onError () inherited
Called from the main thread when the async task experiences an error during onRun(). Use this for things like promise rejection.
Reimplemented in pocketmine\network\mcpe\ChunkRequestTask.
Definition at line 200 of file AsyncTask.php.
onProgressUpdate()
pocketmine\scheduler\AsyncTask::onProgressUpdate ($progress) inherited
Called from the main thread after AsyncTask::publishProgress is called. All AsyncTask::publishProgress calls should result in AsyncTask::onProgressUpdate calls before AsyncTask::onCompletion is called.
Parameters
mixed $progress The parameter passed to AsyncTask#publishProgress. It is serialize()'ed and then unserialize()'ed, as if it has been cloned.
Definition at line 192 of file AsyncTask.php.
onRun()
pocketmine\stats\SendUsageTask::onRun ()
Actions to execute when run
Reimplemented from pocketmine\scheduler\AsyncTask.
Definition at line 155 of file SendUsageTask.php.
publishProgress()
pocketmine\scheduler\AsyncTask::publishProgress ($progress) inherited
Call this method from AsyncTask::onRun (AsyncTask execution thread) to schedule a call to AsyncTask::onProgressUpdate from the main thread with the given progress parameter.
Parameters
mixed $progress A value that can be safely serialize()'ed.
Definition at line 170 of file AsyncTask.php.
reallyDestruct()
pocketmine\scheduler\AsyncTask::reallyDestruct () protected inherited
Override this to do normal __destruct() cleanup from a child class.
Definition at line 265 of file AsyncTask.php.
run()
pocketmine\scheduler\AsyncTask::run () inherited
Definition at line 85 of file AsyncTask.php.
setResult()
pocketmine\scheduler\AsyncTask::setResult ($result) inherited
Parameters
mixed $result
Definition at line 131 of file AsyncTask.php.
setSubmitted()
pocketmine\scheduler\AsyncTask::setSubmitted () inherited
Definition at line 143 of file AsyncTask.php.
storeLocal()
pocketmine\scheduler\AsyncTask::storeLocal (string $key, $complexData) protected inherited
Saves mixed data in thread-local storage. Data stored using this storage is only accessible from the thread it was stored on. Data stored using this method will not be serialized. This can be used to store references to variables which you need later on on the same thread, but not others.
For example, plugin references could be stored in the constructor of the async task (which is called on the main thread) using this, and then fetched in onCompletion() (which is also called on the main thread), without them becoming serialized.
Scalar types can be stored directly in class properties instead of using this storage.
Objects stored in this storage can be retrieved using fetchLocal() on the same thread that this method was called from.
Parameters
mixed $complexData the data to store
Definition at line 220 of file AsyncTask.php.
Referenced by pocketmine\network\mcpe\auth\ProcessLoginTask\__construct(), pocketmine\scheduler\BulkCurlTask\__construct(), pocketmine\world\light\LightPopulationTask\__construct(), pocketmine\network\mcpe\ChunkRequestTask\__construct(), pocketmine\world\generator\PopulationTask\__construct(), and pocketmine\network\mcpe\encryption\PrepareEncryptionTask\__construct().
Member Data Documentation
$data
pocketmine\stats\SendUsageTask::$data
Definition at line 55 of file SendUsageTask.php.
$endpoint
pocketmine\stats\SendUsageTask::$endpoint
Definition at line 53 of file SendUsageTask.php.
$progressUpdates
pocketmine\scheduler\AsyncTask::$progressUpdates inherited
Definition at line 75 of file AsyncTask.php.
$worker
AsyncWorker null pocketmine\scheduler\AsyncTask::$worker = null inherited
Definition at line 72 of file AsyncTask.php.
TYPE_CLOSE
const pocketmine\stats\SendUsageTask::TYPE_CLOSE = 3
Definition at line 50 of file SendUsageTask.php.
TYPE_OPEN
const pocketmine\stats\SendUsageTask::TYPE_OPEN = 1
Definition at line 48 of file SendUsageTask.php.
TYPE_STATUS
const pocketmine\stats\SendUsageTask::TYPE_STATUS = 2
Definition at line 49 of file SendUsageTask.php.
The documentation for this class was generated from the following file:
SendUsageTask.php