PocketMine-MP: DaveRandom\CallbackValidator\MatchTester Class Reference
DaveRandom\CallbackValidator\MatchTester Class Reference
Static Public Member Functions
static isMatch ($superTypeName, $superTypeNullable, $subTypeName, $subTypeNullable, $weak)
static isWeakScalarMatch ($superTypeName, $subTypeName)
Detailed Description
Definition at line 5 of file MatchTester.php.
Member Function Documentation
isMatch()
static DaveRandom\CallbackValidator\MatchTester::isMatch ($superTypeName, $superTypeNullable, $subTypeName, $subTypeNullable, $weak) static
Parameters
string | null $superTypeName
bool $superTypeNullable
string | null $subTypeName
bool $subTypeNullable
bool $weak
Returns
bool
Definition at line 71 of file MatchTester.php.
References DaveRandom\CallbackValidator\MatchTester\isWeakScalarMatch().
Referenced by DaveRandom\CallbackValidator\Type\isSatisfiedBy().
isWeakScalarMatch()
static DaveRandom\CallbackValidator\MatchTester::isWeakScalarMatch ($superTypeName, $subTypeName) static
Parameters
string $superTypeName
string $subTypeName
Returns
bool
Definition at line 43 of file MatchTester.php.
Referenced by DaveRandom\CallbackValidator\MatchTester\isMatch(), and DaveRandom\CallbackValidator\Type\isSatisfiedBy().
The documentation for this class was generated from the following file:
MatchTester.php