PocketMine-MP: pocketmine\nbt\tag\Tag Class Reference
pocketmine\nbt\tag\Tag Class Reference
Public Member Functions
__toString ()
equals (Tag $that)
getType ()
getValue ()
safeClone ()
toString (int $indentation=0)
write (NbtStreamWriter $writer)
Protected Member Functions
getTypeName ()
makeCopy ()
stringifyValue (int $indentation)
Static Protected Member Functions
static restrictArgCount (string $func, int $haveArgs, int $wantMaxArgs)
Protected Attributes
$cloning = false
Detailed Description
Definition at line 28 of file Tag.php.
Member Function Documentation
__toString()
pocketmine\nbt\tag\Tag::__toString ()
Definition at line 43 of file Tag.php.
equals()
pocketmine\nbt\tag\Tag::equals (Tag $that)
Compares this Tag to the given Tag and determines whether or not they are equal, based on type and value. Complex tag types should override this to provide proper value comparison.
Reimplemented in pocketmine\nbt\tag\CompoundTag, pocketmine\nbt\tag\FloatTag, and pocketmine\nbt\tag\ListTag.
Definition at line 84 of file Tag.php.
getValue()
pocketmine\nbt\tag\Tag::getValue () abstract
Returns
mixed
Reimplemented in pocketmine\nbt\tag\ByteArrayTag, pocketmine\nbt\tag\CompoundTag, pocketmine\nbt\tag\DoubleTag, pocketmine\nbt\tag\FloatTag, pocketmine\nbt\tag\IntArrayTag, pocketmine\nbt\tag\ListTag, and pocketmine\nbt\tag\StringTag.
Referenced by pocketmine\data\bedrock\block\convert\BlockStateReader\readBool(), pocketmine\data\bedrock\block\convert\BlockStateReader\readInt(), and pocketmine\data\bedrock\block\convert\BlockStateReader\readString().
makeCopy()
pocketmine\nbt\tag\Tag::makeCopy () abstract protected
Returns
static
Reimplemented in pocketmine\nbt\tag\CompoundTag, pocketmine\nbt\tag\ImmutableTag, and pocketmine\nbt\tag\ListTag.
restrictArgCount()
static pocketmine\nbt\tag\Tag::restrictArgCount (string $func, int $haveArgs, int $wantMaxArgs) static protected
Definition at line 88 of file Tag.php.
safeClone()
pocketmine\nbt\tag\Tag::safeClone ()
Clones this tag safely, detecting recursive dependencies which would otherwise cause an infinite cloning loop. Used for cloning tags in tags that have children.
Exceptions
RuntimeException if a recursive dependency was detected
Definition at line 61 of file Tag.php.
toString()
pocketmine\nbt\tag\Tag::toString (int $indentation = 0) final
Definition at line 47 of file Tag.php.
Member Data Documentation
$cloning
pocketmine\nbt\tag\Tag::$cloning = false protected
Definition at line 34 of file Tag.php.
The documentation for this class was generated from the following file:
Tag.php