PocketMine-MP: pocketmine\network\mcpe\protocol\SetScoreboardIdentityPacket Class Reference
pocketmine\network\mcpe\protocol\SetScoreboardIdentityPacket Class Reference
Public Member Functions
__get ($name)
__set ($name, $value)
canBeSentBeforeLogin ()
decode (PacketSerializer $in)
encode (PacketSerializer $out)
getName ()
handle (PacketHandlerInterface $handler)
pid ()
Static Public Member Functions
static create (int $type, array $entries)
Public Attributes
array $entries = []
int $recipientSubId = 0
int $senderSubId = 0
int $type
const NETWORK_ID = ProtocolInfo::SET_SCOREBOARD_IDENTITY_PACKET
const PID_MASK = 0x3ff
const TYPE_CLEAR_IDENTITY = 1
const TYPE_REGISTER_IDENTITY = 0
Protected Member Functions
decodeHeader (PacketSerializer $in)
decodePayload (PacketSerializer $in)
encodeHeader (PacketSerializer $out)
encodePayload (PacketSerializer $out)
Detailed Description
Definition at line 21 of file SetScoreboardIdentityPacket.php.
Member Function Documentation
__get()
pocketmine\network\mcpe\protocol\DataPacket::__get ($name) inherited
Parameters
string $name
Returns
mixed
Definition at line 105 of file DataPacket.php.
__set()
pocketmine\network\mcpe\protocol\DataPacket::__set ($name, $value) inherited
Parameters
string $name
mixed $value
Definition at line 113 of file DataPacket.php.
canBeSentBeforeLogin()
pocketmine\network\mcpe\protocol\DataPacket::canBeSentBeforeLogin () inherited
Implements pocketmine\network\mcpe\protocol\Packet.
Definition at line 42 of file DataPacket.php.
create()
static pocketmine\network\mcpe\protocol\SetScoreboardIdentityPacket::create (int $type, array $entries) static
@generate-create-func
Parameters
ScoreboardIdentityPacketEntry[] $entries
Definition at line 35 of file SetScoreboardIdentityPacket.php.
decode()
pocketmine\network\mcpe\protocol\DataPacket::decode (PacketSerializer $in) final inherited
Exceptions
PacketDecodeException
Implements pocketmine\network\mcpe\protocol\Packet.
Definition at line 49 of file DataPacket.php.
decodeHeader()
pocketmine\network\mcpe\protocol\DataPacket::decodeHeader (PacketSerializer $in) protected inherited
Exceptions
BinaryDataException
PacketDecodeException
Definition at line 62 of file DataPacket.php.
decodePayload()
pocketmine\network\mcpe\protocol\SetScoreboardIdentityPacket::decodePayload (PacketSerializer $in) protected
Decodes the packet body, without the packet ID or other generic header fields.
Exceptions
PacketDecodeException
BinaryDataException
Reimplemented from pocketmine\network\mcpe\protocol\DataPacket.
Definition at line 42 of file SetScoreboardIdentityPacket.php.
References pocketmine\network\mcpe\protocol\serializer\PacketSerializer\getActorUniqueId(), and pocketmine\utils\BinaryStream\getVarLong().
encode()
pocketmine\network\mcpe\protocol\DataPacket::encode (PacketSerializer $out) final inherited
Implements pocketmine\network\mcpe\protocol\Packet.
Definition at line 82 of file DataPacket.php.
encodeHeader()
pocketmine\network\mcpe\protocol\DataPacket::encodeHeader (PacketSerializer $out) protected inherited
Definition at line 87 of file DataPacket.php.
encodePayload()
pocketmine\network\mcpe\protocol\SetScoreboardIdentityPacket::encodePayload (PacketSerializer $out) protected
Encodes the packet body, without the packet ID or other generic header fields.
Reimplemented from pocketmine\network\mcpe\protocol\DataPacket.
Definition at line 55 of file SetScoreboardIdentityPacket.php.
References pocketmine\utils\BinaryStream\putVarLong().
getName()
pocketmine\network\mcpe\protocol\DataPacket::getName () inherited
Implements pocketmine\network\mcpe\protocol\Packet.
Definition at line 38 of file DataPacket.php.
handle()
pocketmine\network\mcpe\protocol\SetScoreboardIdentityPacket::handle (PacketHandlerInterface $handler)
Performs handling for this packet. Usually you'll want an appropriately named method in the session handler for this.
This method returns a bool to indicate whether the packet was handled or not. If the packet was unhandled, a debug message will be logged with a hexdump of the packet.
Typically this method returns the return value of the handler in the supplied PacketHandler. See other packets for examples how to implement this.
Returns
bool true if the packet was handled successfully, false if not.
Exceptions
PacketDecodeException if broken data was found in the packet
Implements pocketmine\network\mcpe\protocol\Packet.
Definition at line 66 of file SetScoreboardIdentityPacket.php.
pid()
pocketmine\network\mcpe\protocol\DataPacket::pid () inherited
Implements pocketmine\network\mcpe\protocol\Packet.
Definition at line 34 of file DataPacket.php.
Member Data Documentation
$entries
array pocketmine\network\mcpe\protocol\SetScoreboardIdentityPacket::$entries = []
Definition at line 29 of file SetScoreboardIdentityPacket.php.
$recipientSubId
int pocketmine\network\mcpe\protocol\DataPacket::$recipientSubId = 0 inherited
Definition at line 32 of file DataPacket.php.
$senderSubId
int pocketmine\network\mcpe\protocol\DataPacket::$senderSubId = 0 inherited
Definition at line 31 of file DataPacket.php.
$type
int pocketmine\network\mcpe\protocol\SetScoreboardIdentityPacket::$type
Definition at line 27 of file SetScoreboardIdentityPacket.php.
NETWORK_ID
const pocketmine\network\mcpe\protocol\SetScoreboardIdentityPacket::NETWORK_ID = ProtocolInfo::SET_SCOREBOARD_IDENTITY_PACKET
Definition at line 22 of file SetScoreboardIdentityPacket.php.
PID_MASK
const pocketmine\network\mcpe\protocol\DataPacket::PID_MASK = 0x3ff inherited
Definition at line 25 of file DataPacket.php.
TYPE_CLEAR_IDENTITY
const pocketmine\network\mcpe\protocol\SetScoreboardIdentityPacket::TYPE_CLEAR_IDENTITY = 1
Definition at line 25 of file SetScoreboardIdentityPacket.php.
TYPE_REGISTER_IDENTITY
const pocketmine\network\mcpe\protocol\SetScoreboardIdentityPacket::TYPE_REGISTER_IDENTITY = 0
Definition at line 24 of file SetScoreboardIdentityPacket.php.
The documentation for this class was generated from the following file:
SetScoreboardIdentityPacket.php