PocketMine-MP: pocketmine\network\mcpe\protocol\serializer\PacketBatch Class Reference
pocketmine\network\mcpe\protocol\serializer\PacketBatch Class Reference
Public Member Functions
__construct (private string $buffer)
getBuffer ()
getPackets (PacketPool $packetPool, PacketSerializerContext $decoderContext, int $max)
Static Public Member Functions
static decodePackets (BinaryStream $stream, PacketSerializerContext $context, PacketPool $packetPool)
static decodeRaw (BinaryStream $stream)
static encodePackets (BinaryStream $stream, PacketSerializerContext $context, array $packets)
static encodeRaw (BinaryStream $stream, array $packets)
static fromPackets (PacketSerializerContext $context, Packet ... $packets)
Detailed Description
Definition at line 24 of file PacketBatch.php.
Constructor & Destructor Documentation
__construct()
pocketmine\network\mcpe\protocol\serializer\PacketBatch::__construct (private string $buffer)
Deprecated:
Definition at line 93 of file PacketBatch.php.
Member Function Documentation
decodePackets()
static pocketmine\network\mcpe\protocol\serializer\PacketBatch::decodePackets (BinaryStream $stream, PacketSerializerContext $context, PacketPool $packetPool) static final
@phpstan-return \Generator<int, Packet, void, void>
Exceptions
PacketDecodeException
Definition at line 59 of file PacketBatch.php.
References pocketmine\network\mcpe\protocol\PacketPool\getPacket().
decodeRaw()
static pocketmine\network\mcpe\protocol\serializer\PacketBatch::decodeRaw (BinaryStream $stream) static final
@phpstan-return \Generator<int, string, void, void>
Exceptions
PacketDecodeException
Definition at line 30 of file PacketBatch.php.
References pocketmine\utils\BinaryStream\get(), and pocketmine\utils\BinaryStream\getUnsignedVarInt().
encodePackets()
static pocketmine\network\mcpe\protocol\serializer\PacketBatch::encodePackets (BinaryStream $stream, PacketSerializerContext $context, array $packets) static final
Parameters
Packet[] $packets @phpstan-param list<Packet> $packets
Definition at line 81 of file PacketBatch.php.
References pocketmine\utils\BinaryStream\putUnsignedVarInt().
encodeRaw()
static pocketmine\network\mcpe\protocol\serializer\PacketBatch::encodeRaw (BinaryStream $stream, array $packets) static final
Parameters
string[] $packets @phpstan-param list<string> $packets
Definition at line 48 of file PacketBatch.php.
References pocketmine\utils\BinaryStream\putUnsignedVarInt().
fromPackets()
static pocketmine\network\mcpe\protocol\serializer\PacketBatch::fromPackets (PacketSerializerContext $context, Packet ... $packets) static
Deprecated:
Constructs a packet batch from the given list of packets.
Definition at line 122 of file PacketBatch.php.
getBuffer()
pocketmine\network\mcpe\protocol\serializer\PacketBatch::getBuffer ()
Deprecated:
Definition at line 131 of file PacketBatch.php.
getPackets()
pocketmine\network\mcpe\protocol\serializer\PacketBatch::getPackets (PacketPool $packetPool, PacketSerializerContext $decoderContext, int $max)
Deprecated:
Returns
\Generator|Packet[]|null[] @phpstan-return \Generator<int, array{?Packet, string}, void, void>
Exceptions
PacketDecodeException
Definition at line 103 of file PacketBatch.php.
References pocketmine\network\mcpe\protocol\PacketPool\getPacket().
The documentation for this class was generated from the following file:
PacketBatch.php