PocketMine-MP: AttachableThreadedLogger Class Reference
AttachableThreadedLogger Class Reference
Public Member Functions
addAttachment (\ThreadedLoggerAttachment $attachment)
alert ($message)
critical ($message)
debug ($message)
emergency ($message)
error ($message)
getAttachments ()
info ($message)
log ($level, $message)
logException (\Throwable $e, $trace=null)
notice ($message)
removeAttachment (\ThreadedLoggerAttachment $attachment)
removeAttachments ()
warning ($message)
Protected Attributes
$attachments
Detailed Description
Definition at line 18 of file AttachableThreadedLogger.php.
Constructor & Destructor Documentation
__construct()
AttachableThreadedLogger::__construct ()
Definition at line 23 of file AttachableThreadedLogger.php.
Member Function Documentation
addAttachment()
AttachableThreadedLogger::addAttachment (\ThreadedLoggerAttachment $attachment)
Parameters
ThreadedLoggerAttachment $attachment
Returns
void
Definition at line 32 of file AttachableThreadedLogger.php.
alert()
Logger::alert ($message) inherited
Action must be taken immediately
Parameters
string $message
Returns
void
Implemented in pocketmine\utils\MainLogger, and SimpleLogger.
critical()
Logger::critical ($message) inherited
Critical conditions
Parameters
string $message
Returns
void
Implemented in pocketmine\utils\MainLogger, and SimpleLogger.
Referenced by pocketmine\resourcepacks\ResourcePackManager\__construct().
debug()
Logger::debug ($message) inherited
Detailed debug information.
Parameters
string $message
Returns
void
Implemented in SimpleLogger.
Referenced by pocketmine\resourcepacks\ResourcePackManager\__construct().
emergency()
Logger::emergency ($message) inherited
System is unusable
Parameters
string $message
Returns
void
Implemented in pocketmine\utils\MainLogger, and SimpleLogger.
error()
Logger::error ($message) inherited
Runtime errors that do not require immediate action but should typically be logged and monitored.
Parameters
string $message
Returns
void
Implemented in pocketmine\utils\MainLogger, and SimpleLogger.
getAttachments()
AttachableThreadedLogger::getAttachments ()
Returns
\ThreadedLoggerAttachment[]
Definition at line 61 of file AttachableThreadedLogger.php.
info()
Logger::info ($message) inherited
Interesting events.
Parameters
string $message
Returns
void
Implemented in pocketmine\utils\MainLogger, and SimpleLogger.
Referenced by pocketmine\resourcepacks\ResourcePackManager\__construct().
log()
Logger::log ($level, $message) inherited
Logs with an arbitrary level.
Parameters
mixed $level
string $message
Returns
void
Implemented in pocketmine\plugin\PluginLogger, pocketmine\utils\MainLogger, PrefixedLogger, and SimpleLogger.
logException()
Logger::logException (\Throwable $e, $trace = null) inherited
Logs a Throwable object
Parameters
Throwable $e
array | null $trace @phpstan-param list<array<string, mixed>>|null $trace
Returns
void
Implemented in pocketmine\utils\MainLogger, and SimpleLogger.
notice()
Logger::notice ($message) inherited
Normal but significant events.
Parameters
string $message
Returns
void
Implemented in pocketmine\utils\MainLogger, and SimpleLogger.
removeAttachment()
AttachableThreadedLogger::removeAttachment (\ThreadedLoggerAttachment $attachment)
Parameters
ThreadedLoggerAttachment $attachment
Returns
void
Definition at line 41 of file AttachableThreadedLogger.php.
removeAttachments()
AttachableThreadedLogger::removeAttachments ()
Returns
void
Definition at line 52 of file AttachableThreadedLogger.php.
warning()
Logger::warning ($message) inherited
Exceptional occurrences that are not errors.
Example: Use of deprecated APIs, poor use of an API, undesirable things that are not necessarily wrong.
Parameters
string $message
Returns
void
Implemented in pocketmine\utils\MainLogger, and SimpleLogger.
Referenced by pocketmine\emit_performance_warnings().
Member Data Documentation
$attachments
AttachableThreadedLogger::$attachments protected
Definition at line 21 of file AttachableThreadedLogger.php.
The documentation for this class was generated from the following file:
AttachableThreadedLogger.php