PocketMine-MP: pocketmine\block\tile\Lectern Class Reference
pocketmine\block\tile\Lectern Class Reference
Public Member Functions
clearSpawnCompoundCache ()
close ()
copyDataFromItem (Item $item)
getBlock ()
getBook ()
getCleanedNBT ()
getPosition ()
getRenderUpdateBugWorkaroundStateProperties (Block $block)
getSerializedSpawnCompound ()
getSpawnCompound ()
getViewedPage ()
isClosed ()
isDirty ()
onBlockDestroyed ()
readSaveData (CompoundTag $nbt)
saveNBT ()
setBook (?WritableBookBase $book)
setDirty (bool $dirty=true)
setViewedPage (int $viewedPage)
Public Attributes
bool $closed = false
const TAG_BOOK = "book"
const TAG_HAS_BOOK = "hasBook"
const TAG_ID = "id"
const TAG_PAGE = "page"
const TAG_TOTAL_PAGES = "totalPages"
const TAG_X = "x"
const TAG_Y = "y"
const TAG_Z = "z"
Protected Member Functions
addAdditionalSpawnData (CompoundTag $nbt)
onBlockDestroyedHook ()
writeSaveData (CompoundTag $nbt)
Protected Attributes
Position $position
TimingsHandler $timings
Detailed Description
Deprecated
See also
\pocketmine\block\Lectern
Definition at line 36 of file tile/Lectern.php.
Member Function Documentation
addAdditionalSpawnData()
pocketmine\block\tile\Lectern::addAdditionalSpawnData (CompoundTag $nbt) protected
An extension to getSpawnCompound() for further modifying the generic tile NBT.
Reimplemented from pocketmine\block\tile\Spawnable.
Definition at line 80 of file tile/Lectern.php.
References pocketmine\nbt\tag\CompoundTag\setInt(), and pocketmine\nbt\tag\CompoundTag\setTag().
clearSpawnCompoundCache()
pocketmine\block\tile\Spawnable::clearSpawnCompoundCache () inherited
Definition at line 52 of file Spawnable.php.
close()
pocketmine\block\tile\Tile::close () inherited
Definition at line 129 of file Tile.php.
copyDataFromItem()
pocketmine\block\tile\Tile::copyDataFromItem (Item $item) inherited
Definition at line 92 of file Tile.php.
getBlock()
pocketmine\block\tile\Tile::getBlock () inherited
Definition at line 98 of file Tile.php.
getBook()
pocketmine\block\tile\Lectern::getBook ()
Definition at line 72 of file tile/Lectern.php.
getCleanedNBT()
pocketmine\block\tile\Tile::getCleanedNBT () inherited
Definition at line 82 of file Tile.php.
getPosition()
pocketmine\block\tile\Tile::getPosition () inherited
Definition at line 102 of file Tile.php.
getRenderUpdateBugWorkaroundStateProperties()
pocketmine\block\tile\Spawnable::getRenderUpdateBugWorkaroundStateProperties (Block $block) inherited
The Bedrock client won't re-render a block if the block's state properties didn't change. This is a problem when the tile may affect the block's appearance. For example, a cauldron's liquid changes colour based on the dye inside.
This is worked around in vanilla by modifying one of the block's state properties to a different value, and then changing it back again. Since we don't want to litter core implementation with hacks like this, we brush it under the rug into Tile.
Returns
ByteTag[]|IntTag[]|StringTag[] @phpstan-return array<string, IntTag|StringTag|ByteTag>
Reimplemented in pocketmine\block\tile\Cauldron, and pocketmine\block\tile\FlowerPot.
Definition at line 68 of file Spawnable.php.
getSerializedSpawnCompound()
pocketmine\block\tile\Spawnable::getSerializedSpawnCompound () final inherited
Returns encoded NBT (varint, little-endian) used to spawn this tile to clients. Uses cache where possible, populates cache if it is null.
@phpstan-return CacheableNbt<\pocketmine\nbt\tag\CompoundTag>
Definition at line 78 of file Spawnable.php.
getSpawnCompound()
pocketmine\block\tile\Spawnable::getSpawnCompound () final inherited
Definition at line 86 of file Spawnable.php.
getViewedPage()
pocketmine\block\tile\Lectern::getViewedPage ()
Definition at line 64 of file tile/Lectern.php.
isClosed()
pocketmine\block\tile\Tile::isClosed () inherited
Definition at line 106 of file Tile.php.
isDirty()
pocketmine\block\tile\Spawnable::isDirty () inherited
Deprecated
Definition at line 41 of file Spawnable.php.
onBlockDestroyed()
pocketmine\block\tile\Tile::onBlockDestroyed () final inherited
Called when the tile's block is destroyed.
Definition at line 117 of file Tile.php.
References pocketmine\block\tile\onBlockDestroyedHook().
onBlockDestroyedHook()
pocketmine\block\tile\Tile::onBlockDestroyedHook () protected inherited
Override this method to do actions you need to do when this tile is destroyed due to block being broken.
Reimplemented in pocketmine\block\tile\Chest, pocketmine\block\tile\Jukebox, and pocketmine\block\tile\ShulkerBox.
Definition at line 125 of file Tile.php.
readSaveData()
pocketmine\block\tile\Lectern::readSaveData (CompoundTag $nbt)
Reimplemented from pocketmine\block\tile\Tile.
Definition at line 45 of file tile/Lectern.php.
saveNBT()
pocketmine\block\tile\Tile::saveNBT () inherited
Definition at line 70 of file Tile.php.
setBook()
pocketmine\block\tile\Lectern::setBook (?WritableBookBase $book)
Definition at line 76 of file tile/Lectern.php.
setDirty()
pocketmine\block\tile\Spawnable::setDirty (bool $dirty = true) inherited
Deprecated
Definition at line 48 of file Spawnable.php.
setViewedPage()
pocketmine\block\tile\Lectern::setViewedPage (int $viewedPage)
Definition at line 68 of file tile/Lectern.php.
writeSaveData()
pocketmine\block\tile\Lectern::writeSaveData (CompoundTag $nbt) protected
Writes additional save data to a CompoundTag, not including generic things like ID and coordinates.
Reimplemented from pocketmine\block\tile\Tile.
Definition at line 55 of file tile/Lectern.php.
References pocketmine\nbt\tag\CompoundTag\setInt(), and pocketmine\nbt\tag\CompoundTag\setTag().
Member Data Documentation
$closed
bool pocketmine\block\tile\Tile::$closed = false inherited
Definition at line 50 of file Tile.php.
$position
Position pocketmine\block\tile\Tile::$position protected inherited
Definition at line 49 of file Tile.php.
$timings
TimingsHandler pocketmine\block\tile\Tile::$timings protected inherited
Definition at line 51 of file Tile.php.
TAG_BOOK
const pocketmine\block\tile\Lectern::TAG_BOOK = "book"
Definition at line 40 of file tile/Lectern.php.
TAG_HAS_BOOK
const pocketmine\block\tile\Lectern::TAG_HAS_BOOK = "hasBook"
Definition at line 37 of file tile/Lectern.php.
TAG_ID
const pocketmine\block\tile\Tile::TAG_ID = "id" inherited
Definition at line 44 of file Tile.php.
TAG_PAGE
const pocketmine\block\tile\Lectern::TAG_PAGE = "page"
Definition at line 38 of file tile/Lectern.php.
TAG_TOTAL_PAGES
const pocketmine\block\tile\Lectern::TAG_TOTAL_PAGES = "totalPages"
Definition at line 39 of file tile/Lectern.php.
TAG_X
const pocketmine\block\tile\Tile::TAG_X = "x" inherited
Definition at line 45 of file Tile.php.
TAG_Y
const pocketmine\block\tile\Tile::TAG_Y = "y" inherited
Definition at line 46 of file Tile.php.
TAG_Z
const pocketmine\block\tile\Tile::TAG_Z = "z" inherited
Definition at line 47 of file Tile.php.
The documentation for this class was generated from the following file:
tile/Lectern.php