PocketMine-MP: pocketmine\block\inventory\EnchantInventory Class Reference
pocketmine\block\inventory\EnchantInventory Class Reference
Public Member Functions
__construct (Position $holder)
addItem (Item ... $slots)
all (Item $item)
canAddItem (Item $item)
clear (int $index)
clearAll ()
contains (Item $item)
first (Item $item, bool $exact=false)
firstEmpty ()
getAddableItemQuantity (Item $item)
getContents (bool $includeEmpty=false)
getHolder ()
getItem (int $index)
getListeners ()
getMaxStackSize ()
getSize ()
getViewers ()
isSlotEmpty (int $index)
onClose (Player $who)
onOpen (Player $who)
remove (Item $item)
removeAllViewers ()
removeItem (Item ... $slots)
setContents (array $items)
setItem (int $index, Item $item)
setMaxStackSize (int $size)
slotExists (int $slot)
swap (int $slot1, int $slot2)
Public Attributes
const MAX_STACK = 64
const SLOT_INPUT = 0
const SLOT_LAPIS = 1
Protected Member Functions
internalSetContents (array $items)
internalSetItem (int $index, Item $item)
onContentChange (array $itemsBefore)
onSlotChange (int $index, Item $before)
Protected Attributes
$listeners
$maxStackSize = Inventory::MAX_STACK
SplFixedArray $slots
$viewers = []
Detailed Description
Definition at line 30 of file EnchantInventory.php.
Constructor & Destructor Documentation
__construct()
pocketmine\block\inventory\EnchantInventory::__construct (Position $holder)
Definition at line 36 of file EnchantInventory.php.
Member Function Documentation
addItem()
pocketmine\inventory\BaseInventory::addItem (Item ... $slots) inherited
Stores the given Items in the inventory. This will try to fill existing stacks and empty slots as well as it can.
Returns the Items that did not fit.
Returns
Item[]
Implements pocketmine\inventory\Inventory.
Definition at line 187 of file BaseInventory.php.
all()
pocketmine\inventory\BaseInventory::all (Item $item) inherited
Will return all the Items that has the same id and metadata (if not null). Won't check amount
Returns
Item[]
Implements pocketmine\inventory\Inventory.
Definition at line 123 of file BaseInventory.php.
References pocketmine\item\Item\equals().
canAddItem()
pocketmine\inventory\BaseInventory::canAddItem (Item $item) inherited
Checks if a given Item can be added to the inventory
Implements pocketmine\inventory\Inventory.
Reimplemented in pocketmine\block\inventory\ShulkerBoxInventory.
Definition at line 163 of file BaseInventory.php.
clear()
pocketmine\inventory\BaseInventory::clear (int $index) inherited
Will clear a specific slot
Implements pocketmine\inventory\Inventory.
Definition at line 295 of file BaseInventory.php.
Referenced by pocketmine\inventory\transaction\TransactionBuilderInventory\internalSetContents().
clearAll()
pocketmine\inventory\BaseInventory::clearAll () inherited
Clears all the slots
Implements pocketmine\inventory\Inventory.
Definition at line 299 of file BaseInventory.php.
contains()
pocketmine\inventory\BaseInventory::contains (Item $item) inherited
Checks if the inventory contains any Item with the same material data. It will check id, amount, and metadata (if not null)
Implements pocketmine\inventory\Inventory.
Definition at line 107 of file BaseInventory.php.
References pocketmine\item\Item\equals().
first()
pocketmine\inventory\BaseInventory::first (Item $item, bool $exact = false) inherited
Returns the first slot number containing an item with the same ID, damage (if not any-damage), NBT (if not empty) and count >= to the count of the specified item stack.
If $exact is true, only items with equal ID, damage, NBT and count will match.
Implements pocketmine\inventory\Inventory.
Definition at line 135 of file BaseInventory.php.
References pocketmine\item\Item\equals().
firstEmpty()
pocketmine\inventory\BaseInventory::firstEmpty () inherited
Returns the first empty slot, or -1 if not found
Implements pocketmine\inventory\Inventory.
Definition at line 149 of file BaseInventory.php.
getAddableItemQuantity()
pocketmine\inventory\BaseInventory::getAddableItemQuantity (Item $item) inherited
Returns how many items from the given itemstack can be added to this inventory.
Implements pocketmine\inventory\Inventory.
Definition at line 167 of file BaseInventory.php.
References pocketmine\item\Item\canStackWith(), and pocketmine\item\Item\getMaxStackSize().
getContents()
pocketmine\inventory\SimpleInventory::getContents (bool $includeEmpty = false) inherited
Returns
Item[]
Implements pocketmine\inventory\Inventory.
Definition at line 62 of file SimpleInventory.php.
getItem()
pocketmine\inventory\SimpleInventory::getItem (int $index) inherited
Implements pocketmine\inventory\Inventory.
Definition at line 51 of file SimpleInventory.php.
getListeners()
pocketmine\inventory\BaseInventory::getListeners () inherited
Returns
InventoryListener[]|ObjectSet @phpstan-return ObjectSet<InventoryListener>
Implements pocketmine\inventory\Inventory.
Definition at line 372 of file BaseInventory.php.
getMaxStackSize()
pocketmine\inventory\BaseInventory::getMaxStackSize () inherited
Implements pocketmine\inventory\Inventory.
Definition at line 54 of file BaseInventory.php.
getSize()
pocketmine\inventory\SimpleInventory::getSize () inherited
Returns the size of the inventory.
Implements pocketmine\inventory\Inventory.
Definition at line 47 of file SimpleInventory.php.
getViewers()
pocketmine\inventory\BaseInventory::getViewers () inherited
Returns
Player[]
Implements pocketmine\inventory\Inventory.
Definition at line 313 of file BaseInventory.php.
internalSetContents()
pocketmine\inventory\SimpleInventory::internalSetContents (array $items) protected inherited
Parameters
Item[] $items
Reimplemented from pocketmine\inventory\BaseInventory.
Definition at line 76 of file SimpleInventory.php.
internalSetItem()
pocketmine\inventory\SimpleInventory::internalSetItem (int $index, Item $item) protected inherited
Reimplemented from pocketmine\inventory\BaseInventory.
Definition at line 55 of file SimpleInventory.php.
isSlotEmpty()
pocketmine\inventory\BaseInventory::isSlotEmpty (int $index) inherited
Returns whether the given slot is empty.
Implements pocketmine\inventory\Inventory.
Definition at line 159 of file BaseInventory.php.
onClose()
pocketmine\inventory\BaseInventory::onClose (Player $who) inherited
Implements pocketmine\inventory\Inventory.
Definition at line 333 of file BaseInventory.php.
onContentChange()
pocketmine\inventory\BaseInventory::onContentChange (array $itemsBefore) protected inherited
Parameters
Item[] $itemsBefore @phpstan-param array<int, Item> $itemsBefore
Definition at line 354 of file BaseInventory.php.
onOpen()
pocketmine\inventory\BaseInventory::onOpen (Player $who) inherited
Called when a player opens this inventory.
Implements pocketmine\inventory\Inventory.
Definition at line 329 of file BaseInventory.php.
onSlotChange()
pocketmine\inventory\BaseInventory::onSlotChange (int $index, Item $before) protected inherited
Definition at line 337 of file BaseInventory.php.
remove()
pocketmine\inventory\BaseInventory::remove (Item $item) inherited
Will remove all the Items that has the same id and metadata (if not null)
Implements pocketmine\inventory\Inventory.
Definition at line 248 of file BaseInventory.php.
removeAllViewers()
pocketmine\inventory\BaseInventory::removeAllViewers () inherited
Removes the inventory window from all players currently viewing it.
Definition at line 320 of file BaseInventory.php.
removeItem()
pocketmine\inventory\BaseInventory::removeItem (Item ... $slots) inherited
Removes the given Item from the inventory. It will return the Items that couldn't be removed.
Returns
Item[]
Implements pocketmine\inventory\Inventory.
Definition at line 259 of file BaseInventory.php.
setContents()
pocketmine\inventory\BaseInventory::setContents (array $items) inherited
Parameters
Item[] $items
Implements pocketmine\inventory\Inventory.
Definition at line 85 of file BaseInventory.php.
setItem()
pocketmine\inventory\BaseInventory::setItem (int $index, Item $item) inherited
Puts an Item in a slot.
Implements pocketmine\inventory\Inventory.
Reimplemented in pocketmine\crafting\CraftingGrid.
Definition at line 64 of file BaseInventory.php.
Referenced by pocketmine\inventory\transaction\TransactionBuilderInventory\internalSetContents().
setMaxStackSize()
pocketmine\inventory\BaseInventory::setMaxStackSize (int $size) inherited
Implements pocketmine\inventory\Inventory.
Definition at line 58 of file BaseInventory.php.
slotExists()
pocketmine\inventory\BaseInventory::slotExists (int $slot) inherited
Returns whether the specified slot exists in the inventory.
Implements pocketmine\inventory\Inventory.
Definition at line 368 of file BaseInventory.php.
swap()
pocketmine\inventory\BaseInventory::swap (int $slot1, int $slot2) inherited
Swaps the specified slots.
Implements pocketmine\inventory\Inventory.
Definition at line 303 of file BaseInventory.php.
Member Data Documentation
$listeners
pocketmine\inventory\BaseInventory::$listeners protected inherited
Definition at line 48 of file BaseInventory.php.
$maxStackSize
pocketmine\inventory\BaseInventory::$maxStackSize = Inventory::MAX_STACK protected inherited
Definition at line 41 of file BaseInventory.php.
$slots
SplFixedArray pocketmine\inventory\SimpleInventory::$slots protected inherited
Definition at line 37 of file SimpleInventory.php.
$viewers
pocketmine\inventory\BaseInventory::$viewers = [] protected inherited
Definition at line 43 of file BaseInventory.php.
MAX_STACK
const pocketmine\inventory\Inventory::MAX_STACK = 64 inherited
Definition at line 34 of file Inventory.php.
SLOT_INPUT
const pocketmine\block\inventory\EnchantInventory::SLOT_INPUT = 0
Definition at line 33 of file EnchantInventory.php.
SLOT_LAPIS
const pocketmine\block\inventory\EnchantInventory::SLOT_LAPIS = 1
Definition at line 34 of file EnchantInventory.php.
The documentation for this class was generated from the following file:
EnchantInventory.php