PocketMine-MP: pocketmine\entity\effect\HealthBoostEffect Class Reference
pocketmine\entity\effect\HealthBoostEffect Class Reference
Public Member Functions
add (Living $entity, EffectInstance $instance)
applyEffect (Living $entity, EffectInstance $instance, float $potency=1.0, ?Entity $source=null)
canTick (EffectInstance $instance)
getColor ()
getDefaultDuration ()
getName ()
hasBubbles ()
isBad ()
remove (Living $entity, EffectInstance $instance)
Detailed Description
Definition at line 28 of file HealthBoostEffect.php.
Member Function Documentation
add()
pocketmine\entity\effect\HealthBoostEffect::add (Living $entity, EffectInstance $instance)
Applies effects to the entity when the effect is first added.
Reimplemented from pocketmine\entity\effect\Effect.
Definition at line 30 of file HealthBoostEffect.php.
applyEffect()
pocketmine\entity\effect\Effect::applyEffect (Living $entity, EffectInstance $instance, float $potency = 1.0, ?Entity $source = null) inherited
Applies effect results to an entity. This will not be called unless canTick() returns true.
Reimplemented in pocketmine\entity\effect\HungerEffect, pocketmine\entity\effect\InstantDamageEffect, pocketmine\entity\effect\InstantHealthEffect, pocketmine\entity\effect\LevitationEffect, pocketmine\entity\effect\PoisonEffect, pocketmine\entity\effect\RegenerationEffect, pocketmine\entity\effect\SaturationEffect, and pocketmine\entity\effect\WitherEffect.
Definition at line 97 of file Effect.php.
canTick()
pocketmine\entity\effect\Effect::canTick (EffectInstance $instance) inherited
Returns whether the effect will do something on the current tick.
Reimplemented in pocketmine\entity\effect\HungerEffect, pocketmine\entity\effect\InstantEffect, pocketmine\entity\effect\LevitationEffect, pocketmine\entity\effect\PoisonEffect, pocketmine\entity\effect\RegenerationEffect, and pocketmine\entity\effect\WitherEffect.
Definition at line 90 of file Effect.php.
getColor()
pocketmine\entity\effect\Effect::getColor () inherited
Returns a Color object representing this effect's particle colour.
Definition at line 61 of file Effect.php.
Referenced by pocketmine\entity\effect\EffectInstance\__construct().
getDefaultDuration()
pocketmine\entity\effect\Effect::getDefaultDuration () inherited
Returns the default duration (in ticks) this effect will apply for if a duration is not specified.
Definition at line 76 of file Effect.php.
Referenced by pocketmine\entity\effect\EffectInstance\__construct().
getName()
pocketmine\entity\effect\Effect::getName () inherited
Returns the translation key used to translate this effect's name.
Definition at line 54 of file Effect.php.
hasBubbles()
pocketmine\entity\effect\Effect::hasBubbles () inherited
Returns whether this effect will give the subject potion bubbles.
Definition at line 83 of file Effect.php.
isBad()
pocketmine\entity\effect\Effect::isBad () inherited
Returns whether this effect is harmful. TODO: implement inverse effect results for undead mobs
Definition at line 69 of file Effect.php.
remove()
pocketmine\entity\effect\HealthBoostEffect::remove (Living $entity, EffectInstance $instance)
Removes the effect from the entity, resetting any changed values back to their original defaults.
Reimplemented from pocketmine\entity\effect\Effect.
Definition at line 34 of file HealthBoostEffect.php.
References pocketmine\entity\Living\setHealth().
The documentation for this class was generated from the following file:
HealthBoostEffect.php