PocketMine-MP: pocketmine Namespace Reference
pocketmine Namespace Reference
Namespaces
namespace block
namespace command
namespace entity
namespace event
namespace inventory
namespace item
namespace math
namespace nbt
namespace network
namespace permission
namespace plugin
namespace scheduler
namespace utils
namespace wizard
namespace world
Classes
class BootstrapOptions
class MemoryManager
class Server
class ServerConfigGroup
class ServerProperties
class TimeTrackingSleeperHandler
class VersionInfo
class YmlServerProperties
Functions
check_platform_dependencies ()
critical_error ($message)
emit_performance_warnings (\Logger $logger)
getopt_string (string $opt)
server ()
set_ini_entries ()
Variables
const _CORE_CONSTANTS_INCLUDED (defined('pocketmine\_CORE_CONSTANTS_INCLUDED')) true
const BEDROCK_BLOCK_UPGRADE_SCHEMA_PATH dirname(__DIR__) . '/vendor/pocketmine/bedrock-block-upgrade-schema/'
const BEDROCK_DATA_PATH dirname(__DIR__) . '/vendor/pocketmine/bedrock-data/'
const BEDROCK_ITEM_UPGRADE_SCHEMA_PATH dirname(__DIR__) . '/vendor/pocketmine/bedrock-item-upgrade-schema/'
const COMPOSER_AUTOLOADER_PATH dirname(__DIR__) . '/vendor/autoload.php'
const LOCALE_DATA_PATH dirname(__DIR__) . '/vendor/pocketmine/locale-data/'
const MIN_PHP_VERSION = "8.1.0"
const PATH dirname(__DIR__) . '/'
const RESOURCE_PATH dirname(__DIR__) . '/resources/'
Detailed Description
PocketMine-MP is the Minecraft: PE multiplayer server software Homepage: http://www.pocketmine.net/
Function Documentation
check_platform_dependencies()
pocketmine\check_platform_dependencies ()
Returns
string[]
Definition at line 73 of file PocketMine.php.
critical_error()
pocketmine\critical_error ($message)
Parameters
string $message
Returns
void
Definition at line 60 of file PocketMine.php.
Referenced by server().
emit_performance_warnings()
pocketmine\emit_performance_warnings (\Logger $logger)
Returns
void
Definition at line 168 of file PocketMine.php.
References Logger\warning().
getopt_string()
pocketmine\getopt_string (string $opt)
Definition at line 212 of file PocketMine.php.
server()
pocketmine\server ()
Returns
void
Definition at line 231 of file PocketMine.php.
References critical_error().
Referenced by pocketmine\world\World\__construct(), pocketmine\updater\UpdateChecker\checkUpdateCallback(), pocketmine\updater\UpdateChecker\doCheck(), pocketmine\MemoryManager\dumpServerMemory(), pocketmine\updater\UpdateChecker\getChannel(), pocketmine\plugin\PluginBase\getCommand(), pocketmine\player\Player\getItemUseDuration(), pocketmine\entity\Entity\getOwningEntity(), pocketmine\player\Player\getSpawn(), pocketmine\entity\Entity\getTargetEntity(), pocketmine\network\mcpe\handler\LoginPacketHandler\processLogin(), pocketmine\player\Player\resetItemCooldown(), pocketmine\player\Player\save(), pocketmine\player\Player\sendSkin(), pocketmine\network\mcpe\raklib\RakLibInterface\shutdown(), and pocketmine\MemoryManager\trigger().
set_ini_entries()
pocketmine\set_ini_entries ()
Returns
void
Definition at line 204 of file PocketMine.php.
Variable Documentation
_CORE_CONSTANTS_INCLUDED
const pocketmine\_CORE_CONSTANTS_INCLUDED(defined('pocketmine\_CORE_CONSTANTS_INCLUDED')) (defined('pocketmine\_CORE_CONSTANTS_INCLUDED')) true
Definition at line 34 of file CoreConstants.php.
BEDROCK_BLOCK_UPGRADE_SCHEMA_PATH
const pocketmine\BEDROCK_BLOCK_UPGRADE_SCHEMA_PATH dirname(__DIR__) . '/vendor/pocketmine/bedrock-block-upgrade-schema/'
Definition at line 40 of file CoreConstants.php.
BEDROCK_DATA_PATH
const pocketmine\BEDROCK_DATA_PATH dirname(__DIR__) . '/vendor/pocketmine/bedrock-data/'
Definition at line 38 of file CoreConstants.php.
BEDROCK_ITEM_UPGRADE_SCHEMA_PATH
const pocketmine\BEDROCK_ITEM_UPGRADE_SCHEMA_PATH dirname(__DIR__) . '/vendor/pocketmine/bedrock-item-upgrade-schema/'
Definition at line 41 of file CoreConstants.php.
COMPOSER_AUTOLOADER_PATH
const pocketmine\COMPOSER_AUTOLOADER_PATH dirname(__DIR__) . '/vendor/autoload.php'
Definition at line 42 of file CoreConstants.php.
LOCALE_DATA_PATH
const pocketmine\LOCALE_DATA_PATH dirname(__DIR__) . '/vendor/pocketmine/locale-data/'
Definition at line 39 of file CoreConstants.php.
MIN_PHP_VERSION
const pocketmine\MIN_PHP_VERSION = "8.1.0"
Definition at line 54 of file PocketMine.php.
PATH
const pocketmine\PATH dirname(__DIR__) . '/'
Definition at line 36 of file CoreConstants.php.
RESOURCE_PATH
const pocketmine\RESOURCE_PATH dirname(__DIR__) . '/resources/'
Definition at line 37 of file CoreConstants.php.