PocketMine-MP: pocketmine\item\Hoe Class Reference
pocketmine\item\Hoe Class Reference
Public Member Functions
__clone ()
__toString ()
applyDamage (int $amount)
canBePlaced ()
canStackWith (Item $other)
clearCustomBlockData ()
clearCustomName ()
clearNamedTag ()
equals (Item $item, bool $checkDamage=true, bool $checkCompound=true)
equalsExact (Item $other)
getAttackPoints ()
getBlock (?int $clickedFace=null)
getBlockToolHarvestLevel ()
getBlockToolType ()
getCanDestroy ()
getCanPlaceOn ()
getCooldownTicks ()
getCount ()
getCustomBlockData ()
getCustomName ()
getDamage ()
getDefensePoints ()
getFuelResidue ()
getFuelTime ()
getId ()
getLore ()
getMaxDurability ()
getMaxStackSize ()
getMeta ()
getMiningEfficiency (bool $isCorrectTool)
getName ()
getNamedTag ()
getTier ()
getVanillaName ()
hasAnyDamageValue ()
hasCustomBlockData ()
hasCustomName ()
hasNamedTag ()
isBroken ()
isNull ()
isUnbreakable ()
jsonSerialize ()
nbtSerialize (int $slot=-1)
onAttackEntity (Entity $victim)
onClickAir (Player $player, Vector3 $directionVector)
onDestroyBlock (Block $block)
onInteractBlock (Player $player, Block $blockReplace, Block $blockClicked, int $face, Vector3 $clickVector)
onReleaseUsing (Player $player)
pop (int $count=1)
setCanDestroy (array $canDestroy)
setCanPlaceOn (array $canPlaceOn)
setCount (int $count)
setCustomBlockData (CompoundTag $compound)
setCustomName (string $name)
setDamage (int $damage)
setLore (array $lines)
setNamedTag (CompoundTag $tag)
setUnbreakable (bool $value=true)
Static Public Member Functions
static jsonDeserialize (array $data)
static nbtDeserialize (CompoundTag $tag)
Public Attributes
const TAG_BLOCK_ENTITY_TAG = "BlockEntityTag"
const TAG_DISPLAY = "display"
const TAG_DISPLAY_LORE = "Lore"
const TAG_DISPLAY_NAME = "Name"
const TAG_ENCH = "ench"
Protected Member Functions
deserializeCompoundTag (CompoundTag $tag)
getBaseMiningEfficiency ()
getUnbreakingDamageReduction (int $amount)
onBroken ()
serializeCompoundTag (CompoundTag $tag)
Protected Attributes
$blockEntityTag = null
$canDestroy
$canPlaceOn = []
$count = 1
$customName = ""
$damage = 0
$lore = []
$name
$tier
Detailed Description
Definition at line 30 of file Hoe.php.
Member Function Documentation
__clone()
pocketmine\item\Item::__clone () inherited
Definition at line 710 of file Item.php.
__toString()
pocketmine\item\Item::__toString () final inherited
Definition at line 590 of file Item.php.
applyDamage()
pocketmine\item\Durable::applyDamage (int $amount) inherited
Applies damage to the item.
Returns
bool if any damage was applied to the item
Definition at line 64 of file Durable.php.
Referenced by pocketmine\item\FlintSteel\onInteractBlock().
canBePlaced()
pocketmine\item\Item::canBePlaced () final inherited
Definition at line 432 of file Item.php.
canStackWith()
pocketmine\item\Item::canStackWith (Item $other) final inherited
Returns whether this item could stack with the given item (ignoring stack size and count).
Definition at line 579 of file Item.php.
Referenced by pocketmine\inventory\BaseInventory\getAddableItemQuantity().
clearCustomBlockData()
pocketmine\item\Item::clearCustomBlockData () inherited
Returns
$this
Definition at line 123 of file Item.php.
clearCustomName()
pocketmine\item\Item::clearCustomName () inherited
Returns
$this
Definition at line 161 of file Item.php.
clearNamedTag()
pocketmine\item\Item::clearNamedTag () inherited
Removes the Item's NBT.
Returns
$this
Exceptions
NbtException
Definition at line 263 of file Item.php.
deserializeCompoundTag()
pocketmine\item\Durable::deserializeCompoundTag (CompoundTag $tag) protected inherited
Exceptions
NbtException
Reimplemented from pocketmine\item\Item.
Reimplemented in pocketmine\item\Armor.
Definition at line 127 of file Durable.php.
equals()
pocketmine\item\Item::equals (Item $item, bool $checkDamage = true, bool $checkCompound = true) final inherited
Compares an Item to this Item and check if they match.
Parameters
bool $checkDamage Whether to verify that the damage values match.
bool $checkCompound Whether to verify that the items' NBT match.
Definition at line 570 of file Item.php.
Referenced by pocketmine\inventory\BaseInventory\all(), pocketmine\inventory\BaseInventory\contains(), pocketmine\inventory\BaseInventory\first(), and pocketmine\inventory\BaseInventory\remove().
equalsExact()
pocketmine\item\Item::equalsExact (Item $other) final inherited
Returns whether the specified item stack has the same ID, damage, NBT and count as this item stack.
Definition at line 586 of file Item.php.
getAttackPoints()
pocketmine\item\Item::getAttackPoints () inherited
Returns how many points of damage this item will deal to an entity when used as a weapon.
Reimplemented in pocketmine\item\Axe, pocketmine\item\Pickaxe, pocketmine\item\Shovel, and pocketmine\item\Sword.
Definition at line 486 of file Item.php.
getBaseMiningEfficiency()
pocketmine\item\TieredTool::getBaseMiningEfficiency () protected inherited
Reimplemented from pocketmine\item\Tool.
Definition at line 44 of file TieredTool.php.
getBlock()
pocketmine\item\Item::getBlock (?int $clickedFace = null) inherited
Returns the block corresponding to this Item.
Reimplemented in pocketmine\item\Bamboo, pocketmine\item\Bed, pocketmine\item\BeetrootSeeds, pocketmine\item\Carrot, pocketmine\item\CocoaBeans, pocketmine\item\ItemBlock, pocketmine\item\ItemBlockWallOrFloor, pocketmine\item\MelonSeeds, pocketmine\item\Potato, pocketmine\item\PumpkinSeeds, pocketmine\item\Redstone, pocketmine\item\Skull, pocketmine\item\StringItem, pocketmine\item\SweetBerries, and pocketmine\item\WheatSeeds.
Definition at line 439 of file Item.php.
getBlockToolHarvestLevel()
pocketmine\item\Item::getBlockToolHarvestLevel () inherited
Returns the harvesting power that this tool has. This affects what blocks it can mine when the tool type matches the mined block. This should return 1 for non-tiered tools, and the tool tier for tiered tools.
See also
BlockBreakInfo::getToolHarvestLevel()
Reimplemented in pocketmine\item\Axe, pocketmine\item\Pickaxe, pocketmine\item\Shears, pocketmine\item\Shovel, and pocketmine\item\Sword.
Definition at line 512 of file Item.php.
getBlockToolType()
pocketmine\item\Hoe::getBlockToolType ()
Returns what type of block-breaking tool this is. Blocks requiring the same tool type as the item will break faster (except for blocks requiring no tool, which break at the same speed regardless of the tool used)
Reimplemented from pocketmine\item\Item.
Definition at line 32 of file Hoe.php.
getCanDestroy()
pocketmine\item\Item::getCanDestroy () inherited
Returns
string[] @phpstan-return array<string, string>
Definition at line 211 of file Item.php.
getCanPlaceOn()
pocketmine\item\Item::getCanPlaceOn () inherited
Returns
string[] @phpstan-return array<string, string>
Definition at line 193 of file Item.php.
getCooldownTicks()
pocketmine\item\Item::getCooldownTicks () inherited
Returns the number of ticks a player must wait before activating this item again.
Reimplemented in pocketmine\item\ChorusFruit, and pocketmine\item\EnderPearl.
Definition at line 560 of file Item.php.
getCount()
pocketmine\item\Item::getCount () inherited
Definition at line 382 of file Item.php.
getCustomBlockData()
pocketmine\item\Item::getCustomBlockData () inherited
Definition at line 137 of file Item.php.
getCustomName()
pocketmine\item\Item::getCustomName () inherited
Definition at line 145 of file Item.php.
getDamage()
pocketmine\item\Durable::getDamage () inherited
Definition at line 79 of file Durable.php.
getDefensePoints()
pocketmine\item\Item::getDefensePoints () inherited
Returns how many armor points can be gained by wearing this item.
Reimplemented in pocketmine\item\Armor.
Definition at line 493 of file Item.php.
getFuelResidue()
pocketmine\item\Item::getFuelResidue () inherited
Returns an item after burning fuel
Reimplemented in pocketmine\item\LiquidBucket.
Definition at line 476 of file Item.php.
getFuelTime()
pocketmine\item\TieredTool::getFuelTime () inherited
Returns the time in ticks which the item will fuel a furnace for.
Reimplemented from pocketmine\item\Item.
Definition at line 48 of file TieredTool.php.
getId()
pocketmine\item\Item::getId () final inherited
Definition at line 443 of file Item.php.
getLore()
pocketmine\item\Item::getLore () inherited
Returns
string[]
Definition at line 169 of file Item.php.
getMaxDurability()
pocketmine\item\TieredTool::getMaxDurability () inherited
Returns the maximum amount of damage this item can take before it breaks.
Reimplemented from pocketmine\item\Durable.
Definition at line 36 of file TieredTool.php.
getMaxStackSize()
pocketmine\item\Tool::getMaxStackSize () inherited
Returns the highest amount of this item which will fit into one inventory slot.
Reimplemented from pocketmine\item\Item.
Definition at line 30 of file Tool.php.
getMeta()
pocketmine\item\Durable::getMeta () inherited
Reimplemented from pocketmine\item\Item.
Definition at line 38 of file Durable.php.
getMiningEfficiency()
pocketmine\item\Tool::getMiningEfficiency (bool $isCorrectTool) inherited
Reimplemented from pocketmine\item\Item.
Definition at line 34 of file Tool.php.
getName()
pocketmine\item\Item::getName () final inherited
Returns the name of the item, or the custom name if it is set.
Definition at line 421 of file Item.php.
getNamedTag()
pocketmine\item\Item::getNamedTag () inherited
Returns a tree of Tag objects representing the Item's NBT. If the item does not have any NBT, an empty CompoundTag object is returned to allow the caller to manipulate and apply back to the item.
Definition at line 236 of file Item.php.
getTier()
pocketmine\item\TieredTool::getTier () inherited
Definition at line 40 of file TieredTool.php.
getUnbreakingDamageReduction()
pocketmine\item\Durable::getUnbreakingDamageReduction (int $amount) protected inherited
Definition at line 91 of file Durable.php.
getVanillaName()
pocketmine\item\Item::getVanillaName () inherited
Returns the vanilla name of the item, disregarding custom names.
Definition at line 428 of file Item.php.
hasAnyDamageValue()
pocketmine\item\Item::hasAnyDamageValue () inherited
Returns whether this item can match any item with an equivalent ID with any meta value. Used in crafting recipes which accept multiple variants of the same item, for example crafting tables recipes.
Definition at line 455 of file Item.php.
Referenced by pocketmine\inventory\BaseInventory\remove().
hasCustomBlockData()
pocketmine\item\Item::hasCustomBlockData () inherited
Definition at line 116 of file Item.php.
hasCustomName()
pocketmine\item\Item::hasCustomName () inherited
Definition at line 141 of file Item.php.
hasNamedTag()
pocketmine\item\Item::hasNamedTag () inherited
Returns whether this Item has a non-empty NBT.
Definition at line 228 of file Item.php.
Referenced by pocketmine\inventory\BaseInventory\remove().
isBroken()
pocketmine\item\Durable::isBroken () inherited
Returns whether the item is broken.
Definition at line 123 of file Durable.php.
Referenced by pocketmine\player\Player\breakBlock(), and pocketmine\player\Player\interactBlock().
isNull()
pocketmine\item\Item::isNull () inherited
Definition at line 414 of file Item.php.
isUnbreakable()
pocketmine\item\Durable::isUnbreakable () inherited
Returns whether this item will take damage when used.
Definition at line 45 of file Durable.php.
jsonDeserialize()
static pocketmine\item\Item::jsonDeserialize (array $data) static final inherited
Returns an Item from properties created in an array by Item#jsonSerialize
Parameters
mixed[] $data @phpstan-param array{ id: int, damage?: int, count?: int, nbt?: string, nbt_hex?: string, nbt_b64?: string } $data
Exceptions
NbtDataException
InvalidArgumentException
Definition at line 635 of file Item.php.
jsonSerialize()
pocketmine\item\Item::jsonSerialize () final inherited
Returns an array of item stack properties that can be serialized to json.
Returns
mixed[] @phpstan-return array{id: int, damage?: int, count?: int, nbt_b64?: string}
Definition at line 600 of file Item.php.
nbtDeserialize()
static pocketmine\item\Item::nbtDeserialize (CompoundTag $tag) static inherited
Deserializes an Item from an NBT CompoundTag
Exceptions
NbtException
SavedDataLoadingException
Definition at line 679 of file Item.php.
nbtSerialize()
pocketmine\item\Item::nbtSerialize (int $slot = -1) inherited
Serializes the item to an NBT CompoundTag
Parameters
int $slot optional, the inventory slot of the item
Definition at line 656 of file Item.php.
onAttackEntity()
pocketmine\item\Hoe::onAttackEntity (Entity $victim)
Called when this item is used to attack an entity. Usually used to update durability.
Reimplemented from pocketmine\item\Item.
Definition at line 36 of file Hoe.php.
onBroken()
pocketmine\item\Durable::onBroken () protected inherited
Called when the item's damage exceeds its maximum durability.
Definition at line 111 of file Durable.php.
onClickAir()
pocketmine\item\Item::onClickAir (Player $player, Vector3 $directionVector) inherited
Called when a player uses the item on air, for example throwing a projectile. Returns whether the item was changed, for example count decrease or durability change.
Reimplemented in pocketmine\item\Armor, and pocketmine\item\ProjectileItem.
Definition at line 531 of file Item.php.
onDestroyBlock()
pocketmine\item\Hoe::onDestroyBlock (Block $block)
Called when this item is used to destroy a block. Usually used to update durability.
Reimplemented from pocketmine\item\Item.
Definition at line 40 of file Hoe.php.
onInteractBlock()
pocketmine\item\Item::onInteractBlock (Player $player, Block $blockReplace, Block $blockClicked, int $face, Vector3 $clickVector) inherited
Called when a player uses this item on a block.
Reimplemented in pocketmine\item\Bucket, pocketmine\item\FlintSteel, pocketmine\item\LiquidBucket, pocketmine\item\PaintingItem, and pocketmine\item\SpawnEgg.
Definition at line 523 of file Item.php.
onReleaseUsing()
pocketmine\item\Item::onReleaseUsing (Player $player) inherited
Called when a player is using this item and releases it. Used to handle bow shoot actions. Returns whether the item was changed, for example count decrease or durability change.
Reimplemented in pocketmine\item\Bow.
Definition at line 539 of file Item.php.
pop()
pocketmine\item\Item::pop (int $count = 1) inherited
Pops an item from the stack and returns it, decreasing the stack count of this item stack by one.
Returns
static A clone of this itemstack containing the amount of items that were removed from this stack.
Exceptions
InvalidArgumentException if trying to pop more items than are on the stack
Definition at line 401 of file Item.php.
Referenced by pocketmine\block\Bamboo\onInteract(), pocketmine\block\BambooSapling\onInteract(), pocketmine\block\CocoaBlock\onInteract(), pocketmine\block\Crops\onInteract(), pocketmine\block\Jukebox\onInteract(), pocketmine\block\Lectern\onInteract(), pocketmine\block\Sapling\onInteract(), pocketmine\block\Sugarcane\onInteract(), and pocketmine\block\SweetBerryBush\onInteract().
serializeCompoundTag()
pocketmine\item\Durable::serializeCompoundTag (CompoundTag $tag) protected inherited
Reimplemented from pocketmine\item\Item.
Definition at line 132 of file Durable.php.
setCanDestroy()
pocketmine\item\Item::setCanDestroy (array $canDestroy) inherited
Parameters
string[] $canDestroy
Definition at line 218 of file Item.php.
setCanPlaceOn()
pocketmine\item\Item::setCanPlaceOn (array $canPlaceOn) inherited
Parameters
string[] $canPlaceOn
Definition at line 200 of file Item.php.
setCount()
pocketmine\item\Item::setCount (int $count) inherited
Returns
$this
Definition at line 389 of file Item.php.
setCustomBlockData()
pocketmine\item\Item::setCustomBlockData (CompoundTag $compound) inherited
Returns
$this
Definition at line 131 of file Item.php.
Referenced by pocketmine\block\Block\getPickedItem().
setCustomName()
pocketmine\item\Item::setCustomName (string $name) inherited
Returns
$this
Definition at line 152 of file Item.php.
setDamage()
pocketmine\item\Durable::setDamage (int $damage) inherited
Definition at line 83 of file Durable.php.
setLore()
pocketmine\item\Item::setLore (array $lines) inherited
Parameters
string[] $lines
Returns
$this
Definition at line 178 of file Item.php.
setNamedTag()
pocketmine\item\Item::setNamedTag (CompoundTag $tag) inherited
Sets the Item's NBT from the supplied CompoundTag object.
Returns
$this
Exceptions
NbtException
Definition at line 247 of file Item.php.
setUnbreakable()
pocketmine\item\Durable::setUnbreakable (bool $value = true) inherited
Sets whether the item will take damage when used.
Returns
$this
Definition at line 54 of file Durable.php.
Member Data Documentation
$blockEntityTag
pocketmine\item\Item::$blockEntityTag = null protected inherited
Definition at line 87 of file Item.php.
$canDestroy
pocketmine\item\Item::$canDestroy protected inherited
Definition at line 98 of file Item.php.
$canPlaceOn
pocketmine\item\Item::$canPlaceOn = [] protected inherited
Definition at line 93 of file Item.php.
$count
pocketmine\item\Item::$count = 1 protected inherited
Definition at line 73 of file Item.php.
$customName
pocketmine\item\Item::$customName = "" protected inherited
Definition at line 80 of file Item.php.
$damage
pocketmine\item\Durable::$damage = 0 protected inherited
Definition at line 34 of file Durable.php.
$lore
pocketmine\item\Item::$lore = [] protected inherited
Definition at line 82 of file Item.php.
$name
pocketmine\item\Item::$name protected inherited
Definition at line 75 of file Item.php.
$tier
pocketmine\item\TieredTool::$tier protected inherited
Definition at line 29 of file TieredTool.php.
TAG_BLOCK_ENTITY_TAG
const pocketmine\item\Item::TAG_BLOCK_ENTITY_TAG = "BlockEntityTag" inherited
Definition at line 63 of file Item.php.
TAG_DISPLAY
const pocketmine\item\Item::TAG_DISPLAY = "display" inherited
Definition at line 62 of file Item.php.
TAG_DISPLAY_LORE
const pocketmine\item\Item::TAG_DISPLAY_LORE = "Lore" inherited
Definition at line 66 of file Item.php.
TAG_DISPLAY_NAME
const pocketmine\item\Item::TAG_DISPLAY_NAME = "Name" inherited
Definition at line 65 of file Item.php.
TAG_ENCH
const pocketmine\item\Item::TAG_ENCH = "ench" inherited
Definition at line 61 of file Item.php.
The documentation for this class was generated from the following file:
Hoe.php