PocketMine-MP: pocketmine\block\Flower Class Reference
pocketmine\block\Flower Class Reference
Public Member Functions
__clone ()
__toString ()
addVelocityToEntity (Entity $entity)
asItem ()
blocksDirectSkyLight ()
burnsForever ()
calculateIntercept (Vector3 $pos1, Vector3 $pos2)
canBeFlowedInto ()
canBePlaced ()
canBePlacedAt (Block $blockReplace, Vector3 $clickVector, int $face, bool $isClickedBlock)
canBeReplaced ()
canClimb ()
collidesWithBB (AxisAlignedBB $bb)
getAffectedBlocks ()
getAllSides ()
getBreakInfo ()
getCollisionBoxes ()
getDrops (Item $item)
getDropsForCompatibleTool (Item $item)
getDropsForIncompatibleTool (Item $item)
getFlameEncouragement ()
getFlammability ()
getFrictionFactor ()
getFuelTime ()
getFullId ()
getHorizontalSides ()
getId ()
getIdInfo ()
getLightFilter ()
getLightLevel ()
getMaxStackSize ()
getMeta ()
getModelPositionOffset ()
getName ()
getPickedItem (bool $addUserData=false)
getPosition ()
getSide (int $side, int $step=1)
getSilkTouchDrops (Item $item)
getStateBitmask ()
getTypeId ()
getXpDropForTool (Item $item)
hasEntityCollision ()
isAffectedBySilkTouch ()
isFlammable ()
isFullCube ()
isSameState (Block $other)
isSameType (Block $other)
isSolid ()
isTransparent ()
onAttack (Item $item, int $face, ?Player $player=null)
onBreak (Item $item, ?Player $player=null)
onEntityInside (Entity $entity)
onEntityLand (Entity $entity)
onIncinerate ()
onInteract (Item $item, int $face, Vector3 $clickVector, ?Player $player=null)
onNearbyBlockChange ()
onPostPlace ()
onRandomTick ()
onScheduledUpdate ()
place (BlockTransaction $tx, Item $item, Block $blockReplace, Block $blockClicked, int $face, Vector3 $clickVector, ?Player $player=null)
position (World $world, int $x, int $y, int $z)
readStateFromData (int $id, int $stateMeta)
readStateFromWorld ()
ticksRandomly ()
writeStateToWorld ()
Public Attributes
const INTERNAL_METADATA_BITS = 4
const INTERNAL_METADATA_MASK = ~(~0 << self::INTERNAL_METADATA_BITS)
Protected Member Functions
getXpDropAmount ()
recalculateCollisionBoxes ()
writeStateToItemMeta ()
writeStateToMeta ()
Protected Attributes
BlockBreakInfo $breakInfo
array $collisionBoxes = null
string $fallbackName
BlockIdentifier $idInfo
Position $position
Detailed Description
Definition at line 32 of file Flower.php.
Member Function Documentation
__clone()
pocketmine\block\Block::__clone () inherited
Definition at line 76 of file Block.php.
__toString()
pocketmine\block\Block::__toString () inherited
Returns
string
Definition at line 546 of file Block.php.
addVelocityToEntity()
pocketmine\block\Block::addVelocityToEntity (Entity $entity) inherited
Definition at line 342 of file Block.php.
asItem()
pocketmine\block\Block::asItem () inherited
Definition at line 99 of file Block.php.
blocksDirectSkyLight()
pocketmine\block\Block::blocksDirectSkyLight () inherited
Returns whether this block blocks direct sky light from passing through it. This is independent from the light filter value, which is used during propagation.
In most cases, this is the same as isTransparent(); however, some special cases exist such as leaves and cobwebs, which don't have any additional effect on light propagation, but don't allow direct sky light to pass through.
Reimplemented in pocketmine\block\Cobweb, and pocketmine\block\Leaves.
Definition at line 312 of file Block.php.
burnsForever()
pocketmine\block\Block::burnsForever () inherited
Returns whether fire lit on this block will burn indefinitely.
Reimplemented in pocketmine\block\Bedrock, pocketmine\block\Magma, and pocketmine\block\Netherrack.
Definition at line 476 of file Block.php.
calculateIntercept()
pocketmine\block\Block::calculateIntercept (Vector3 $pos1, Vector3 $pos2) inherited
Definition at line 619 of file Block.php.
canBeFlowedInto()
pocketmine\block\Flowable::canBeFlowedInto () inherited
AKA: Block->isFlowable
Reimplemented from pocketmine\block\Block.
Reimplemented in pocketmine\block\UnderwaterTorch.
Definition at line 30 of file Flowable.php.
canBePlaced()
pocketmine\block\Block::canBePlaced () inherited
AKA: Block->isPlaceable
Reimplemented in pocketmine\block\Air, and pocketmine\block\UnknownBlock.
Definition at line 196 of file Block.php.
canBePlacedAt()
pocketmine\block\Block::canBePlacedAt (Block $blockReplace, Vector3 $clickVector, int $face, bool $isClickedBlock) inherited
Definition at line 204 of file Block.php.
canBeReplaced()
pocketmine\block\Block::canBeReplaced () inherited
Definition at line 200 of file Block.php.
canClimb()
pocketmine\block\Block::canClimb () inherited
Returns whether entities can climb up this block.
Reimplemented in pocketmine\block\Ladder, and pocketmine\block\Vine.
Definition at line 338 of file Block.php.
collidesWithBB()
pocketmine\block\Block::collidesWithBB (AxisAlignedBB $bb) inherited
Checks for collision against an AxisAlignedBB
Definition at line 553 of file Block.php.
References pocketmine\math\AxisAlignedBB\intersectsWith().
getAffectedBlocks()
pocketmine\block\Block::getAffectedBlocks () inherited
Returns a list of blocks that this block is part of. In most cases, only contains the block itself, but in cases such as double plants, beds and doors, will contain both halves.
Returns
Block[]
Reimplemented in pocketmine\block\Bed, pocketmine\block\Door, and pocketmine\block\DoublePlant.
Definition at line 539 of file Block.php.
getAllSides()
pocketmine\block\Block::getAllSides () inherited
Returns the six blocks around this block.
Returns
Block[]|\Generator @phpstan-return \Generator<int, Block, void, void>
Definition at line 526 of file Block.php.
getBreakInfo()
pocketmine\block\Block::getBreakInfo () inherited
Returns an object containing information about the destruction requirements of this block.
Definition at line 223 of file Block.php.
getCollisionBoxes()
pocketmine\block\Block::getCollisionBoxes () final inherited
Returns
AxisAlignedBB[]
Definition at line 585 of file Block.php.
getDrops()
pocketmine\block\Block::getDrops (Item $item) inherited
Returns an array of Item objects to be dropped
Returns
Item[]
Reimplemented in pocketmine\block\Bed, pocketmine\block\Door, pocketmine\block\DoublePlant, pocketmine\block\Lectern, pocketmine\block\NetherPortal, pocketmine\block\UnknownBlock, and pocketmine\block\Vine.
Definition at line 362 of file Block.php.
getDropsForCompatibleTool()
pocketmine\block\Block::getDropsForCompatibleTool (Item $item) inherited
Returns an array of Items to be dropped when the block is broken using the correct tool type.
Returns
Item[]
Reimplemented in pocketmine\block\BaseBanner, pocketmine\block\BaseCoral, pocketmine\block\Beetroot, pocketmine\block\BlueIce, pocketmine\block\Bookshelf, pocketmine\block\BrownMushroomBlock, pocketmine\block\Cake, pocketmine\block\Carrot, pocketmine\block\Clay, pocketmine\block\CoalOre, pocketmine\block\Cobweb, pocketmine\block\CocoaBlock, pocketmine\block\CoralBlock, pocketmine\block\DiamondOre, pocketmine\block\EmeraldOre, pocketmine\block\EnderChest, pocketmine\block\Farmland, pocketmine\block\Fire, pocketmine\block\FlowerPot, pocketmine\block\Glass, pocketmine\block\GlassPane, pocketmine\block\Glowstone, pocketmine\block\Grass, pocketmine\block\GrassPath, pocketmine\block\Gravel, pocketmine\block\Ice, pocketmine\block\InfestedStone, pocketmine\block\ItemFrame, pocketmine\block\Jukebox, pocketmine\block\LapisOre, pocketmine\block\Leaves, pocketmine\block\Liquid, pocketmine\block\Melon, pocketmine\block\MonsterSpawner, pocketmine\block\MushroomStem, pocketmine\block\Mycelium, pocketmine\block\NetherQuartzOre, pocketmine\block\NetherReactor, pocketmine\block\NetherWartPlant, pocketmine\block\PackedIce, pocketmine\block\Podzol, pocketmine\block\Potato, pocketmine\block\RedMushroomBlock, pocketmine\block\RedstoneOre, pocketmine\block\SeaLantern, pocketmine\block\SeaPickle, pocketmine\block\ShulkerBox, pocketmine\block\Slab, pocketmine\block\Snow, pocketmine\block\SnowLayer, pocketmine\block\Stem, pocketmine\block\SweetBerryBush, and pocketmine\block\Wheat.
Definition at line 379 of file Block.php.
getDropsForIncompatibleTool()
pocketmine\block\Block::getDropsForIncompatibleTool (Item $item) inherited
Returns the items dropped by this block when broken with an incorrect tool type (or tool with a too-low tier).
Returns
Item[]
Reimplemented in pocketmine\block\DeadBush, pocketmine\block\DoubleTallGrass, and pocketmine\block\TallGrass.
Definition at line 388 of file Block.php.
getFlameEncouragement()
pocketmine\block\Flower::getFlameEncouragement ()
Returns the chance that the block will catch fire from nearby fire sources. Higher values lead to faster catching fire.
Reimplemented from pocketmine\block\Block.
Definition at line 49 of file Flower.php.
getFlammability()
pocketmine\block\Flower::getFlammability ()
Returns the base flammability of this block. Higher values lead to the block burning away more quickly.
Reimplemented from pocketmine\block\Block.
Definition at line 53 of file Flower.php.
getFrictionFactor()
pocketmine\block\Block::getFrictionFactor () inherited
Definition at line 284 of file Block.php.
getFuelTime()
pocketmine\block\Block::getFuelTime () inherited
Returns the time in ticks which the block will fuel a furnace for.
Reimplemented in pocketmine\block\Barrel, pocketmine\block\Bookshelf, pocketmine\block\Chest, pocketmine\block\Coal, pocketmine\block\CraftingTable, pocketmine\block\DaylightSensor, pocketmine\block\DriedKelp, pocketmine\block\FenceGate, pocketmine\block\FletchingTable, pocketmine\block\Jukebox, pocketmine\block\Note, pocketmine\block\Planks, pocketmine\block\Sapling, pocketmine\block\Wood, pocketmine\block\WoodenFence, pocketmine\block\WoodenPressurePlate, pocketmine\block\WoodenSlab, and pocketmine\block\WoodenTrapdoor.
Definition at line 447 of file Block.php.
getFullId()
pocketmine\block\Block::getFullId () inherited
Definition at line 95 of file Block.php.
getHorizontalSides()
pocketmine\block\Block::getHorizontalSides () inherited
Returns the 4 blocks on the horizontal axes around the block (north, south, east, west)
Returns
Block[]|\Generator @phpstan-return \Generator<int, Block, void, void>
Definition at line 513 of file Block.php.
getId()
pocketmine\block\Block::getId () inherited
Definition at line 88 of file Block.php.
getIdInfo()
pocketmine\block\Block::getIdInfo () inherited
Definition at line 80 of file Block.php.
getLightFilter()
pocketmine\block\Block::getLightFilter () inherited
Returns the amount of light this block will filter out when light passes through this block. This value is used in light spread calculation.
Returns
int 0-15
Reimplemented in pocketmine\block\Ice, and pocketmine\block\Water.
Definition at line 301 of file Block.php.
getLightLevel()
pocketmine\block\Block::getLightLevel () inherited
Returns
int 0-15
Reimplemented in pocketmine\block\Beacon, pocketmine\block\BlueIce, pocketmine\block\BrownMushroom, pocketmine\block\DragonEgg, pocketmine\block\EnderChest, pocketmine\block\EndPortalFrame, pocketmine\block\EndRod, pocketmine\block\Fire, pocketmine\block\Furnace, pocketmine\block\GlowingObsidian, pocketmine\block\Glowstone, pocketmine\block\Lantern, pocketmine\block\Lava, pocketmine\block\LitPumpkin, pocketmine\block\Magma, pocketmine\block\NetherPortal, pocketmine\block\RedstoneLamp, pocketmine\block\RedstoneOre, pocketmine\block\RedstoneTorch, pocketmine\block\SeaLantern, pocketmine\block\SeaPickle, and pocketmine\block\Torch.
Definition at line 291 of file Block.php.
getMaxStackSize()
pocketmine\block\Block::getMaxStackSize () inherited
Returns the maximum number of this block that can fit into a single item stack.
Reimplemented in pocketmine\block\BaseBanner, pocketmine\block\BaseSign, and pocketmine\block\ShulkerBox.
Definition at line 454 of file Block.php.
getMeta()
pocketmine\block\Block::getMeta () inherited
Definition at line 106 of file Block.php.
getModelPositionOffset()
pocketmine\block\Block::getModelPositionOffset () inherited
Returns an additional fractional vector to shift the block model's position by based on the current position. Used to randomize position of things like bamboo canes and tall grass.
Reimplemented in pocketmine\block\Bamboo.
Definition at line 602 of file Block.php.
getName()
pocketmine\block\Block::getName () inherited
Definition at line 84 of file Block.php.
getPickedItem()
pocketmine\block\Block::getPickedItem (bool $addUserData = false) inherited
Returns the item that players will equip when middle-clicking on this block.
Reimplemented in pocketmine\block\BaseBanner, pocketmine\block\Beetroot, pocketmine\block\Carrot, pocketmine\block\CocoaBlock, pocketmine\block\Farmland, pocketmine\block\FlowerPot, pocketmine\block\ItemFrame, pocketmine\block\Potato, pocketmine\block\ShulkerBox, and pocketmine\block\Wheat.
Definition at line 429 of file Block.php.
References pocketmine\item\Item\setCustomBlockData().
getPosition()
pocketmine\block\Block::getPosition () final inherited
Definition at line 346 of file Block.php.
getSide()
pocketmine\block\Block::getSide (int $side, int $step = 1) inherited
Returns the Block on the side $side, works like Vector3::getSide()
Returns
Block
Definition at line 499 of file Block.php.
Referenced by pocketmine\block\Stem\onRandomTick(), pocketmine\block\WaterLily\place(), pocketmine\block\Fence\readStateFromWorld(), pocketmine\block\Thin\readStateFromWorld(), and pocketmine\block\Wall\readStateFromWorld().
getSilkTouchDrops()
pocketmine\block\Block::getSilkTouchDrops (Item $item) inherited
Returns an array of Items to be dropped when the block is broken using a compatible Silk Touch-enchanted tool.
Returns
Item[]
Reimplemented in pocketmine\block\InfestedStone.
Definition at line 397 of file Block.php.
getStateBitmask()
pocketmine\block\Block::getStateBitmask () inherited
Returns a bitmask used to extract state bits from block metadata.
Reimplemented in pocketmine\block\Anvil, pocketmine\block\Bamboo, pocketmine\block\BambooSapling, pocketmine\block\Barrel, pocketmine\block\Bed, pocketmine\block\Bedrock, pocketmine\block\Bell, pocketmine\block\BrewingStand, pocketmine\block\Button, pocketmine\block\Cactus, pocketmine\block\Cake, pocketmine\block\CarvedPumpkin, pocketmine\block\ChemistryTable, pocketmine\block\CocoaBlock, pocketmine\block\Coral, pocketmine\block\CoralBlock, pocketmine\block\Crops, pocketmine\block\DaylightSensor, pocketmine\block\DetectorRail, pocketmine\block\Dirt, pocketmine\block\Door, pocketmine\block\DoublePlant, pocketmine\block\EndPortalFrame, pocketmine\block\EndRod, pocketmine\block\Farmland, pocketmine\block\FenceGate, pocketmine\block\Fire, pocketmine\block\FloorBanner, pocketmine\block\FloorCoralFan, pocketmine\block\FloorSign, pocketmine\block\FlowerPot, pocketmine\block\FrostedIce, pocketmine\block\Hopper, pocketmine\block\ItemFrame, pocketmine\block\Lantern, pocketmine\block\Leaves, pocketmine\block\Lectern, pocketmine\block\Lever, pocketmine\block\Liquid, pocketmine\block\Loom, pocketmine\block\NetherPortal, pocketmine\block\NetherReactor, pocketmine\block\NetherWartPlant, pocketmine\block\Rail, pocketmine\block\RedMushroomBlock, pocketmine\block\RedstoneComparator, pocketmine\block\RedstoneRepeater, pocketmine\block\RedstoneWire, pocketmine\block\Sapling, pocketmine\block\SeaPickle, pocketmine\block\SimplePressurePlate, pocketmine\block\Skull, pocketmine\block\Slab, pocketmine\block\SnowLayer, pocketmine\block\Sponge, pocketmine\block\Stair, pocketmine\block\StraightOnlyRail, pocketmine\block\Sugarcane, pocketmine\block\SweetBerryBush, pocketmine\block\TNT, pocketmine\block\Torch, pocketmine\block\Trapdoor, pocketmine\block\Tripwire, pocketmine\block\TripwireHook, pocketmine\block\Vine, pocketmine\block\WallCoralFan, and pocketmine\block\WeightedPressurePlate.
Definition at line 119 of file Block.php.
Referenced by pocketmine\block\Block\__construct().
getTypeId()
pocketmine\block\Block::getTypeId () inherited
Returns a type ID that identifies this type of block. This does not include information like facing, colour, powered/unpowered, etc.
Definition at line 172 of file Block.php.
getXpDropAmount()
pocketmine\block\Block::getXpDropAmount () protected inherited
Returns how much XP this block will drop when broken with an appropriate tool.
Reimplemented in pocketmine\block\CoalOre, pocketmine\block\DiamondOre, pocketmine\block\EmeraldOre, pocketmine\block\LapisOre, pocketmine\block\MonsterSpawner, pocketmine\block\NetherQuartzOre, and pocketmine\block\RedstoneOre.
Definition at line 415 of file Block.php.
getXpDropForTool()
pocketmine\block\Block::getXpDropForTool (Item $item) inherited
Returns how much XP will be dropped by breaking this block with the given item.
Definition at line 404 of file Block.php.
hasEntityCollision()
pocketmine\block\Block::hasEntityCollision () inherited
Definition at line 331 of file Block.php.
isAffectedBySilkTouch()
pocketmine\block\Block::isAffectedBySilkTouch () inherited
Returns whether Silk Touch enchanted tools will cause this block to drop as itself.
Reimplemented in pocketmine\block\BaseCoral, pocketmine\block\Bookshelf, pocketmine\block\Clay, pocketmine\block\CoalOre, pocketmine\block\Cobweb, pocketmine\block\CoralBlock, pocketmine\block\DeadBush, pocketmine\block\DiamondOre, pocketmine\block\EmeraldOre, pocketmine\block\EnderChest, pocketmine\block\Glass, pocketmine\block\GlassPane, pocketmine\block\Glowstone, pocketmine\block\Grass, pocketmine\block\GrassPath, pocketmine\block\Gravel, pocketmine\block\Ice, pocketmine\block\InfestedStone, pocketmine\block\LapisOre, pocketmine\block\Leaves, pocketmine\block\Melon, pocketmine\block\MushroomStem, pocketmine\block\Mycelium, pocketmine\block\NetherQuartzOre, pocketmine\block\PackedIce, pocketmine\block\RedMushroomBlock, pocketmine\block\RedstoneOre, pocketmine\block\SeaLantern, and pocketmine\block\Snow.
Definition at line 422 of file Block.php.
isFlammable()
pocketmine\block\Block::isFlammable () inherited
Returns whether this block can catch fire.
Definition at line 483 of file Block.php.
isFullCube()
pocketmine\block\Block::isFullCube () inherited
Definition at line 613 of file Block.php.
isSameState()
pocketmine\block\Block::isSameState (Block $other) inherited
Returns whether the given block has the same type and properties as this block.
Definition at line 189 of file Block.php.
isSameType()
pocketmine\block\Block::isSameType (Block $other) inherited
Returns whether the given block has an equivalent type to this one. This compares the type IDs.
Note: This ignores additional IDs used to represent additional states. This means that, for example, a lit furnace and unlit furnace are considered the same type.
Definition at line 182 of file Block.php.
Referenced by pocketmine\block\Stem\onRandomTick(), and pocketmine\block\Liquid\onScheduledUpdate().
isSolid()
pocketmine\block\Flowable::isSolid () inherited
Reimplemented from pocketmine\block\Block.
Definition at line 34 of file Flowable.php.
isTransparent()
pocketmine\block\Transparent::isTransparent () inherited
Reimplemented from pocketmine\block\Block.
Definition at line 28 of file Transparent.php.
onAttack()
pocketmine\block\Block::onAttack (Item $item, int $face, ?Player $player = null) inherited
Called when this block is attacked (left-clicked). This is called when a player left-clicks the block to try and start to break it in survival mode.
Returns
bool if an action took place, prevents starting to break the block if true.
Reimplemented in pocketmine\block\DragonEgg, pocketmine\block\ItemFrame, and pocketmine\block\Lectern.
Definition at line 280 of file Block.php.
onBreak()
pocketmine\block\Block::onBreak (Item $item, ?Player $player = null) inherited
Do the actions needed so the block is broken with the Item
Reimplemented in pocketmine\block\Ice, pocketmine\block\Jukebox, and pocketmine\block\TNT.
Definition at line 230 of file Block.php.
onEntityInside()
pocketmine\block\Block::onEntityInside (Entity $entity) inherited
Called when an entity's bounding box clips inside this block's cell. Note that the entity may not be intersecting with the collision box or bounding box.
Returns
bool Whether the block is still the same after the intersection. If it changed (e.g. due to an explosive being ignited), this should return false.
Reimplemented in pocketmine\block\Cactus, pocketmine\block\Cobweb, pocketmine\block\Fire, pocketmine\block\Ladder, pocketmine\block\Lava, pocketmine\block\Magma, pocketmine\block\NetherPortal, pocketmine\block\SweetBerryBush, pocketmine\block\TNT, pocketmine\block\Vine, and pocketmine\block\Water.
Definition at line 570 of file Block.php.
onEntityLand()
pocketmine\block\Block::onEntityLand (Entity $entity) inherited
Called when an entity lands on this block (usually due to falling).
Returns
float|null The new vertical velocity of the entity, or null if unchanged.
Reimplemented in pocketmine\block\Bed, pocketmine\block\Farmland, pocketmine\block\HayBale, and pocketmine\block\Slime.
Definition at line 578 of file Block.php.
onIncinerate()
pocketmine\block\Block::onIncinerate () inherited
Called when this block is burned away by being on fire.
Reimplemented in pocketmine\block\TNT.
Definition at line 490 of file Block.php.
onInteract()
pocketmine\block\Block::onInteract (Item $item, int $face, Vector3 $clickVector, ?Player $player = null) inherited
Do actions when interacted by Item. Returns if it has done anything
Reimplemented in pocketmine\block\Anvil, pocketmine\block\Bamboo, pocketmine\block\BambooSapling, pocketmine\block\Barrel, pocketmine\block\Bed, pocketmine\block\Bell, pocketmine\block\BrewingStand, pocketmine\block\Button, pocketmine\block\Cake, pocketmine\block\ChemistryTable, pocketmine\block\Chest, pocketmine\block\CocoaBlock, pocketmine\block\CraftingTable, pocketmine\block\Crops, pocketmine\block\DaylightSensor, pocketmine\block\Dirt, pocketmine\block\Door, pocketmine\block\DragonEgg, pocketmine\block\EnchantingTable, pocketmine\block\EnderChest, pocketmine\block\FenceGate, pocketmine\block\FlowerPot, pocketmine\block\Furnace, pocketmine\block\Grass, pocketmine\block\Hopper, pocketmine\block\ItemFrame, pocketmine\block\Jukebox, pocketmine\block\Lectern, pocketmine\block\Lever, pocketmine\block\Loom, pocketmine\block\Pumpkin, pocketmine\block\RedstoneComparator, pocketmine\block\RedstoneOre, pocketmine\block\RedstoneRepeater, pocketmine\block\Sapling, pocketmine\block\SeaPickle, pocketmine\block\ShulkerBox, pocketmine\block\Sugarcane, pocketmine\block\SweetBerryBush, pocketmine\block\TNT, pocketmine\block\Trapdoor, and pocketmine\block\Wood.
Definition at line 270 of file Block.php.
onNearbyBlockChange()
pocketmine\block\Flower::onNearbyBlockChange ()
Called when this block or a block immediately adjacent to it changes state.
Reimplemented from pocketmine\block\Block.
Definition at line 43 of file Flower.php.
onPostPlace()
pocketmine\block\Block::onPostPlace () inherited
Definition at line 216 of file Block.php.
onRandomTick()
pocketmine\block\Block::onRandomTick () inherited
Called when this block is randomly updated due to chunk ticking. WARNING: This will not be called if ticksRandomly() does not return true!
Reimplemented in pocketmine\block\Bamboo, pocketmine\block\BambooSapling, pocketmine\block\Cactus, pocketmine\block\CocoaBlock, pocketmine\block\Crops, pocketmine\block\Farmland, pocketmine\block\Fire, pocketmine\block\FrostedIce, pocketmine\block\Grass, pocketmine\block\Ice, pocketmine\block\Leaves, pocketmine\block\Mycelium, pocketmine\block\NetherWartPlant, pocketmine\block\RedstoneOre, pocketmine\block\Sapling, pocketmine\block\SnowLayer, pocketmine\block\Stem, pocketmine\block\Sugarcane, pocketmine\block\SweetBerryBush, and pocketmine\block\Vine.
Definition at line 256 of file Block.php.
onScheduledUpdate()
pocketmine\block\Block::onScheduledUpdate () inherited
Called when this block is updated by the delayed blockupdate scheduler in the world.
Reimplemented in pocketmine\block\BrewingStand, pocketmine\block\Button, pocketmine\block\CoralBlock, pocketmine\block\DaylightSensor, pocketmine\block\Fire, pocketmine\block\FrostedIce, pocketmine\block\Furnace, pocketmine\block\Hopper, pocketmine\block\Lectern, pocketmine\block\Liquid, and pocketmine\block\MonsterSpawner.
Definition at line 263 of file Block.php.
place()
pocketmine\block\Flower::place (BlockTransaction $tx, Item $item, Block $blockReplace, Block $blockClicked, int $face, Vector3 $clickVector, ?Player $player = null)
Places the Block, using block space and block target, and side. Returns if the block has been placed.
Reimplemented from pocketmine\block\Block.
Definition at line 34 of file Flower.php.
position()
pocketmine\block\Block::position (World $world, int $x, int $y, int $z) final inherited
Definition at line 353 of file Block.php.
readStateFromData()
pocketmine\block\Block::readStateFromData (int $id, int $stateMeta) inherited
Exceptions
InvalidBlockStateException
Reimplemented in pocketmine\block\Anvil, pocketmine\block\Bamboo, pocketmine\block\BambooSapling, pocketmine\block\Barrel, pocketmine\block\Bed, pocketmine\block\Bedrock, pocketmine\block\Bell, pocketmine\block\BrewingStand, pocketmine\block\Button, pocketmine\block\Cactus, pocketmine\block\Cake, pocketmine\block\CarvedPumpkin, pocketmine\block\ChemistryTable, pocketmine\block\CocoaBlock, pocketmine\block\Coral, pocketmine\block\CoralBlock, pocketmine\block\Crops, pocketmine\block\DaylightSensor, pocketmine\block\DetectorRail, pocketmine\block\Dirt, pocketmine\block\Door, pocketmine\block\DoublePlant, pocketmine\block\EndPortalFrame, pocketmine\block\EndRod, pocketmine\block\Farmland, pocketmine\block\FenceGate, pocketmine\block\Fire, pocketmine\block\FloorBanner, pocketmine\block\FloorCoralFan, pocketmine\block\FloorSign, pocketmine\block\FrostedIce, pocketmine\block\Furnace, pocketmine\block\Hopper, pocketmine\block\ItemFrame, pocketmine\block\Lantern, pocketmine\block\Leaves, pocketmine\block\Lectern, pocketmine\block\Lever, pocketmine\block\Liquid, pocketmine\block\Loom, pocketmine\block\NetherPortal, pocketmine\block\NetherReactor, pocketmine\block\NetherWartPlant, pocketmine\block\Rail, pocketmine\block\RedMushroomBlock, pocketmine\block\RedstoneComparator, pocketmine\block\RedstoneLamp, pocketmine\block\RedstoneOre, pocketmine\block\RedstoneRepeater, pocketmine\block\RedstoneTorch, pocketmine\block\RedstoneWire, pocketmine\block\Sapling, pocketmine\block\SeaPickle, pocketmine\block\SimplePressurePlate, pocketmine\block\Skull, pocketmine\block\Slab, pocketmine\block\SnowLayer, pocketmine\block\Sponge, pocketmine\block\Stair, pocketmine\block\StraightOnlyRail, pocketmine\block\Sugarcane, pocketmine\block\SweetBerryBush, pocketmine\block\TNT, pocketmine\block\Torch, pocketmine\block\Trapdoor, pocketmine\block\Tripwire, pocketmine\block\TripwireHook, pocketmine\block\Vine, pocketmine\block\WallCoralFan, and pocketmine\block\WeightedPressurePlate.
Definition at line 130 of file Block.php.
readStateFromWorld()
pocketmine\block\Block::readStateFromWorld () inherited
Called when this block is created, set, or has a neighbouring block update, to re-detect dynamic properties which are not saved on the world.
Clears any cached precomputed objects, such as bounding boxes. Remove any outdated precomputed things such as AABBs and force recalculation.
Reimplemented in pocketmine\block\BaseBanner, pocketmine\block\BaseSign, pocketmine\block\Bed, pocketmine\block\Coral, pocketmine\block\Door, pocketmine\block\Fence, pocketmine\block\FlowerPot, pocketmine\block\ItemFrame, pocketmine\block\Jukebox, pocketmine\block\Lectern, pocketmine\block\Liquid, pocketmine\block\Note, pocketmine\block\RedstoneComparator, pocketmine\block\RedstoneWire, pocketmine\block\ShulkerBox, pocketmine\block\Skull, pocketmine\block\Stair, pocketmine\block\Thin, and pocketmine\block\Wall.
Definition at line 141 of file Block.php.
recalculateCollisionBoxes()
pocketmine\block\Flowable::recalculateCollisionBoxes () protected inherited
Returns
AxisAlignedBB[]
Reimplemented from pocketmine\block\Block.
Reimplemented in pocketmine\block\Carpet, pocketmine\block\EndRod, pocketmine\block\FlowerPot, pocketmine\block\RedstoneComparator, pocketmine\block\RedstoneRepeater, pocketmine\block\Skull, pocketmine\block\SnowLayer, pocketmine\block\Vine, and pocketmine\block\WaterLily.
Definition at line 41 of file Flowable.php.
ticksRandomly()
pocketmine\block\Block::ticksRandomly () inherited
Returns whether random block updates will be done on this block.
Reimplemented in pocketmine\block\Bamboo, pocketmine\block\BambooSapling, pocketmine\block\Cactus, pocketmine\block\CocoaBlock, pocketmine\block\Crops, pocketmine\block\Farmland, pocketmine\block\Fire, pocketmine\block\Grass, pocketmine\block\Ice, pocketmine\block\Leaves, pocketmine\block\Mycelium, pocketmine\block\NetherWartPlant, pocketmine\block\RedMushroom, pocketmine\block\RedstoneOre, pocketmine\block\Sapling, pocketmine\block\SnowLayer, pocketmine\block\Sugarcane, pocketmine\block\SweetBerryBush, and pocketmine\block\Vine.
Definition at line 248 of file Block.php.
writeStateToItemMeta()
pocketmine\block\Block::writeStateToItemMeta () protected inherited
Definition at line 112 of file Block.php.
writeStateToMeta()
pocketmine\block\Block::writeStateToMeta () protected inherited
Definition at line 123 of file Block.php.
writeStateToWorld()
pocketmine\block\Block::writeStateToWorld () inherited
Definition at line 145 of file Block.php.
Member Data Documentation
$breakInfo
BlockBreakInfo pocketmine\block\Block::$breakInfo protected inherited
Definition at line 57 of file Block.php.
$collisionBoxes
array pocketmine\block\Block::$collisionBoxes = null protected inherited
Definition at line 61 of file Block.php.
$fallbackName
string pocketmine\block\Block::$fallbackName protected inherited
Definition at line 56 of file Block.php.
$idInfo
BlockIdentifier pocketmine\block\Block::$idInfo protected inherited
Definition at line 55 of file Block.php.
$position
Position pocketmine\block\Block::$position protected inherited
Definition at line 58 of file Block.php.
INTERNAL_METADATA_BITS
const pocketmine\block\Block::INTERNAL_METADATA_BITS = 4 inherited
Definition at line 52 of file Block.php.
INTERNAL_METADATA_MASK
const pocketmine\block\Block::INTERNAL_METADATA_MASK = ~(~0 << self::INTERNAL_METADATA_BITS) inherited
Definition at line 53 of file Block.php.
The documentation for this class was generated from the following file:
Flower.php