PocketMine-MP: pocketmine\item\RawRabbit Class Reference
pocketmine\item\RawRabbit Class Reference
Public Member Functions
__clone ()
__toString ()
canBePlaced ()
canStackWith (Item $other)
canStartUsingItem (Player $player)
clearCustomBlockData ()
clearCustomName ()
clearNamedTag ()
equals (Item $item, bool $checkDamage=true, bool $checkCompound=true)
equalsExact (Item $other)
getAdditionalEffects ()
getAttackPoints ()
getBlock (?int $clickedFace=null)
getBlockToolHarvestLevel ()
getBlockToolType ()
getCanDestroy ()
getCanPlaceOn ()
getCooldownTicks ()
getCount ()
getCustomBlockData ()
getCustomName ()
getDefensePoints ()
getFoodRestore ()
getFuelResidue ()
getFuelTime ()
getLore ()
getMaxStackSize ()
getMiningEfficiency (bool $isCorrectTool)
getName ()
getNamedTag ()
getResidue ()
getSaturationRestore ()
getStateId ()
getTypeId ()
getVanillaName ()
hasCustomBlockData ()
hasCustomName ()
hasNamedTag ()
isFireProof ()
isNull ()
jsonSerialize ()
keepOnDeath ()
nbtSerialize (int $slot=-1)
onAttackEntity (Entity $victim, array &$returnedItems)
onClickAir (Player $player, Vector3 $directionVector, array &$returnedItems)
onConsume (Living $consumer)
onDestroyBlock (Block $block, array &$returnedItems)
onInteractBlock (Player $player, Block $blockReplace, Block $blockClicked, int $face, Vector3 $clickVector, array &$returnedItems)
onInteractEntity (Player $player, Entity $entity, Vector3 $clickVector)
onReleaseUsing (Player $player, array &$returnedItems)
onTickWorn (Living $entity)
pop (int $count=1)
requiresHunger ()
setCanDestroy (array $canDestroy)
setCanPlaceOn (array $canPlaceOn)
setCount (int $count)
setCustomBlockData (CompoundTag $compound)
setCustomName (string $name)
setKeepOnDeath (bool $keepOnDeath)
setLore (array $lines)
setNamedTag (CompoundTag $tag)
Static Public Member Functions
static legacyJsonDeserialize (array $data)
static nbtDeserialize (CompoundTag $tag)
Public Attributes
const TAG_BLOCK_ENTITY_TAG = "BlockEntityTag"
const TAG_DISPLAY = "display"
const TAG_DISPLAY_LORE = "Lore"
const TAG_DISPLAY_NAME = "Name"
const TAG_ENCH = "ench"
const TAG_KEEP_ON_DEATH = "minecraft:keep_on_death"
Protected Member Functions
describeState (RuntimeDataDescriber $w)
deserializeCompoundTag (CompoundTag $tag)
serializeCompoundTag (CompoundTag $tag)
Protected Attributes
CompoundTag $blockEntityTag = null
array $canDestroy = []
array $canPlaceOn = []
int $count = 1
string $customName = ""
bool $keepOnDeath = false
array $lore = []
Detailed Description
Definition at line 26 of file RawRabbit.php.
Member Function Documentation
__clone()
pocketmine\item\Item::__clone () inherited
Definition at line 727 of file Item.php.
__toString()
pocketmine\item\Item::__toString () final inherited
Definition at line 656 of file Item.php.
canBePlaced()
pocketmine\item\Item::canBePlaced () final inherited
Definition at line 458 of file Item.php.
canStackWith()
pocketmine\item\Item::canStackWith (Item $other) final inherited
Returns whether this item could stack with the given item (ignoring stack size and count).
Definition at line 645 of file Item.php.
canStartUsingItem()
pocketmine\item\Food::canStartUsingItem (Player $player) inherited
Implements pocketmine\item\Releasable.
Definition at line 46 of file Food.php.
clearCustomBlockData()
pocketmine\item\Item::clearCustomBlockData () inherited
Returns
$this
Definition at line 125 of file Item.php.
clearCustomName()
pocketmine\item\Item::clearCustomName () inherited
Returns
$this
Definition at line 163 of file Item.php.
clearNamedTag()
pocketmine\item\Item::clearNamedTag () inherited
Removes the Item's NBT.
Returns
$this
Exceptions
NbtException
Definition at line 276 of file Item.php.
describeState()
pocketmine\item\Item::describeState (RuntimeDataDescriber $w) protected inherited
Describes state properties of the item, such as colour, skull type, etc. This allows associating basic extra data with the item at runtime in a more efficient format than NBT.
Reimplemented in pocketmine\item\Banner, pocketmine\item\CoralFan, pocketmine\item\Dye, pocketmine\item\ItemBlock, pocketmine\item\Medicine, pocketmine\item\Potion, pocketmine\item\SplashPotion, and pocketmine\item\SuspiciousStew.
Definition at line 487 of file Item.php.
deserializeCompoundTag()
pocketmine\item\Item::deserializeCompoundTag (CompoundTag $tag) protected inherited
Exceptions
NbtException
Reimplemented in pocketmine\item\Armor, pocketmine\item\Banner, pocketmine\item\Durable, pocketmine\item\WritableBookBase, and pocketmine\item\WrittenBook.
Definition at line 285 of file Item.php.
equals()
pocketmine\item\Item::equals (Item $item, bool $checkDamage = true, bool $checkCompound = true) final inherited
Compares an Item to this Item and check if they match.
Parameters
bool $checkDamage
Deprecated:
Parameters
bool $checkCompound Whether to verify that the items' NBT match.
Definition at line 637 of file Item.php.
equalsExact()
pocketmine\item\Item::equalsExact (Item $other) final inherited
Returns whether the specified item stack has the same ID, damage, NBT and count as this item stack.
Definition at line 652 of file Item.php.
getAdditionalEffects()
pocketmine\item\Food::getAdditionalEffects () inherited
Returns
EffectInstance[]
Implements pocketmine\entity\Consumable.
Reimplemented in pocketmine\item\GoldenApple, pocketmine\item\GoldenAppleEnchanted, pocketmine\item\PoisonousPotato, pocketmine\item\Pufferfish, pocketmine\item\RawChicken, pocketmine\item\RottenFlesh, pocketmine\item\SpiderEye, and pocketmine\item\SuspiciousStew.
Definition at line 38 of file Food.php.
getAttackPoints()
pocketmine\item\Item::getAttackPoints () inherited
Returns how many points of damage this item will deal to an entity when used as a weapon.
Reimplemented in pocketmine\item\Axe, pocketmine\item\Pickaxe, pocketmine\item\Shovel, and pocketmine\item\Sword.
Definition at line 525 of file Item.php.
getBlock()
pocketmine\item\Item::getBlock (?int $clickedFace = null) inherited
Returns the block corresponding to this Item.
Reimplemented in pocketmine\item\Bamboo, pocketmine\item\BeetrootSeeds, pocketmine\item\Carrot, pocketmine\item\CocoaBeans, pocketmine\item\CoralFan, pocketmine\item\GlowBerries, pocketmine\item\ItemBlock, pocketmine\item\ItemBlockWallOrFloor, pocketmine\item\MelonSeeds, pocketmine\item\Potato, pocketmine\item\PumpkinSeeds, pocketmine\item\Redstone, pocketmine\item\StringItem, pocketmine\item\SweetBerries, and pocketmine\item\WheatSeeds.
Definition at line 465 of file Item.php.
Referenced by pocketmine\block\Cake\onInteract().
getBlockToolHarvestLevel()
pocketmine\item\Item::getBlockToolHarvestLevel () inherited
Returns the harvesting power that this tool has. This affects what blocks it can mine when the tool type matches the mined block. This should return 1 for non-tiered tools, and the tool tier for tiered tools.
See also
BlockBreakInfo::getToolHarvestLevel()
Reimplemented in pocketmine\item\Axe, pocketmine\item\Pickaxe, pocketmine\item\Shears, pocketmine\item\Shovel, and pocketmine\item\Sword.
Definition at line 551 of file Item.php.
getBlockToolType()
pocketmine\item\Item::getBlockToolType () inherited
Returns what type of block-breaking tool this is. Blocks requiring the same tool type as the item will break faster (except for blocks requiring no tool, which break at the same speed regardless of the tool used)
Reimplemented in pocketmine\item\Axe, pocketmine\item\Hoe, pocketmine\item\Pickaxe, pocketmine\item\Shears, pocketmine\item\Shovel, and pocketmine\item\Sword.
Definition at line 540 of file Item.php.
getCanDestroy()
pocketmine\item\Item::getCanDestroy () inherited
Returns
string[] @phpstan-return array<string, string>
Definition at line 213 of file Item.php.
getCanPlaceOn()
pocketmine\item\Item::getCanPlaceOn () inherited
Returns
string[] @phpstan-return array<string, string>
Definition at line 195 of file Item.php.
getCooldownTicks()
pocketmine\item\Item::getCooldownTicks () inherited
Returns the number of ticks a player must wait before activating this item again.
Reimplemented in pocketmine\item\ChorusFruit, and pocketmine\item\EnderPearl.
Definition at line 627 of file Item.php.
getCount()
pocketmine\item\Item::getCount () inherited
Definition at line 408 of file Item.php.
getCustomBlockData()
pocketmine\item\Item::getCustomBlockData () inherited
Definition at line 139 of file Item.php.
getCustomName()
pocketmine\item\Item::getCustomName () inherited
Definition at line 147 of file Item.php.
getDefensePoints()
pocketmine\item\Item::getDefensePoints () inherited
Returns how many armor points can be gained by wearing this item.
Reimplemented in pocketmine\item\Armor.
Definition at line 532 of file Item.php.
getFoodRestore()
pocketmine\item\RawRabbit::getFoodRestore ()
Implements pocketmine\entity\FoodSource.
Definition at line 28 of file RawRabbit.php.
getFuelResidue()
pocketmine\item\Item::getFuelResidue () inherited
Returns an item after burning fuel
Reimplemented in pocketmine\item\LiquidBucket.
Definition at line 508 of file Item.php.
getFuelTime()
pocketmine\item\Item::getFuelTime () inherited
Returns the time in ticks which the item will fuel a furnace for.
Reimplemented in pocketmine\item\Bamboo, pocketmine\item\Banner, pocketmine\item\BlazeRod, pocketmine\item\Boat, pocketmine\item\Bow, pocketmine\item\Coal, pocketmine\item\CoralFan, pocketmine\item\ItemBlock, pocketmine\item\ItemBlockWallOrFloor, pocketmine\item\LiquidBucket, pocketmine\item\Stick, and pocketmine\item\TieredTool.
Definition at line 501 of file Item.php.
getLore()
pocketmine\item\Item::getLore () inherited
Returns
string[]
Definition at line 171 of file Item.php.
getMaxStackSize()
pocketmine\item\Item::getMaxStackSize () inherited
Returns the highest amount of this item which will fit into one inventory slot.
Reimplemented in pocketmine\item\Armor, pocketmine\item\BeetrootSoup, pocketmine\item\Boat, pocketmine\item\Bucket, pocketmine\item\CoralFan, pocketmine\item\Egg, pocketmine\item\EnderPearl, pocketmine\item\FishingRod, pocketmine\item\HoneyBottle, pocketmine\item\ItemBlock, pocketmine\item\ItemBlockWallOrFloor, pocketmine\item\LiquidBucket, pocketmine\item\Medicine, pocketmine\item\MilkBucket, pocketmine\item\Minecart, pocketmine\item\MushroomStew, pocketmine\item\Potion, pocketmine\item\RabbitStew, pocketmine\item\Record, pocketmine\item\Snowball, pocketmine\item\SplashPotion, pocketmine\item\Spyglass, pocketmine\item\SuspiciousStew, pocketmine\item\Tool, pocketmine\item\Totem, pocketmine\item\WritableBookBase, and pocketmine\item\WrittenBook.
Definition at line 494 of file Item.php.
getMiningEfficiency()
pocketmine\item\Item::getMiningEfficiency (bool $isCorrectTool) inherited
Definition at line 555 of file Item.php.
getName()
pocketmine\item\Item::getName () final inherited
Returns the name of the item, or the custom name if it is set.
Definition at line 447 of file Item.php.
getNamedTag()
pocketmine\item\Item::getNamedTag () inherited
Returns a tree of Tag objects representing the Item's NBT. If the item does not have any NBT, an empty CompoundTag object is returned to allow the caller to manipulate and apply back to the item.
Definition at line 249 of file Item.php.
getResidue()
pocketmine\item\Food::getResidue () inherited
Returns the leftover that this Consumable produces when it is consumed. For Items, this is usually air, but could be an Item to add to a Player's inventory afterwards (such as a bowl).
Implements pocketmine\item\ConsumableItem.
Reimplemented in pocketmine\item\BeetrootSoup, pocketmine\item\HoneyBottle, pocketmine\item\MushroomStew, pocketmine\item\RabbitStew, and pocketmine\item\SuspiciousStew.
Definition at line 34 of file Food.php.
getSaturationRestore()
pocketmine\item\RawRabbit::getSaturationRestore ()
Implements pocketmine\entity\FoodSource.
Definition at line 32 of file RawRabbit.php.
getStateId()
pocketmine\item\Item::getStateId () final inherited
Definition at line 473 of file Item.php.
getTypeId()
pocketmine\item\Item::getTypeId () final inherited
Definition at line 469 of file Item.php.
getVanillaName()
pocketmine\item\Item::getVanillaName () inherited
Returns the vanilla name of the item, disregarding custom names.
Definition at line 454 of file Item.php.
hasCustomBlockData()
pocketmine\item\Item::hasCustomBlockData () inherited
Definition at line 118 of file Item.php.
hasCustomName()
pocketmine\item\Item::hasCustomName () inherited
Definition at line 143 of file Item.php.
hasNamedTag()
pocketmine\item\Item::hasNamedTag () inherited
Returns whether this Item has a non-empty NBT.
Definition at line 241 of file Item.php.
isFireProof()
pocketmine\item\Item::isFireProof () inherited
Returns whether this item can survive being dropped into lava, or fire.
Reimplemented in pocketmine\item\Armor, pocketmine\item\ItemBlock, and pocketmine\item\TieredTool.
Definition at line 518 of file Item.php.
isNull()
pocketmine\item\Item::isNull () inherited
Definition at line 440 of file Item.php.
jsonSerialize()
pocketmine\item\Item::jsonSerialize () inherited
@phpstan-return never
Definition at line 663 of file Item.php.
keepOnDeath()
pocketmine\item\Item::keepOnDeath () inherited
Returns whether players will retain this item on death. If a non-player dies it will be excluded from the drops.
Definition at line 230 of file Item.php.
legacyJsonDeserialize()
static pocketmine\item\Item::legacyJsonDeserialize (array $data) static final inherited
Deserializes item JSON data produced by json_encode()ing Item instances in older versions of PocketMine-MP. This method exists solely to allow upgrading old JSON data stored by plugins.
Parameters
mixed[] $data
Exceptions
SavedDataLoadingException
Definition at line 675 of file Item.php.
nbtDeserialize()
static pocketmine\item\Item::nbtDeserialize (CompoundTag $tag) static inherited
Deserializes an Item from an NBT CompoundTag
Exceptions
SavedDataLoadingException
Definition at line 714 of file Item.php.
nbtSerialize()
pocketmine\item\Item::nbtSerialize (int $slot = -1) inherited
Serializes the item to an NBT CompoundTag
Parameters
int $slot optional, the inventory slot of the item
Definition at line 706 of file Item.php.
onAttackEntity()
pocketmine\item\Item::onAttackEntity (Entity $victim, array & $returnedItems) inherited
Called when this item is used to attack an entity. Usually used to update durability.
Parameters
Item[] &$returnedItems Items to be added to the target's inventory (or dropped, if the inventory is full)
Reimplemented in pocketmine\item\Axe, pocketmine\item\Hoe, pocketmine\item\Pickaxe, pocketmine\item\Shovel, and pocketmine\item\Sword.
Definition at line 602 of file Item.php.
onClickAir()
pocketmine\item\Item::onClickAir (Player $player, Vector3 $directionVector, array & $returnedItems) inherited
Called when a player uses the item on air, for example throwing a projectile. Returns whether the item was changed, for example count decrease or durability change.
Parameters
Item[] &$returnedItems Items to be added to the target's inventory (or dropped, if the inventory is full)
Reimplemented in pocketmine\item\Armor, and pocketmine\item\ProjectileItem.
Definition at line 574 of file Item.php.
onConsume()
pocketmine\item\Food::onConsume (Living $consumer) inherited
Called when this Consumable is consumed by mob, after standard resulting effects have been applied.
Implements pocketmine\entity\Consumable.
Reimplemented in pocketmine\item\ChorusFruit, and pocketmine\item\HoneyBottle.
Definition at line 42 of file Food.php.
onDestroyBlock()
pocketmine\item\Item::onDestroyBlock (Block $block, array & $returnedItems) inherited
Called when this item is used to destroy a block. Usually used to update durability.
Parameters
Item[] &$returnedItems Items to be added to the target's inventory (or dropped, if the inventory is full)
Reimplemented in pocketmine\item\Axe, pocketmine\item\Hoe, pocketmine\item\Pickaxe, pocketmine\item\Shears, pocketmine\item\Shovel, and pocketmine\item\Sword.
Definition at line 593 of file Item.php.
onInteractBlock()
pocketmine\item\Item::onInteractBlock (Player $player, Block $blockReplace, Block $blockClicked, int $face, Vector3 $clickVector, array & $returnedItems) inherited
Called when a player uses this item on a block.
Parameters
Item[] &$returnedItems Items to be added to the target's inventory (or dropped, if the inventory is full)
Reimplemented in pocketmine\item\Bucket, pocketmine\item\FireCharge, pocketmine\item\FlintSteel, pocketmine\item\GlassBottle, pocketmine\item\LiquidBucket, pocketmine\item\PaintingItem, and pocketmine\item\SpawnEgg.
Definition at line 564 of file Item.php.
onInteractEntity()
pocketmine\item\Item::onInteractEntity (Player $player, Entity $entity, Vector3 $clickVector) inherited
Called when a player uses the item to interact with entity, for example by using a name tag.
Parameters
Vector3 $clickVector The exact position of the click (absolute coordinates)
Returns
bool whether some action took place
Definition at line 620 of file Item.php.
onReleaseUsing()
pocketmine\item\Item::onReleaseUsing (Player $player, array & $returnedItems) inherited
Called when a player is using this item and releases it. Used to handle bow shoot actions. Returns whether the item was changed, for example count decrease or durability change.
Parameters
Item[] &$returnedItems Items to be added to the target's inventory (or dropped, if the inventory is full)
Reimplemented in pocketmine\item\Bow.
Definition at line 584 of file Item.php.
onTickWorn()
pocketmine\item\Item::onTickWorn (Living $entity) inherited
Called when this item is being worn by an entity. Returns whether it did something.
Reimplemented in pocketmine\item\TurtleHelmet.
Definition at line 610 of file Item.php.
pop()
pocketmine\item\Item::pop (int $count = 1) inherited
Pops an item from the stack and returns it, decreasing the stack count of this item stack by one.
Returns
static A clone of this itemstack containing the amount of items that were removed from this stack.
Exceptions
InvalidArgumentException if trying to pop more items than are on the stack
Definition at line 427 of file Item.php.
Referenced by pocketmine\block\Bamboo\onInteract(), pocketmine\block\BambooSapling\onInteract(), pocketmine\block\Cake\onInteract(), pocketmine\block\CocoaBlock\onInteract(), pocketmine\block\Crops\onInteract(), pocketmine\block\Jukebox\onInteract(), pocketmine\block\Lectern\onInteract(), pocketmine\block\NetherVines\onInteract(), pocketmine\block\Sapling\onInteract(), pocketmine\block\Sugarcane\onInteract(), pocketmine\block\SweetBerryBush\onInteract(), pocketmine\block\TNT\onInteract(), pocketmine\block\WaterCauldron\onInteract(), pocketmine\item\FireCharge\onInteractBlock(), and pocketmine\item\GlassBottle\onInteractBlock().
requiresHunger()
pocketmine\item\Food::requiresHunger () inherited
Returns whether a Human eating this FoodSource must have a non-full hunger bar.
Implements pocketmine\entity\FoodSource.
Reimplemented in pocketmine\item\ChorusFruit, pocketmine\item\GoldenApple, pocketmine\item\HoneyBottle, and pocketmine\item\SuspiciousStew.
Definition at line 30 of file Food.php.
serializeCompoundTag()
pocketmine\item\Item::serializeCompoundTag (CompoundTag $tag) protected inherited
Definition at line 340 of file Item.php.
setCanDestroy()
pocketmine\item\Item::setCanDestroy (array $canDestroy) inherited
Parameters
string[] $canDestroy
Definition at line 220 of file Item.php.
setCanPlaceOn()
pocketmine\item\Item::setCanPlaceOn (array $canPlaceOn) inherited
Parameters
string[] $canPlaceOn
Definition at line 202 of file Item.php.
setCount()
pocketmine\item\Item::setCount (int $count) inherited
Returns
$this
Definition at line 415 of file Item.php.
setCustomBlockData()
pocketmine\item\Item::setCustomBlockData (CompoundTag $compound) inherited
Returns
$this
Definition at line 133 of file Item.php.
Referenced by pocketmine\block\Block\getPickedItem().
setCustomName()
pocketmine\item\Item::setCustomName (string $name) inherited
Returns
$this
Definition at line 154 of file Item.php.
setKeepOnDeath()
pocketmine\item\Item::setKeepOnDeath (bool $keepOnDeath) inherited
Definition at line 234 of file Item.php.
setLore()
pocketmine\item\Item::setLore (array $lines) inherited
Parameters
string[] $lines
Returns
$this
Definition at line 180 of file Item.php.
Referenced by pocketmine\block\Block\getPickedItem().
setNamedTag()
pocketmine\item\Item::setNamedTag (CompoundTag $tag) inherited
Sets the Item's NBT from the supplied CompoundTag object.
Returns
$this
Exceptions
NbtException
Definition at line 260 of file Item.php.
Member Data Documentation
$blockEntityTag
CompoundTag pocketmine\item\Item::$blockEntityTag = null protected inherited
TODO: this needs to die in a fire
Definition at line 88 of file Item.php.
$canDestroy
array pocketmine\item\Item::$canDestroy = [] protected inherited
Definition at line 99 of file Item.php.
$canPlaceOn
array pocketmine\item\Item::$canPlaceOn = [] protected inherited
Definition at line 94 of file Item.php.
$count
int pocketmine\item\Item::$count = 1 protected inherited
Definition at line 80 of file Item.php.
$customName
string pocketmine\item\Item::$customName = "" protected inherited
Definition at line 84 of file Item.php.
$keepOnDeath
bool pocketmine\item\Item::$keepOnDeath = false protected inherited
Definition at line 101 of file Item.php.
$lore
array pocketmine\item\Item::$lore = [] protected inherited
Definition at line 86 of file Item.php.
TAG_BLOCK_ENTITY_TAG
const pocketmine\item\Item::TAG_BLOCK_ENTITY_TAG = "BlockEntityTag" inherited
Definition at line 68 of file Item.php.
TAG_DISPLAY
const pocketmine\item\Item::TAG_DISPLAY = "display" inherited
Definition at line 67 of file Item.php.
TAG_DISPLAY_LORE
const pocketmine\item\Item::TAG_DISPLAY_LORE = "Lore" inherited
Definition at line 71 of file Item.php.
TAG_DISPLAY_NAME
const pocketmine\item\Item::TAG_DISPLAY_NAME = "Name" inherited
Definition at line 70 of file Item.php.
TAG_ENCH
const pocketmine\item\Item::TAG_ENCH = "ench" inherited
Definition at line 63 of file Item.php.
TAG_KEEP_ON_DEATH
const pocketmine\item\Item::TAG_KEEP_ON_DEATH = "minecraft:keep_on_death" inherited
Definition at line 73 of file Item.php.
The documentation for this class was generated from the following file:
RawRabbit.php