PocketMine-MP: pocketmine\data\bedrock\block\convert\BlockStateToObjectDeserializer Class Reference
pocketmine\data\bedrock\block\convert\BlockStateToObjectDeserializer Class Reference
Public Member Functions
deserialize (BlockStateData $stateData)
deserializeBlock (BlockStateData $blockStateData)
map (string $id, \Closure $c)
mapLog (string $unstrippedId, string $strippedId, \Closure $getBlock)
mapSimple (string $id, \Closure $getBlock)
mapSlab (string $singleId, string $doubleId, \Closure $getBlock)
mapStairs (string $id, \Closure $getBlock)
Detailed Description
Definition at line 60 of file BlockStateToObjectDeserializer.php.
Constructor & Destructor Documentation
__construct()
pocketmine\data\bedrock\block\convert\BlockStateToObjectDeserializer::__construct ()
Definition at line 74 of file BlockStateToObjectDeserializer.php.
Member Function Documentation
deserialize()
pocketmine\data\bedrock\block\convert\BlockStateToObjectDeserializer::deserialize (BlockStateData $stateData)
Deserializes blockstate NBT into an implementation-defined blockstate ID, for runtime paletted storage.
@phpstan-return BlockStateId
Exceptions
BlockStateDeserializeException
Implements pocketmine\data\bedrock\block\BlockStateDeserializer.
Definition at line 86 of file BlockStateToObjectDeserializer.php.
References pocketmine\data\bedrock\block\convert\BlockStateToObjectDeserializer\deserializeBlock().
deserializeBlock()
pocketmine\data\bedrock\block\convert\BlockStateToObjectDeserializer::deserializeBlock (BlockStateData $blockStateData)
Exceptions
BlockStateDeserializeException
Definition at line 1530 of file BlockStateToObjectDeserializer.php.
Referenced by pocketmine\data\bedrock\block\convert\BlockStateToObjectDeserializer\deserialize().
map()
pocketmine\data\bedrock\block\convert\BlockStateToObjectDeserializer::map (string $id, \Closure $c)
@phpstan-param \Closure(Reader) : Block $c
Definition at line 97 of file BlockStateToObjectDeserializer.php.
mapLog()
pocketmine\data\bedrock\block\convert\BlockStateToObjectDeserializer::mapLog (string $unstrippedId, string $strippedId, \Closure $getBlock)
@phpstan-param \Closure() : Wood $getBlock
Definition at line 128 of file BlockStateToObjectDeserializer.php.
mapSimple()
pocketmine\data\bedrock\block\convert\BlockStateToObjectDeserializer::mapSimple (string $id, \Closure $getBlock)
@phpstan-param \Closure() : Block $getBlock
Definition at line 105 of file BlockStateToObjectDeserializer.php.
mapSlab()
pocketmine\data\bedrock\block\convert\BlockStateToObjectDeserializer::mapSlab (string $singleId, string $doubleId, \Closure $getBlock)
@phpstan-param \Closure(Reader) : Slab $getBlock
Definition at line 112 of file BlockStateToObjectDeserializer.php.
References pocketmine\block\Slab\setSlabType().
mapStairs()
pocketmine\data\bedrock\block\convert\BlockStateToObjectDeserializer::mapStairs (string $id, \Closure $getBlock)
@phpstan-param \Closure() : Stair $getBlock
Definition at line 123 of file BlockStateToObjectDeserializer.php.
The documentation for this class was generated from the following file:
BlockStateToObjectDeserializer.php