PocketMine-MP: pocketmine\block\NetherWartPlant Class Reference
pocketmine\block\NetherWartPlant Class Reference
Public Member Functions
__clone ()
__toString ()
addVelocityToEntity (Entity $entity)
asItem ()
blocksDirectSkyLight ()
burnsForever ()
calculateIntercept (Vector3 $pos1, Vector3 $pos2)
canBeFlowedInto ()
canBePlaced ()
canBePlacedAt (Block $blockReplace, Vector3 $clickVector, int $face, bool $isClickedBlock)
canBeReplaced ()
canClimb ()
collidesWithBB (AxisAlignedBB $bb)
getAffectedBlocks ()
getAge ()
getAllSides ()
getBreakInfo ()
getCollisionBoxes ()
getDrops (Item $item)
getDropsForCompatibleTool (Item $item)
getDropsForIncompatibleTool (Item $item)
getFlameEncouragement ()
getFlammability ()
getFrictionFactor ()
getFuelTime ()
getFullId ()
getHorizontalSides ()
getId ()
getIdInfo ()
getLightFilter ()
getLightLevel ()
getMaxStackSize ()
getMeta ()
getModelPositionOffset ()
getName ()
getPickedItem (bool $addUserData=false)
getPosition ()
getSide (int $side, int $step=1)
getSilkTouchDrops (Item $item)
getStateBitmask ()
getSupportType (int $facing)
getTypeId ()
getXpDropForTool (Item $item)
hasEntityCollision ()
isAffectedBySilkTouch ()
isFlammable ()
isFullCube ()
isSameState (Block $other)
isSameType (Block $other)
isSolid ()
isTransparent ()
onAttack (Item $item, int $face, ?Player $player=null)
onBreak (Item $item, ?Player $player=null)
onEntityInside (Entity $entity)
onEntityLand (Entity $entity)
onIncinerate ()
onInteract (Item $item, int $face, Vector3 $clickVector, ?Player $player=null)
onNearbyBlockChange ()
onPostPlace ()
onRandomTick ()
onScheduledUpdate ()
place (BlockTransaction $tx, Item $item, Block $blockReplace, Block $blockClicked, int $face, Vector3 $clickVector, ?Player $player=null)
position (World $world, int $x, int $y, int $z)
readStateFromData (int $id, int $stateMeta)
readStateFromWorld ()
setAge (int $age)
ticksRandomly ()
writeStateToWorld ()
Public Attributes
const INTERNAL_METADATA_BITS = 4
const INTERNAL_METADATA_MASK = ~(~0 << self::INTERNAL_METADATA_BITS)
const MAX_AGE = 3
Protected Member Functions
getXpDropAmount ()
recalculateCollisionBoxes ()
writeStateToItemMeta ()
writeStateToMeta ()
Protected Attributes
int $age = 0
BlockBreakInfo $breakInfo
array $collisionBoxes = null
string $fallbackName
BlockIdentifier $idInfo
Position $position
Detailed Description
Definition at line 35 of file NetherWartPlant.php.
Member Function Documentation
__clone()
pocketmine\block\Block::__clone () inherited
Definition at line 77 of file Block.php.
__toString()
pocketmine\block\Block::__toString () inherited
Returns
string
Definition at line 606 of file Block.php.
addVelocityToEntity()
pocketmine\block\Block::addVelocityToEntity (Entity $entity) inherited
Returns a direction vector describing which way an entity intersecting this block should be pushed. This is used by liquids to push entities in liquid currents.
The returned vector is summed with vectors from every other block the entity is intersecting, and normalized to produce a final direction vector.
WARNING: This will not be called if Block::hasEntityCollision() does not return true!
Reimplemented in pocketmine\block\Liquid.
Definition at line 654 of file Block.php.
asItem()
pocketmine\block\Block::asItem () inherited
Returns the block as an item. State information such as facing, powered/unpowered, open/closed, etc., is discarded. Type information such as colour, wood type, etc. is preserved.
Reimplemented in pocketmine\block\BambooSapling, pocketmine\block\FloorCoralFan, pocketmine\block\SweetBerryBush, and pocketmine\block\WallCoralFan.
Definition at line 122 of file Block.php.
blocksDirectSkyLight()
pocketmine\block\Block::blocksDirectSkyLight () inherited
Returns whether this block blocks direct sky light from passing through it. This is independent from the light filter value, which is used during propagation.
In most cases, this is the same as isTransparent(); however, some special cases exist such as leaves and cobwebs, which don't have any additional effect on light propagation, but don't allow direct sky light to pass through.
Reimplemented in pocketmine\block\Cobweb, and pocketmine\block\Leaves.
Definition at line 379 of file Block.php.
burnsForever()
pocketmine\block\Block::burnsForever () inherited
Returns whether fire lit on this block will burn indefinitely.
Reimplemented in pocketmine\block\Bedrock, pocketmine\block\Magma, and pocketmine\block\Netherrack.
Definition at line 536 of file Block.php.
calculateIntercept()
pocketmine\block\Block::calculateIntercept (Vector3 $pos1, Vector3 $pos2) inherited
Performs a ray trace along the line between the two positions using the block's collision boxes. Returns the intersection point closest to pos1, or null if no intersection occurred.
Definition at line 722 of file Block.php.
canBeFlowedInto()
pocketmine\block\Flowable::canBeFlowedInto () inherited
AKA: Block->isFlowable
Reimplemented from pocketmine\block\Block.
Reimplemented in pocketmine\block\UnderwaterTorch.
Definition at line 35 of file Flowable.php.
canBePlaced()
pocketmine\block\Block::canBePlaced () inherited
AKA: Block->isPlaceable
Reimplemented in pocketmine\block\Air, and pocketmine\block\UnknownBlock.
Definition at line 233 of file Block.php.
canBePlacedAt()
pocketmine\block\Block::canBePlacedAt (Block $blockReplace, Vector3 $clickVector, int $face, bool $isClickedBlock) inherited
Returns whether this block can replace the given block in the given placement conditions. This is used to allow slabs of the same type to combine into double slabs.
Reimplemented in pocketmine\block\SeaPickle, pocketmine\block\Slab, and pocketmine\block\WaterLily.
Definition at line 248 of file Block.php.
canBeReplaced()
pocketmine\block\Block::canBeReplaced () inherited
Returns whether this block can be replaced by another block placed in the same position.
Reimplemented in pocketmine\block\Air, pocketmine\block\DoubleTallGrass, pocketmine\block\Fire, pocketmine\block\Liquid, pocketmine\block\SnowLayer, pocketmine\block\TallGrass, and pocketmine\block\Vine.
Definition at line 240 of file Block.php.
canClimb()
pocketmine\block\Block::canClimb () inherited
Returns whether entities can climb up this block.
Reimplemented in pocketmine\block\Ladder, and pocketmine\block\Vine.
Definition at line 401 of file Block.php.
collidesWithBB()
pocketmine\block\Block::collidesWithBB (AxisAlignedBB $bb) inherited
Returns whether any of the block's collision boxes intersect with the given AxisAlignedBB.
Definition at line 613 of file Block.php.
References pocketmine\math\AxisAlignedBB\intersectsWith().
getAffectedBlocks()
pocketmine\block\Block::getAffectedBlocks () inherited
Returns a list of blocks that this block is part of. In most cases, only contains the block itself, but in cases such as double plants, beds and doors, will contain both halves.
Returns
Block[]
Reimplemented in pocketmine\block\Bed, pocketmine\block\Door, and pocketmine\block\DoublePlant.
Definition at line 599 of file Block.php.
getAge()
pocketmine\block\NetherWartPlant::getAge ()
Definition at line 52 of file NetherWartPlant.php.
getAllSides()
pocketmine\block\Block::getAllSides () inherited
Returns the six blocks around this block.
Returns
Block[]|\Generator @phpstan-return \Generator<int, Block, void, void>
Definition at line 586 of file Block.php.
getBreakInfo()
pocketmine\block\Block::getBreakInfo () inherited
Returns an object containing information about the destruction requirements of this block.
Definition at line 282 of file Block.php.
getCollisionBoxes()
pocketmine\block\Block::getCollisionBoxes () final inherited
Returns an array of collision bounding boxes for this block. These are used for:
entity movement collision checks (to ensure entities can't clip through blocks)
projectile flight paths
block placement (to ensure the player can't place blocks inside itself or another entity)
anti-cheat checks in plugins
Returns
AxisAlignedBB[]
Definition at line 676 of file Block.php.
getDrops()
pocketmine\block\Block::getDrops (Item $item) inherited
Returns an array of Item objects to be dropped
Returns
Item[]
Reimplemented in pocketmine\block\Bed, pocketmine\block\Door, pocketmine\block\DoublePlant, pocketmine\block\Lectern, pocketmine\block\NetherPortal, pocketmine\block\UnknownBlock, and pocketmine\block\Vine.
Definition at line 421 of file Block.php.
getDropsForCompatibleTool()
pocketmine\block\NetherWartPlant::getDropsForCompatibleTool (Item $item)
Returns an array of Items to be dropped when the block is broken using the correct tool type.
Returns
Item[]
Reimplemented from pocketmine\block\Block.
Definition at line 94 of file NetherWartPlant.php.
getDropsForIncompatibleTool()
pocketmine\block\Block::getDropsForIncompatibleTool (Item $item) inherited
Returns the items dropped by this block when broken with an incorrect tool type (or tool with a too-low tier).
Returns
Item[]
Reimplemented in pocketmine\block\DeadBush, pocketmine\block\DoubleTallGrass, and pocketmine\block\TallGrass.
Definition at line 447 of file Block.php.
getFlameEncouragement()
pocketmine\block\Block::getFlameEncouragement () inherited
Returns the chance that the block will catch fire from nearby fire sources. Higher values lead to faster catching fire.
Reimplemented in pocketmine\block\Bookshelf, pocketmine\block\Carpet, pocketmine\block\Coal, pocketmine\block\DeadBush, pocketmine\block\DoublePlant, pocketmine\block\DriedKelp, pocketmine\block\FenceGate, pocketmine\block\Flower, pocketmine\block\HayBale, pocketmine\block\Leaves, pocketmine\block\Planks, pocketmine\block\TallGrass, pocketmine\block\TNT, pocketmine\block\Vine, pocketmine\block\Wood, pocketmine\block\WoodenFence, pocketmine\block\WoodenSlab, pocketmine\block\WoodenStairs, and pocketmine\block\Wool.
Definition at line 522 of file Block.php.
getFlammability()
pocketmine\block\Block::getFlammability () inherited
Returns the base flammability of this block. Higher values lead to the block burning away more quickly.
Reimplemented in pocketmine\block\Bookshelf, pocketmine\block\Carpet, pocketmine\block\Coal, pocketmine\block\DeadBush, pocketmine\block\DoublePlant, pocketmine\block\DriedKelp, pocketmine\block\FenceGate, pocketmine\block\Flower, pocketmine\block\HayBale, pocketmine\block\Leaves, pocketmine\block\Lectern, pocketmine\block\Planks, pocketmine\block\TallGrass, pocketmine\block\TNT, pocketmine\block\Vine, pocketmine\block\Wood, pocketmine\block\WoodenFence, pocketmine\block\WoodenSlab, pocketmine\block\WoodenStairs, and pocketmine\block\Wool.
Definition at line 529 of file Block.php.
getFrictionFactor()
pocketmine\block\Block::getFrictionFactor () inherited
Returns a multiplier applied to the velocity of entities moving on top of this block. A higher value will make the block more slippery (like ice).
Returns
float 0.0-1.0
Reimplemented in pocketmine\block\BlueIce, pocketmine\block\Ice, pocketmine\block\PackedIce, and pocketmine\block\Slime.
Definition at line 349 of file Block.php.
getFuelTime()
pocketmine\block\Block::getFuelTime () inherited
Returns the time in ticks which the block will fuel a furnace for.
Reimplemented in pocketmine\block\Barrel, pocketmine\block\Bookshelf, pocketmine\block\Chest, pocketmine\block\Coal, pocketmine\block\CraftingTable, pocketmine\block\DaylightSensor, pocketmine\block\DriedKelp, pocketmine\block\FenceGate, pocketmine\block\FletchingTable, pocketmine\block\Jukebox, pocketmine\block\Note, pocketmine\block\Planks, pocketmine\block\Sapling, pocketmine\block\Wood, pocketmine\block\WoodenFence, pocketmine\block\WoodenPressurePlate, pocketmine\block\WoodenSlab, and pocketmine\block\WoodenTrapdoor.
Definition at line 507 of file Block.php.
getFullId()
pocketmine\block\Block::getFullId () inherited
Definition at line 113 of file Block.php.
getHorizontalSides()
pocketmine\block\Block::getHorizontalSides () inherited
Returns the 4 blocks on the horizontal axes around the block (north, south, east, west)
Returns
Block[]|\Generator @phpstan-return \Generator<int, Block, void, void>
Definition at line 573 of file Block.php.
getId()
pocketmine\block\Block::getId () inherited
Deprecated:
Returns the legacy numeric Minecraft block ID.
Reimplemented in pocketmine\block\DaylightSensor, pocketmine\block\FloorCoralFan, pocketmine\block\Furnace, pocketmine\block\Liquid, pocketmine\block\RedstoneComparator, pocketmine\block\RedstoneLamp, pocketmine\block\RedstoneOre, pocketmine\block\RedstoneRepeater, pocketmine\block\RedstoneTorch, pocketmine\block\Slab, and pocketmine\block\WallCoralFan.
Definition at line 101 of file Block.php.
Referenced by pocketmine\item\Bucket\onInteractBlock().
getIdInfo()
pocketmine\block\Block::getIdInfo () inherited
Returns an object containing information about how to identify and store this block type, such as its legacy numeric ID(s), tile type (if any), and legacy variant metadata.
Definition at line 85 of file Block.php.
Referenced by pocketmine\block\BlockFactory\register().
getLightFilter()
pocketmine\block\Block::getLightFilter () inherited
Returns the amount of light this block will filter out when light passes through this block. This value is used in light spread calculation.
Returns
int 0-15
Reimplemented in pocketmine\block\Ice, and pocketmine\block\Water.
Definition at line 368 of file Block.php.
getLightLevel()
pocketmine\block\Block::getLightLevel () inherited
Returns the amount of light emitted by this block.
Returns
int 0-15
Reimplemented in pocketmine\block\Beacon, pocketmine\block\BlueIce, pocketmine\block\BrownMushroom, pocketmine\block\DragonEgg, pocketmine\block\EnderChest, pocketmine\block\EndPortalFrame, pocketmine\block\EndRod, pocketmine\block\Fire, pocketmine\block\Furnace, pocketmine\block\GlowingObsidian, pocketmine\block\Glowstone, pocketmine\block\Lantern, pocketmine\block\Lava, pocketmine\block\LitPumpkin, pocketmine\block\Magma, pocketmine\block\NetherPortal, pocketmine\block\RedstoneLamp, pocketmine\block\RedstoneOre, pocketmine\block\RedstoneTorch, pocketmine\block\SeaLantern, pocketmine\block\SeaPickle, and pocketmine\block\Torch.
Definition at line 358 of file Block.php.
getMaxStackSize()
pocketmine\block\Block::getMaxStackSize () inherited
Returns the maximum number of this block that can fit into a single item stack.
Reimplemented in pocketmine\block\BaseBanner, pocketmine\block\BaseSign, and pocketmine\block\ShulkerBox.
Definition at line 514 of file Block.php.
getMeta()
pocketmine\block\Block::getMeta () inherited
Deprecated:
Returns the legacy Minecraft block meta value. This is a mixed-purpose value, which is used to store different things for different blocks.
Definition at line 135 of file Block.php.
getModelPositionOffset()
pocketmine\block\Block::getModelPositionOffset () inherited
Returns an additional fractional vector to shift the block model's position by based on the current position. Used to randomize position of things like bamboo canes and tall grass.
Reimplemented in pocketmine\block\Bamboo.
Definition at line 693 of file Block.php.
getName()
pocketmine\block\Block::getName () inherited
Returns the printable English name of the block.
Definition at line 92 of file Block.php.
getPickedItem()
pocketmine\block\Block::getPickedItem (bool $addUserData = false) inherited
Returns the item that players will equip when middle-clicking on this block. If addUserData is true, additional data may be added, such as banner patterns, chest contents, etc.
Reimplemented in pocketmine\block\BaseBanner, pocketmine\block\Beetroot, pocketmine\block\Carrot, pocketmine\block\CocoaBlock, pocketmine\block\Farmland, pocketmine\block\FlowerPot, pocketmine\block\ItemFrame, pocketmine\block\Potato, pocketmine\block\ShulkerBox, and pocketmine\block\Wheat.
Definition at line 489 of file Block.php.
References pocketmine\item\Item\setCustomBlockData(), and pocketmine\item\Item\setLore().
getPosition()
pocketmine\block\Block::getPosition () final inherited
Definition at line 405 of file Block.php.
getSide()
pocketmine\block\Block::getSide (int $side, int $step = 1) inherited
Returns the Block on the side $side, works like Vector3::getSide()
Returns
Block
Definition at line 559 of file Block.php.
Referenced by pocketmine\block\Stem\onRandomTick(), pocketmine\block\Fence\readStateFromWorld(), pocketmine\block\Thin\readStateFromWorld(), and pocketmine\block\Wall\readStateFromWorld().
getSilkTouchDrops()
pocketmine\block\Block::getSilkTouchDrops (Item $item) inherited
Returns an array of Items to be dropped when the block is broken using a compatible Silk Touch-enchanted tool.
Returns
Item[]
Reimplemented in pocketmine\block\InfestedStone.
Definition at line 456 of file Block.php.
getStateBitmask()
pocketmine\block\NetherWartPlant::getStateBitmask ()
Returns a bitmask used to extract state bits from block metadata. This is used to remove unwanted information from the legacy meta value when getting the block as an item.
Reimplemented from pocketmine\block\Block.
Definition at line 48 of file NetherWartPlant.php.
getSupportType()
pocketmine\block\Flowable::getSupportType (int $facing) inherited
Returns the type of support that the block can provide on the given face. This is used to determine whether blocks placed on the given face can be supported by this block.
Reimplemented from pocketmine\block\Block.
Reimplemented in pocketmine\block\SnowLayer.
Definition at line 50 of file Flowable.php.
getTypeId()
pocketmine\block\Block::getTypeId () inherited
Returns a type ID that identifies this type of block. This does not include information like facing, open/closed, powered/unpowered, etc.
Definition at line 209 of file Block.php.
getXpDropAmount()
pocketmine\block\Block::getXpDropAmount () protected inherited
Returns how much XP this block will drop when broken with an appropriate tool.
Reimplemented in pocketmine\block\CoalOre, pocketmine\block\DiamondOre, pocketmine\block\EmeraldOre, pocketmine\block\LapisOre, pocketmine\block\MonsterSpawner, pocketmine\block\NetherQuartzOre, and pocketmine\block\RedstoneOre.
Definition at line 474 of file Block.php.
getXpDropForTool()
pocketmine\block\Block::getXpDropForTool (Item $item) inherited
Returns how much XP will be dropped by breaking this block with the given item.
Definition at line 463 of file Block.php.
hasEntityCollision()
pocketmine\block\Block::hasEntityCollision () inherited
Returns whether the block has actions to be executed when an entity enters its cell (full cube space).
See also
Block::onEntityInside()
Reimplemented in pocketmine\block\Cactus, pocketmine\block\Cobweb, pocketmine\block\Fire, pocketmine\block\Ladder, pocketmine\block\Liquid, pocketmine\block\Magma, pocketmine\block\SweetBerryBush, pocketmine\block\TNT, pocketmine\block\Vine, and pocketmine\block\WoodenButton.
Definition at line 628 of file Block.php.
isAffectedBySilkTouch()
pocketmine\block\Block::isAffectedBySilkTouch () inherited
Returns whether Silk Touch enchanted tools will cause this block to drop as itself.
Reimplemented in pocketmine\block\BaseCoral, pocketmine\block\Bookshelf, pocketmine\block\Clay, pocketmine\block\CoalOre, pocketmine\block\Cobweb, pocketmine\block\CoralBlock, pocketmine\block\DeadBush, pocketmine\block\DiamondOre, pocketmine\block\EmeraldOre, pocketmine\block\EnderChest, pocketmine\block\Glass, pocketmine\block\GlassPane, pocketmine\block\Glowstone, pocketmine\block\Grass, pocketmine\block\GrassPath, pocketmine\block\Gravel, pocketmine\block\Ice, pocketmine\block\InfestedStone, pocketmine\block\LapisOre, pocketmine\block\Leaves, pocketmine\block\Melon, pocketmine\block\MushroomStem, pocketmine\block\Mycelium, pocketmine\block\NetherQuartzOre, pocketmine\block\PackedIce, pocketmine\block\RedMushroomBlock, pocketmine\block\RedstoneOre, pocketmine\block\SeaLantern, and pocketmine\block\Snow.
Definition at line 481 of file Block.php.
isFlammable()
pocketmine\block\Block::isFlammable () inherited
Returns whether this block can catch fire.
Definition at line 543 of file Block.php.
isFullCube()
pocketmine\block\Block::isFullCube () inherited
Definition at line 712 of file Block.php.
isSameState()
pocketmine\block\Block::isSameState (Block $other) inherited
Returns whether the given block has the same type and properties as this block.
Definition at line 226 of file Block.php.
isSameType()
pocketmine\block\Block::isSameType (Block $other) inherited
Returns whether the given block has an equivalent type to this one. This compares the type IDs.
Note: This ignores additional IDs used to represent additional states. This means that, for example, a lit furnace and unlit furnace are considered the same type.
Definition at line 219 of file Block.php.
Referenced by pocketmine\block\Chest\onPostPlace(), pocketmine\block\Stem\onRandomTick(), and pocketmine\block\Liquid\onScheduledUpdate().
isSolid()
pocketmine\block\Flowable::isSolid () inherited
Reimplemented from pocketmine\block\Block.
Definition at line 39 of file Flowable.php.
isTransparent()
pocketmine\block\Transparent::isTransparent () inherited
Reimplemented from pocketmine\block\Block.
Definition at line 34 of file Transparent.php.
onAttack()
pocketmine\block\Block::onAttack (Item $item, int $face, ?Player $player = null) inherited
Called when this block is attacked (left-clicked) by a player attempting to start breaking it in survival.
Returns
bool if an action took place, prevents starting to break the block if true.
Reimplemented in pocketmine\block\DragonEgg, pocketmine\block\ItemFrame, and pocketmine\block\Lectern.
Definition at line 339 of file Block.php.
onBreak()
pocketmine\block\Block::onBreak (Item $item, ?Player $player = null) inherited
Do the actions needed so the block is broken with the Item
Reimplemented in pocketmine\block\Ice, pocketmine\block\Jukebox, and pocketmine\block\TNT.
Definition at line 289 of file Block.php.
onEntityInside()
pocketmine\block\Block::onEntityInside (Entity $entity) inherited
Called when an entity's bounding box clips inside this block's cell. Note that the entity may not be intersecting with the collision box or bounding box.
WARNING: This will not be called if Block::hasEntityCollision() returns false.
Returns
bool Whether the block is still the same after the intersection. If it changed (e.g. due to an explosive being ignited), this should return false.
Reimplemented in pocketmine\block\Cactus, pocketmine\block\Cobweb, pocketmine\block\Fire, pocketmine\block\Ladder, pocketmine\block\Lava, pocketmine\block\Magma, pocketmine\block\NetherPortal, pocketmine\block\SweetBerryBush, pocketmine\block\TNT, pocketmine\block\Vine, and pocketmine\block\Water.
Definition at line 641 of file Block.php.
onEntityLand()
pocketmine\block\Block::onEntityLand (Entity $entity) inherited
Called when an entity lands on this block (usually due to falling).
Returns
float|null The new vertical velocity of the entity, or null if unchanged.
Reimplemented in pocketmine\block\Bed, pocketmine\block\Farmland, pocketmine\block\HayBale, and pocketmine\block\Slime.
Definition at line 662 of file Block.php.
onIncinerate()
pocketmine\block\Block::onIncinerate () inherited
Called when this block is burned away by being on fire.
Reimplemented in pocketmine\block\TNT.
Definition at line 550 of file Block.php.
onInteract()
pocketmine\block\Block::onInteract (Item $item, int $face, Vector3 $clickVector, ?Player $player = null) inherited
Do actions when interacted by Item. Returns if it has done anything
Reimplemented in pocketmine\block\Anvil, pocketmine\block\Bamboo, pocketmine\block\BambooSapling, pocketmine\block\Barrel, pocketmine\block\Bed, pocketmine\block\Bell, pocketmine\block\BrewingStand, pocketmine\block\Button, pocketmine\block\Cake, pocketmine\block\ChemistryTable, pocketmine\block\Chest, pocketmine\block\CocoaBlock, pocketmine\block\CraftingTable, pocketmine\block\Crops, pocketmine\block\DaylightSensor, pocketmine\block\Dirt, pocketmine\block\Door, pocketmine\block\DragonEgg, pocketmine\block\EnchantingTable, pocketmine\block\EnderChest, pocketmine\block\FenceGate, pocketmine\block\FlowerPot, pocketmine\block\Furnace, pocketmine\block\Grass, pocketmine\block\Hopper, pocketmine\block\ItemFrame, pocketmine\block\Jukebox, pocketmine\block\Lectern, pocketmine\block\Lever, pocketmine\block\Loom, pocketmine\block\Pumpkin, pocketmine\block\RedstoneComparator, pocketmine\block\RedstoneOre, pocketmine\block\RedstoneRepeater, pocketmine\block\Sapling, pocketmine\block\SeaPickle, pocketmine\block\ShulkerBox, pocketmine\block\Stonecutter, pocketmine\block\Sugarcane, pocketmine\block\SweetBerryBush, pocketmine\block\TNT, pocketmine\block\Trapdoor, and pocketmine\block\Wood.
Definition at line 330 of file Block.php.
onNearbyBlockChange()
pocketmine\block\NetherWartPlant::onNearbyBlockChange ()
Called when this block or a block immediately adjacent to it changes state.
Reimplemented from pocketmine\block\Block.
Definition at line 72 of file NetherWartPlant.php.
onPostPlace()
pocketmine\block\Block::onPostPlace () inherited
Called immediately after the block has been placed in the world. Since placement uses a block transaction, some things may not be possible until after the transaction has been executed.
Reimplemented in pocketmine\block\BaseRail, and pocketmine\block\Chest.
Definition at line 275 of file Block.php.
onRandomTick()
pocketmine\block\NetherWartPlant::onRandomTick ()
Called when this block is randomly updated due to chunk ticking. WARNING: This will not be called if Block::ticksRandomly() does not return true!
Reimplemented from pocketmine\block\Block.
Definition at line 82 of file NetherWartPlant.php.
onScheduledUpdate()
pocketmine\block\Block::onScheduledUpdate () inherited
Called when this block is updated by the delayed blockupdate scheduler in the world.
Reimplemented in pocketmine\block\BrewingStand, pocketmine\block\Button, pocketmine\block\CoralBlock, pocketmine\block\DaylightSensor, pocketmine\block\Fire, pocketmine\block\FrostedIce, pocketmine\block\Furnace, pocketmine\block\Hopper, pocketmine\block\Lectern, pocketmine\block\Liquid, and pocketmine\block\MonsterSpawner.
Definition at line 323 of file Block.php.
place()
pocketmine\block\NetherWartPlant::place (BlockTransaction $tx, Item $item, Block $blockReplace, Block $blockClicked, int $face, Vector3 $clickVector, ?Player $player = null)
Generates a block transaction to set all blocks affected by placing this block. Usually this is just the block itself, but may be multiple blocks in some cases (such as doors).
Parameters
BlockTransaction $tx Blocks to be set should be added to this transaction (do not modify thr world directly)
Item $item Item used to place the block
Block $blockReplace Block expected to be replaced
Block $blockClicked Block that was clicked using the item
int $face Face of the clicked block which was clicked
Vector3 $clickVector Exact position inside the clicked block where the click occurred, relative to the block's position
Player | null $player Player who placed the block, or null if it was not a player
Returns
bool whether the placement should go ahead
Reimplemented from pocketmine\block\Block.
Definition at line 63 of file NetherWartPlant.php.
position()
pocketmine\block\Block::position (World $world, int $x, int $y, int $z) final inherited
Definition at line 412 of file Block.php.
readStateFromData()
pocketmine\block\NetherWartPlant::readStateFromData (int $id, int $stateMeta)
Exceptions
InvalidBlockStateException
Reimplemented from pocketmine\block\Block.
Definition at line 44 of file NetherWartPlant.php.
readStateFromWorld()
pocketmine\block\Block::readStateFromWorld () inherited
Called when this block is created, set, or has a neighbouring block update, to re-detect dynamic properties which are not saved on the world.
Clears any cached precomputed objects, such as bounding boxes. Remove any outdated precomputed things such as AABBs and force recalculation.
Reimplemented in pocketmine\block\BaseBanner, pocketmine\block\BaseSign, pocketmine\block\Bed, pocketmine\block\Coral, pocketmine\block\Door, pocketmine\block\Fence, pocketmine\block\FlowerPot, pocketmine\block\ItemFrame, pocketmine\block\Jukebox, pocketmine\block\Lectern, pocketmine\block\Liquid, pocketmine\block\Note, pocketmine\block\RedstoneComparator, pocketmine\block\RedstoneWire, pocketmine\block\ShulkerBox, pocketmine\block\Skull, pocketmine\block\Stair, pocketmine\block\Thin, and pocketmine\block\Wall.
Definition at line 171 of file Block.php.
recalculateCollisionBoxes()
pocketmine\block\Flowable::recalculateCollisionBoxes () protected inherited
Returns
AxisAlignedBB[]
Reimplemented from pocketmine\block\Block.
Reimplemented in pocketmine\block\Carpet, pocketmine\block\EndRod, pocketmine\block\FlowerPot, pocketmine\block\RedstoneComparator, pocketmine\block\RedstoneRepeater, pocketmine\block\Skull, pocketmine\block\SnowLayer, pocketmine\block\Vine, and pocketmine\block\WaterLily.
Definition at line 46 of file Flowable.php.
setAge()
pocketmine\block\NetherWartPlant::setAge (int $age)
Returns
$this
Definition at line 55 of file NetherWartPlant.php.
ticksRandomly()
pocketmine\block\NetherWartPlant::ticksRandomly ()
Returns whether random block updates will be done on this block.
Reimplemented from pocketmine\block\Block.
Definition at line 78 of file NetherWartPlant.php.
writeStateToItemMeta()
pocketmine\block\Block::writeStateToItemMeta () protected inherited
Definition at line 141 of file Block.php.
writeStateToMeta()
pocketmine\block\NetherWartPlant::writeStateToMeta () protected
Reimplemented from pocketmine\block\Block.
Definition at line 40 of file NetherWartPlant.php.
writeStateToWorld()
pocketmine\block\Block::writeStateToWorld () inherited
Writes information about the block into the world. This writes the blockstate ID into the chunk, and creates and/or removes tiles as necessary.
Note: Do not call this directly. Pass the block to World::setBlock() instead.
Reimplemented in pocketmine\block\BaseBanner, pocketmine\block\BaseSign, pocketmine\block\Bed, pocketmine\block\FlowerPot, pocketmine\block\ItemFrame, pocketmine\block\Jukebox, pocketmine\block\Lectern, pocketmine\block\Note, pocketmine\block\RedstoneComparator, pocketmine\block\ShulkerBox, and pocketmine\block\Skull.
Definition at line 181 of file Block.php.
Member Data Documentation
$age
int pocketmine\block\NetherWartPlant::$age = 0 protected
Definition at line 38 of file NetherWartPlant.php.
$breakInfo
BlockBreakInfo pocketmine\block\Block::$breakInfo protected inherited
Definition at line 58 of file Block.php.
$collisionBoxes
array pocketmine\block\Block::$collisionBoxes = null protected inherited
Definition at line 62 of file Block.php.
$fallbackName
string pocketmine\block\Block::$fallbackName protected inherited
Definition at line 57 of file Block.php.
$idInfo
BlockIdentifier pocketmine\block\Block::$idInfo protected inherited
Definition at line 56 of file Block.php.
$position
Position pocketmine\block\Block::$position protected inherited
Definition at line 59 of file Block.php.
INTERNAL_METADATA_BITS
const pocketmine\block\Block::INTERNAL_METADATA_BITS = 4 inherited
Definition at line 53 of file Block.php.
INTERNAL_METADATA_MASK
const pocketmine\block\Block::INTERNAL_METADATA_MASK = ~(~0 << self::INTERNAL_METADATA_BITS) inherited
Definition at line 54 of file Block.php.
MAX_AGE
const pocketmine\block\NetherWartPlant::MAX_AGE = 3
Definition at line 36 of file NetherWartPlant.php.
The documentation for this class was generated from the following file:
NetherWartPlant.php